### ISSUE TITLE
catkin config sourcing with fish shell

### ISSUE THREAD

**Issue by luisrayas3** [ros/catkin#1002]
The following fails in bash as shown.
```
$ catkin config --source-space . --extend /opt/ros/kinetic --cmake-args -DCMAKE_BUILD_TYPE=Release
/usr/bin/fish: unrecognized option '--norc'
WARNING: Sourced environment from `/opt/ros/kinetic/env.sh` has no environment variables. Something is wrong.
Error: Could not load environment from workspace: '/opt/ros/kinetic', target environment (env.sh) does not provide 'CMAKE_PREFIX_PATH'
{}
```
Interestingly somehow its trying to call fish, and while fish is my default shell, I am running the command in bash. On a whim I even tried changing my login shell with `chsh` to `/bin/bash` with no luck.

Just to be sure I also looked at `/opt/ros/kinetic/env.sh` as well as `/opt/ros/kinetic/setup.sh` and sure enough setup.sh includes the line
```
export CMAKE_PREFIX_PATH
```

I've tried to figure out where in the catkin codebase env.sh is being sourced to see what shell it uses and can't figure it out.

**Comment by dirk-thomas** [comment]
The unrecognized option `--norc` seems to come from [catkin_tools](https://github.com/catkin/catkin_tools/blob/e1042f7ff1eff139b264b874f7b4bb95ef4cbf52/catkin_tools/resultspace.py#L128) (not from `catkin`). Please report your problem in the https://github.com/catkin/catkin_tools repo instead.

**Comment by luisrayas3** [comment]
ah, thanks!
