### ISSUE TITLE
setup.zsh corrupts PATH

### ISSUE THREAD

**Issue by janEbert** [ros/catkin#1005]
Hey, I am on Kinetic using Zsh with oh-my-zsh on a netboot machine.
When sourcing the setup.zsh in my catkin devel space, my PATH gets all messed up.
```zsh
$ catkin clean --force --yes && catkin b
$ source [...]/devel/setup.zsh
/opt/ros/kinetic/etc/catkin/profile.d/00.rtt.sh:10: command not found: grep
/opt/ros/kinetic/etc/catkin/profile.d/00.rtt.sh:10: command not found: grep
/opt/ros/kinetic/etc/catkin/profile.d/00.rtt.sh:10: command not found: grep
/opt/ros/kinetic/etc/catkin/profile.d/00.rtt.sh:10: command not found: grep
/opt/ros/kinetic/etc/catkin/profile.d/1.ros_package_path.sh:4: command not found: cat
/opt/ros/kinetic/etc/catkin/profile.d/99.roslisp.sh:4: command not found: cat
/opt/ros/kinetic/etc/catkin/profile.d/99.roslisp.sh:21: command not found: python
prompt_status:5: command not found: wc
$ echo $PATH
/opt/ros/kinetic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/kinetic
prompt_status:5: command not found: wc
```

[This comment](https://github.com/ros/catkin/issues/686#issuecomment-59845054) in #686 (and consequent PR #688) fixes the problem again but was not merged in favor of #692.

At least for me, the previously proposed solution (#688) works where the second (#692) doesn't. :)

I have also tried multiple ways of emulating other shells using Zsh, some of which did not end in an error, but which did not correctly set all environment variables.
For example, `emulate sh -c 'source [...]/devel/setup.sh'` did not add the catkin devel space's Python site-packages to `PYTHONPATH` although other paths were not missing from it.

**Comment by dirk-thomas** [comment]
I tried to reproduce the problem with the ROS Melodic Debian packages and I was able to source `/opt/ros/melodic/setup.zsh` in a `zsh` shell just fine.

Please try to reproduce the problem with the current ROS distro, with either the binaries or a build using `catkin_make(_isolated)` and no additional packages (e.g. the one which provides `00.rtt.sh`) in order to narrow down where the problem is.

**Comment by janEbert** [comment]
We switched to Melodic now and everything works fine just like you said. :)
Thanks!
