### ISSUE TITLE
gtest warning in a stack installed through rosinstall

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#101]
-- RT_LIBRARY: /usr/lib/x86_64-linux-gnu/librt.so
CMake Warning (dev) at /opt/ros/fuerte/share/catkin/cmake/tools/gtest.cmake:33 (set):
  Cannot set "GTEST_INCLUDE_DIRS": current scope has no parent.
Call Stack (most recent call first):
  /opt/ros/fuerte/share/catkin/cmake/all.cmake:53 (include)
  /opt/ros/fuerte/share/catkin/cmake/catkin-config.cmake:6 (include)
  CMakeLists.txt:25 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/ros/fuerte/share/catkin/cmake/tools/gtest.cmake:34 (set):
  Cannot set "GTEST_LIBRARIES": current scope has no parent.
Call Stack (most recent call first):
  /opt/ros/fuerte/share/catkin/cmake/all.cmake:53 (include)
  /opt/ros/fuerte/share/catkin/cmake/catkin-config.cmake:6 (include)
  CMakeLists.txt:25 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/ros/fuerte/share/catkin/cmake/tools/gtest.cmake:35 (set):
  Cannot set "GTEST_MAIN_LIBRARIES": current scope has no parent.
Call Stack (most recent call first):
  /opt/ros/fuerte/share/catkin/cmake/all.cmake:53 (include)
  /opt/ros/fuerte/share/catkin/cmake/catkin-config.cmake:6 (include)
  CMakeLists.txt:25 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/ros/fuerte/share/catkin/cmake/tools/gtest.cmake:36 (set):
  Cannot set "GTEST_BOTH_LIBRARIES": current scope has no parent.
Call Stack (most recent call first):
  /opt/ros/fuerte/share/catkin/cmake/all.cmake:53 (include)
  /opt/ros/fuerte/share/catkin/cmake/catkin-config.cmake:6 (include)
  CMakeLists.txt:25 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/ros/fuerte/share/catkin/cmake/tools/gtest.cmake:37 (set):
  Cannot set "GTEST_FOUND": current scope has no parent.
Call Stack (most recent call first):
  /opt/ros/fuerte/share/catkin/cmake/all.cmake:53 (include)
  /opt/ros/fuerte/share/catkin/cmake/catkin-config.cmake:6 (include)
  CMakeLists.txt:25 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

And my mine CMake installed through rosinstall looks like this:
# 
# TOPLEVEL cmakelists
# 

cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0003 NEW)
cmake_policy(SET CMP0011 NEW)

set(CMAKE_CXX_FLAGS_INIT "-Wall")
project('toto')
enable_testing()

include(${CMAKE_SOURCE_DIR}/workspace-config.cmake OPTIONAL)

list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_BINARY_DIR}/cmake)

file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

if (IS_DIRECTORY ${CMAKE_SOURCE_DIR}/catkin)
  message(STATUS "+++ catkin")
  set(CATKIN_BUILD_PROJECTS "ALL" CACHE STRING
    "List of projects to build, or ALL for all.  Use to completely exclude certain projects from cmake traversal.")
  add_subdirectory(catkin)
else()
  find_package(catkin)
endif()

catkin_workspace()

**Comment by mkjaergaard** [comment]
I suggest we move the find_package of gtest out of catkin, its a weird dependency to have.
We can potentially move it to rostest, or even better, to the individual packages that uses gtest.

**Comment by gerkey** [comment]
6ba2675 sets those vars in the CACHE, instead of using PARENT_SCOPE.  That should remove the warnings.

I don't think that moving gtest out is the right thing to do.  catkin is a build system, and a build system should support testing.  And we're providing first-class support for gtest in particular, because it's easy to use and widely used.  

It's not a requirement in any case: if gtest isn't found, catkin will simply print a warning and continue.  There won't be errors unless somebody calls `add_gtest()`.
