### ISSUE TITLE
Support Git Bash on Windows

### ISSUE THREAD

**Issue by johnwason** [ros/catkin#1035]
I am running into a "line too long" error during `catkin_make_isolated` on Windows when using lots of packages. This appears to be caused by the various environmental variables in env.bat becoming longer than the 8191 character limit allowed in a batch file. Using Git Bash instead of cmd would fix this issue and be more familiar to users from Linux. Git Bash shouldn't have this same limitation.

I submitted an issue to RosOnWindows (https://github.com/ms-iot/ROSOnWindows/issues/157) but it appears this is actually being configured by catkin.

**Comment by dirk-thomas** [comment]
If the shell doesn't support long environment variables you need to use a merged install spaces instead. `bat` certainly falls into that category. I don't know about Git bash.

Assuming there is nothing `catkin` can do about I am going ahead and close this issue.

**Comment by johnwason** [comment]
The `--merge` option failed with an error "Command "*" not found".

Can you briefly describe how and where the environment files are generated for the workspace and primary ROS install directory (ie /opt/ros/melodic/setup.bash). I can create a patch fairly quickly but it isn't clear how these files are generated.

**Comment by johnwason** [comment]
We are attempting to work around the limitations of the Windows build environment here: https://github.com/Jmeyer1292/opw_kinematics/pull/33

**Comment by dirk-thomas** [comment]
> Can you briefly describe how and where the environment files are generated for the workspace and primary ROS install directory (ie /opt/ros/melodic/setup.bash).

The function `catkin_generate_environment` called from [here](https://github.com/ros/catkin/blob/0d245cb80fd62053ba6bcc33b888e97c1588188e/cmake/all.cmake#L190) generates the prefix level files.

There is some conditional logic to only have one Debian package generate them: https://github.com/ros/catkin/blob/0d245cb80fd62053ba6bcc33b888e97c1588188e/cmake/all.cmake#L78-L86

**Comment by johnwason** [comment]
I'v created a script that will read the environmental variables set in a batch file and export back to Git Bash. This allows Git Bash to be used normally by sourcing setup.bat like this:

    source source_bat.bash "c:\opt\ros\melodic\x64\setup.bat"

This does not solve the "line too long" problem, but otherwise allows for Git Bash to be used.
