### ISSUE TITLE
Generated .pc files should use ${prefix}

### ISSUE THREAD

**Issue by Hugal31** [ros/catkin#1036]
The pkg-config file generated by `catkin_package()` defines a `prefix` variable, but do not make use of it and repeat `@PROJECT_SPACE_DIR` multiple times in the file.

Here in the [template file](https://github.com/ros/catkin/blob/kinetic-devel/cmake/em/pkg.pc.em):

```em
prefix=@PROJECT_SPACE_DIR
//...
Libs: -L@PROJECT_SPACE_DIR/lib @(' '.join(PKG_CONFIG_LIBRARIES_WITH_PREFIX))
```
vs
```em
prefix=@PROJECT_SPACE_DIR
// ...
Libs: -L${prefix}/lib @(' '.join(PKG_CONFIG_LIBRARIES_WITH_PREFIX))
```

This matters, because pkg-config can fix relocated packages with the `--define-prefix` flag, which cause the `prefix` variable to be redefined. But it is unused by the generated files.

To fix it, we should simply replace `@PROJECT_SPACE_DIR` by `${prefix}` in the file, and when building the `PKG_CONFIG_LIBRARIES_WITH_PREFIX` and `PROJECT_PKG_CONFIG_INCLUDE_DIRS` variables.

**Comment by dirk-thomas** [comment]
Please provide a pull request with the proposed change.
