### ISSUE TITLE
tests should run even some tests failed to compile

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#106]
A failure during `make tests` will stop `make test` from running.  That, combined with the dummy-result-synthesis, makes a failure look like a clean build.

Targets should be restructured so that a failure to compile (some) tests doesn't prevent running tests.

Also, reconsider the dummy-test-synthesis.  Perhaps it's better to allow Jenkins to flag a test-less build as an error, and require developers to add dummy tests.

**Comment by dirk-thomas** [comment]
duplicated in #166 and currently ongoing effort
