### ISSUE TITLE
Switch to setuptools results in easy-install.pth in install tree

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#1060]
Expanding on https://github.com/ros/catkin/pull/1048#issuecomment-582014565, I believe the change to setuptools requires some additional work, as currently any ROS package that calls `catkin_python_setup` against a setuptools-importing `setup.py` is going to end up trying to install the same `lib/python3/dist-packages/easy-install.pth` file— which will result in ~~conflicts at debian package installation time or~~ potential concurrency issues with builders like colcon or catkin_tools.

I believe the resolution is to pass `setup.py` the `--single-version-externally-managed` flag, as I demonstrate with non-ROS python packages in `catkin_tools_python`, see:

https://github.com/mikepurvis/catkin_tools_python/blob/933fdeab46b4252e16e2128a22aa4f3388a9aaa4/catkin_tools_python/job.py#L115-L125

However, the difficulty with this is that that flag can't be silently ignored by setup files that still import distutils. So the script that pre-interrogates the `setup.py` needs to learn how to tell the difference between `import setuptools` and `import distutils` so that catkin can generate a slightly different `python_distutils_install` for the two cases.

Testing this exhaustively is tricky as there are at least four cases to cover: `import setuptools` with and without `DESTDIR`, and `import distutils` with and without `DESTDIR`.

**Comment by sloretz** [comment]
It looks like setuptools `--single-version-externally-managed` was made automatic when `--root` is passed https://github.com/pypa/setuptools/blob/master/CHANGES.rst#06a11 .  `--root` seems to be supported by both `distutils` and `setuptools`, is that an option catkin can use?

**Comment by sloretz** [comment]
It looks like if `DESTDIR` is specified then `--root` is used. That limits it to 3 cases: `DESTDIR` specified, `DESTDIR` not specified and `setuptools`, `DESTDIR` not specified and `distutils`. Can we eliminate the last two cases by always specifying `DESTDIR`? I don't know much about catkin's python package workflow. When is `DESTDIR` specified?

https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/templates/python_distutils_install.sh.in#L3-L12

https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/templates/python_distutils_install.bat.in#L3-L6

**Comment by mikepurvis** [comment]
I think `DESTDIR` is specified in the bloom packaging workflow, so that may be why this hasn't blown up more so far. But IMO, non-packaged installspaces shouldn't be different in this regard.

**Comment by mikepurvis** [comment]
Here's the beginnings of a version that explicitly passes the flag: https://github.com/ros/catkin/compare/noetic-devel...mikepurvis:add-setuptools-svem

However, if it's possible to trigger it just with `--root`, that would simplify things.

----

Preliminary testing looks like changing from:

```
--prefix="@CMAKE_INSTALL_PREFIX@"
--install-scripts="@CMAKE_INSTALL_PREFIX@/@CATKIN_GLOBAL_BIN_DESTINATION@"
```

to

```
--prefix=""
--root=${DESTDIR}@CMAKE_INSTALL_PREFIX@
--install-scripts="@CATKIN_GLOBAL_BIN_DESTINATION@"
```

Seems like it does the right thing. But I don't understand enough about these parameters to really appreciate the implications.

**Comment by mikepurvis** [comment]
Closing in favour of #1068.
