### ISSUE TITLE
catkin_make expects cmake_minimum_required 2.8.3 for metapackages

### ISSUE THREAD

**Issue by toliver** [ros/catkin#1064]
It seems that `catkin_make` always expects `cmake_minimum_required(VERSION 2.8.3)` for metapackages.

It checks that the metapackage CMakeLists.txt conforms exactly to the expected format [here](https://github.com/ros/catkin/blob/noetic-devel/cmake/catkin_workspace.cmake#L56-L72) and the build fails if it doesn't. The format has a fixed cmake version that seems to come from [here](https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/templates/metapackage.cmake.in).

What is the rationale for imposing a fixed version? If someone wants to force a higher minimum version for certain packages then they won't be able to do the same for the metapackage containing those packages.

I see that recently the minimum version was bumped for a number of packages and metapackages. (https://github.com/ros/catkin/pull/1052, https://github.com/ros/ros_comm/pull/1869 and other PRs). All these will probably build with with `catkin_make_isolated`, but I think they will no longer build with `catkin_make`.

**Comment by sloretz** [comment]
Seems like the check will need to be relaxed similar to https://github.com/ros-infrastructure/catkin_pkg/pull/274

**Comment by dirk-thomas** [comment]
Thanks for the report. Addressed by #1065.

**Comment by gavanderhoorn** [comment]
@toliver wrote:
> If someone wants to force a higher minimum version for certain packages then they won't be able to do the same for the metapackage containing those packages.

this sentence is strange: metapackages do not *contain* any other packages, and the contents of the `CMakeLists.txt` is fixed. Metapackages don't do anything.

I'm not saying it was wrong to relax the requirement, but there don't seem to be any adverse effects from stipulating a specific minimum version for metapackages.

**Comment by dirk-thomas** [comment]
> there don't seem to be any adverse effects from stipulating a specific minimum version for metapackages.

Yes, there is. If the minimum version is 2.8.3 as it was required before this change newer CMake versions print a CMP0048 warning.

**Comment by gavanderhoorn** [comment]
I would hardly call that an "adverse effect", but ok.

My point was that the OP implies this restriction being a serious one. Seeing as metapackages don't actually install anything, don't contain any CMake logic other than the prescribed content, don't "contain" other packages and don't have any way to enforce anything in other packages it really doesn't matter. Apart from an annoying warning from CMake when they are built.

**Comment by toliver** [comment]
@gavanderhoorn you are right that a metapackage doesn't _contain_ other packages, but it does _list_ or _group_ other packages (not sure what the correct term would be).

Even if it is not necessary to do so, it seems that many developers think it is sensible to bump the `cmake_minimum_required` version of a metapackage when they bump the version of all the packages listed in that metapackage.

That has happened in [ros_comm](https://github.com/ros/ros_comm/blob/melodic-devel/ros_comm/CMakeLists.txt#L1), [moveit](https://github.com/ros-planning/moveit/blob/master/moveit/CMakeLists.txt#L1) and others. After such changes the repository would fail to build with `catkin_make`.

I think important repos failing to build with `catkin_make` can be a serious problem for some people (like myself), which is why I posted this issue. And I'm glad it's been fixed. Thanks.
