### ISSUE TITLE
catkin_add_env_hooks does not copy updated files

### ISSUE THREAD

**Issue by garaemon** [ros/catkin#1072]
`catkin_add_env_hooks` uses  `file(COPY ...)` macro to copy env hook files (https://github.com/ros/catkin/blob/noetic-devel/cmake/catkin_add_env_hooks.cmake#L97).
`file` macro copies files at generation time and it does not copy files at build time.

**Comment by dirk-thomas** [comment]
Thanks for the report. Please see the proposed fix #1075.
