### ISSUE TITLE
Message generation sends invalid ARG_IFLAGS to gen_lisp.py

### ISSUE THREAD

**Issue by kwc** [ros/catkin#108]
gen_lisp.py received:

['std_msgs:', 'std_msgs:/Users/kwc/fuerte/src/std_msgs/msg', 'std_msgs:/Users/kwc/fuerte/src/std_msgs/msg']

The first arg is invalid (empty path).  The second and third are duplicates.  This is with up-to-date trees.

catkin: 06c5e8ca14d6e235fe537ed217543ab8ce1995f0

genmsg: bd28289e1cd90b1dc5498624d2c7498194b12079

genlisp: 2bdc396d66fa9e5b250bb05f522a42aaf713d1b1

**Comment by kwc** [comment]
can't reproduce with std_msgs anymore, but actionlib_msgs does show this issue:

```
//dir containing messages in genmsg
actionlib_MSG_INCLUDE_DIRS:FILEPATH=/u/kwc/fuerte/build/actionlib/actions_gen;/u/kwc/fuerte/build/actionlib/actions_gen;/u/kwc/fuerte/build/actionlib/actions_gen
```

**Comment by dirk-thomas** [comment]
this has likely been fixed a long time ago
