### ISSUE TITLE
Cannot create catkin package due to egg_base error

### ISSUE THREAD

**Issue by stertingen** [ros/catkin#1087]
Right now I'm porting the `catkin` package on Arch Linux to Noetic. Catkin 0.8.1 works fine, 0.8.3 not. The `package()` step executes `make DESTDIR=xxx install` which fails:

```
+ cd /home/hermann/ros-noetic-arch/ros-noetic-catkin/src/catkin-0.8.3
+ mkdir -p /home/hermann/ros-noetic-arch/ros-noetic-catkin/pkg/ros-noetic-catkin//opt/ros/noetic/lib/python3.8/site-packages
+ /usr/bin/env PYTHONPATH=/opt/ros/noetic/lib/python3.8/site-packages:/home/hermann/ros-noetic-arch/ros-noetic-catkin/src/build/lib/python3.8/site-packages: CATKIN_BINARY_DIR=/home/hermann/ros-noetic-arch/ros-noetic-catkin/src/build /usr/bin/python3 /home/hermann/ros-noetic-arch/ros-noetic-catkin/src/catkin-0.8.3/setup.py egg_info --egg-base /opt/ros/noetic/lib/python3.8/site-packages build --build-base /home/hermann/ros-noetic-arch/ros-noetic-catkin/src/build install --root=/home/hermann/ros-noetic-arch/ros-noetic-catkin/pkg/ros-noetic-catkin/ --prefix=/opt/ros/noetic --install-scripts=/opt/ros/noetic/bin
running egg_info
error: error in 'egg_base' option: '/opt/ros/noetic/lib/python3.8/site-packages' does not exist or is not a directory
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):
  
  execute_process(/home/hermann/ros-noetic-arch/ros-noetic-catkin/src/build/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:171 (include)


make: *** [Makefile:82: install] Error 1
```

`ros-noetic-catkin` is the first package to install to `/opt/ros/noetic` because all other packages depend on it, so it does not exist yet.

This might be related to https://github.com/ros/catkin/pull/1073.

**Comment by stertingen** [comment]
Appendix: `sudo mkdir -p /opt/ros/noetic/lib/python3.8/site-packages` does not solve the issue, it complains about missing permissions. I guess the `DESTDIR` argument passed to make is not handled correctly.

**Comment by dirk-thomas** [comment]
> The `package()` step executes `make DESTDIR=xxx` install which fails:

Can you please include more context what exact commands you are invoking.

> This might be related to #1073.

Maybe try to prepend the `--egg-base` with the `DESTDIR` environment variable (when available)?

**Comment by stertingen** [comment]
> > The `package()` step executes `make DESTDIR=xxx` install which fails:
> 
> Can you please include more context what exact commands you are invoking.

That's the build script: (sorry, I forgot to include it earlier)
https://github.com/ros-noetic-arch/ros-noetic-catkin/blob/master/PKGBUILD

First, `build()` is executed with `$srcdir` pointing to the directory where the catkin source archive is extracted.

Then, `package()` is executed with `$pkgdir` pointing to a directory with is used to create the package archive later. When the package is installed to the system, the archive is extracted to the system root, so after the `package()` command, `${pkgdir}/opt/ros/noetic` should be a valid path.

> > This might be related to #1073.
> 
> Maybe try to prepend the --egg-base with the DESTDIR environment variable (when available)?

~AFAIK `DESTDIR` is not an environment variable, it's an argument passed to make, so this might make things more interesting.~ DESTDIR is passed as environment variable to sub processes. Pretending `$ENV{DESTDIR}` will probaply work.

Right now, I have only time to try this in my spare time on the weekend, but I see if I can look into this.

Might be helpful (for me or the one who fixes this):
https://cmake.org/cmake/help/v3.0/command/install.html?highlight=destdir
https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html?highlight=destdir
