### ISSUE TITLE
setup.sh mixes up DYLD_LIBRARY_PATH and LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#109]
I notice that the setup.sh in fuerte reads:
 DYLD_LIBRARY_PATH=/opt/ros/fuerte/lib:$LD_LIBRARY_PATH

as opposed to
  =... :$DYLD_LIBRARY_PATH

Looks like a bug to me.

**Comment by gerkey** [comment]
Well-spotted.  2b1ce1b
