### ISSUE TITLE
Possible error in the auto-generated comments provided by catkin_create_pkg?

### ISSUE THREAD

**Issue by adlarkin** [ros/catkin#1094]
I'm using ROS melodic on Ubuntu 18.04. When I call `catkin_create_pkg`, I'm given a `CMakeLists.txt` and `package.xml` file that have auto-generated comments in them. The comments in the `package.xml` state:

```
<!-- Use depend as a shortcut for packages that are both build and exec dependencies -->
<!--   <depend>roscpp</depend> -->
<!--   Note that this is equivalent to the following: -->
<!--   <build_depend>roscpp</build_depend> -->
<!--   <exec_depend>roscpp</exec_depend> -->
```

However, according to [REP 140](https://www.ros.org/reps/rep-0140.html#depend-multiple):

`A <depend> tag is equivalent to specifying <build_depend>, <build_export_depend> and <exec_depend>, all on the same package or key.`

Is it possible that the auto-generated comments for `package.xml` created by `catkin_create_pkg` need to be updated, or am I misunderstanding something here?

**Comment by dirk-thomas** [comment]
`catkin_create_pkg` is provided by a different repository: https://github.com/ros-infrastructure/catkin_pkg/blob/a8c785601af7bb1b981d3694bca9996c28929baa/bin/catkin_create_pkg

There is no difference in outcome to specify a `build_export_depend` and a `exec_depend`. Both will become a run dependency in the Debian package. The template could be updated to list both - it just wouldn't make any difference.

**Comment by adlarkin** [comment]
Thanks for the explanation. I'm closing this issue since your response answered my question
