### ISSUE TITLE
integrate testing 

### ISSUE THREAD

**Issue by straszheim** [ros/catkin#11]
integration of unit tests.  test results go only in build directory.  Nothing is ever written to home directory.  Python unit tests TBD... do we just pivot off of some definition of tests in setup.py and leave it at that?

**Comment by straszheim** [comment]
first we need a cmake interface, then Brian and Ken make the ros utils work.

**Comment by kwc** [comment]
nosetests, gtest, and pyunit integrated.  Brian is now working on rostest. Current implementation only allows tests at the top-level, which is not ideal.

**Comment by gerkey** [comment]
all types of tests (nose,gtest,pyunit,rostest) are now enabled, with post-test verification of the generation of result files (to catch compile failures and program crashes).

The top-level-only 'make test' target remains an issue.

**Comment by gerkey** [comment]
There's already a per-project test target.  You can do this:
make (package_or_stack)_run_tests
And you'll get just those tests.

At this point, testing integration is basically done.  Ticket specific problem separately.
