### ISSUE TITLE
Make dependency management easier while using `catkin` 

### ISSUE THREAD

**Issue by kunaltyagi** [ros/catkin#1104]
For C++, there's no good management for dependencies. `catkin`-less CMake+package.xml do solve the issue to a large extent.

However, virtual environments are common for managing dependencies for ROS and Python users.

While working with several projects, it's common to have separate workspaces as well as virtual environments. This workflow is very common (and dare I say: required) to manage conflicting dependencies in Python. Would it be possible for `catkin init` to detect if it's in a virtual environment?

---
If yes:

An invocation similar to `catkin init --with-venv` or a prompt after detection of virtual env can be used such that `. CATKIN_ROOT/install/setup.*` and `. CATKIN_ROOT/devel/setup.*` both also activate the relevant virtual env?

Detection of venv is not complicated (but has edge cases): https://stackoverflow.com/a/58026969/

**Comment by Rayman** [comment]
I think you are talking about the command line `catkin` which is hosted here: https://github.com/catkin/catkin_tools

There are several projects that try to improve working with virtualenvs and python. I've not worked with them but you could take a look:
https://github.com/locusrobotics/catkin_virtualenv
https://catkin-pip.readthedocs.io/en/latest/
