### ISSUE TITLE
CATKIN_PACKAGE_LIBEXEC_DESTINATION mentioned in docs is not implemented

### ISSUE THREAD

**Issue by rsinnet** [ros/catkin#1118]
The documentation mentions the CMake variable `CATKIN_PACKAGE_LIBEXEC_DESTINATION`.
https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/doc/user_guide/variables.rst#L53

In addition, we see the following mentions in configure files:
https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/templates/cfg-extras.context.py.in#L19
https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/templates/env-hook.context.py.in#L19

Looking through the code, we see no mention of such a variable.
https://github.com/ros/catkin/blob/dfc93c72d9799f57442d08c2f6e9fd494bba95c1/cmake/catkin_destinations.cmake

Is this a real variable or perhaps something that was envisioned but never implemented?

**Comment by rsinnet** [comment]
@dirk-thomas I think this is your code?

**Comment by dirk-thomas** [comment]
That variable is indeed not populated atm.

Would you be willing to create a pull request either removing the variable or filling it with an actual value?
