### ISSUE TITLE
Can't find nosetests executable.... Archlinux

### ISSUE THREAD

**Issue by hauptmech** [ros/catkin#112]
function(add_nosetests   fails.  On archlinux nosetests is suffixed with the version. (nosetests2)

**Comment by hauptmech** [comment]
diff --git a/cmake/tests.cmake.in b/cmake/tests.cmake.in
index dbf2d23..6d0d873 100644
--- a/cmake/tests.cmake.in
+++ b/cmake/tests.cmake.in
@@ -110,8 +110,11 @@ function(add_nosetests dir)
   # Check that nosetests is installed.
   find_program(nosetests_path nosetests)
   if(NOT nosetests_path)
-  find_program(nosetests_path nosetests2)
-  if(NOT nosetests_path)
   message(FATAL_ERROR "Can't find nosetests executable... try installing package 'python-nose'")
  endif()
-  endif()
  
  parse_arguments(_nose "WORKING_DIRECTORY" "" ${ARGN})
  if(_nose_WORKING_DIRECTORY)

**Comment by gerkey** [comment]
Addressed by #115
