### ISSUE TITLE
Why two back-to-back executions of 'catkin_make' command in same terminal in ROS Noetic on Ubuntu 20.04 gives totally different results on terminal ?

### ISSUE THREAD

**Issue by ghost** [ros/catkin#1125]
Why the two back-to-back executions of 'catkin_make' command in same terminal in ROS Noetic on Ubuntu 20.04 gives totally different results on terminal ? I am providing the terminal output in the two snaps for two executions of catkin_make command.

ROS Noetic, Ubuntu 20.04 
![a1](https://user-images.githubusercontent.com/54470916/97164706-8d72fd00-17a8-11eb-8914-fa6bba77780a.png)
![b1](https://user-images.githubusercontent.com/54470916/97164728-92d04780-17a8-11eb-9b3d-9b823ea80372.png)

**Comment by xqms** [comment]
Hey, just saw this by chance. As far as I can tell everything is normal. During the first run, CMake figures out where to find your compiler, libraries, etc and generates Makefiles. If you don't change your CMakeLists.txt files, this step will not be done again, so your next invocation directly starts with compilation.

By the way, the place to ask questions like this is https://answers.ros.org. Use GitHub issues for bug reports :)

**Comment by tfoote** [comment]
This is standard cmake caching. If you want to know more please read some more about how CMake works. Note that if there's no changed source files it will actually not even recompile your code again either to save you time. 

But as mentioned this is a question and not an issue so please use answers.ros.org instead.
