### ISSUE TITLE
`catkin_install_python` fails when shebang is followed by a space

### ISSUE THREAD

**Issue by maetulj** [ros/catkin#1155]
I am porting a python script from melodic to noetic. To convert the shebang from python to python3 I am using `catkin_install_python` as suggested in [the migration guide](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs).

The function successfully converted all the shebangs from `#!/usr/bin/env python` to `#!/usr/bin/env python3` except for one file where it failed. After comparing it for some time I noticed that the erroneous script has a shebang ending with a space character before the new line (represented here as &#9608;):
`#!/usr/bin/env python`&#9608;`\n`

This breaks the `catkin_install_python` function and the "installed" file starts with an incorrect  shebang.

**Comment by Rayman** [comment]
If you want, you could contribute a PR to adjust the regex for this:
https://github.com/ros/catkin/blob/7fa3eb3508ba12c34d85b8e54bbdf4bbdc60a5c1/cmake/catkin_install_python.cmake#L30

**Comment by ivanpauno** [comment]
Fixed in https://github.com/ros/catkin/pull/1156.
