### ISSUE TITLE
Catkin init  detect symbolic  link as source

### ISSUE THREAD

**Issue by soner4** [ros/catkin#1175]
Hi 
I  recently  ported my packages to Ubuntu 20.04 from 16.04. Inside the  catkin_ws  I linked the src folder to another path. I  init the workspace and the Source Space is directed to the linked location. 

The compilation works fine but when I try to launch a file it shows the launch file exists in two separate folders.
`xepost@xepost-20:~/catkin_ws$ catkin init `
`Catkin workspace /home/xepost/catkin_ws is already initialized. No action taken.`
`----------------------------------------------------------------------------------`
`Profile:                     default`
`Extending:          [cached] /home/xepost/catkin_ws/devel:/opt/ros/noetic`
`Workspace:                   /home/xepost/catkin_ws`
`----------------------------------------------------------------------------------`
`Build Space:        [exists] /home/xepost/catkin_ws/build`
`Devel Space:        [exists] /home/xepost/catkin_ws/devel`
`Install Space:      [exists] /home/xepost/catkin_ws/install`
`Log Space:          [exists] /home/xepost/catkin_ws/logs`
`Source Space:       [exists] /media/storage/test/wd/ ros_test_src`
`DESTDIR:            [unused] None`
`----------------------------------------------------------------------------------`
`Devel Space Layout:          linked`
`Install Space Layout:        merged`
`----------------------------------------------------------------------------------`
`Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release`
`Additional Make Args:        None`
`Additional catkin Make Args: None`
`Internal Make Job Server:    True`
`Cache Job Environments:      False`
`----------------------------------------------------------------------------------`
`Buildlisted Packages:        None`
`Skiplisted Packages:         None`
`----------------------------------------------------------------------------------`

On the  Ubuntu 16.04, Ros Kinetic  the   setting  show  as  catkin_ws/src

`Source Space:       [exists] /home/xepost/catkin_ws/src `

The compilation works fine for both cases but when I try to launch a file it thinks the launch file exists in two separate folders.

`RLException: multiple files named [far_test.launch] in package [apriltags_ros]:`
`-  /media/storage/test/wd/ ros_test_src/apriltags_ros/apriltags_ros/launch/far_test.launch`
`- /home/xepost/catkin_ws/src/apriltags_ros/apriltags_ros/launch/far_test.launch`

 I know the trivial solution is removing the symlink and putting the packages inside catkin_ws/src folder,  yes it works but it creates other complications on my side. 

How can I fix this issue ?  Any suggestion is appreciated.

**Comment by gbiggs** [comment]
This question is better suited to ROS Answers. Please see the [ROS support guide](http://wiki.ros.org/action/fullsearch/Support).

**Comment by soner4** [comment]
Thanks, for the suggestion. The main question is not how  I should run the launch files. It is why catkin uses the target path rather than the link path. And how can I disable it? On Ubuntu 16.04 it was using the link path.

**Target path:** /media/storage/test/wd/ ros_test_src
**Link path:**  /home/xepost/catkin_ws/src
