### ISSUE TITLE
How to install catkin on ros2

### ISSUE THREAD

**Issue by liaoran** [ros/catkin#1178]
OS: Ubuntu22.04 LTS
Python version: 3.10.4
I have a test project that needs to use catkin_make, but I can't install it when I use apt install catkin, and there is currently no documentation to learn from. I haven't found a solution through Google search, please help!

**Comment by gbiggs** [comment]
Catkin is a tool for ROS 1, not ROS 2. You need to set up the package repositories for ROS as specified in the [ROS installation instructions](http://wiki.ros.org/ROS/Installation) before you can install catkin.

**Comment by liaoran** [comment]
> Catkin is a tool for ROS 1, not ROS 2. You need to set up the package repositories for ROS as specified in the [ROS installation instructions](http://wiki.ros.org/ROS/Installation) before you can install catkin.

Hello, what can I use to achieve the function of catkin_make in ROS 2

**Comment by gbiggs** [comment]
ROS 2 uses [colcon](https://colcon.readthedocs.io/en/released/).

**Comment by liaoran** [comment]
> ROS 2 uses [colcon](https://colcon.readthedocs.io/en/released/).

Thanks!

**Comment by TurnOffNOD** [comment]
> [colcon](https://colcon.readthedocs.io/en/released/).

Hi, is colcon maintained by ros2 official develop group?
