### ISSUE TITLE
Support branching in release system

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#118]
From @tfoote:

Brian Wim and I have had a short discussion about what will be necessary looking forward to branching development for groovy. 

To be able to make this work we believe that the best way to make this work is to add branch information to catkin.conf (right now it assumes default) and for simplicity we will simply have different gbp repos for each rosdistro.  

We talked about deprecating catkin-set-upstream so people understand it's simply editing catkin.conf in the other branch.  But Wim and I talked about it later and thought that the auto switching to the branch and autocreation of the orphan branch is a very useful capability.

**Comment by gerkey** [comment]
From @kwc:

The release process is already too many manual commands and easy to
mess up; automating it will likely end up reproducing
catkin-set-upstream.

With the current release instructions, its very easy to get the GBP
repo into a conflicting state, especially since the push phase
requires two separate commands.  I've witnessed both myself and others
mess up the command sequence and either get the repo into a
conflicting state (e.g. because didn't do a pull at the start), or
because one or more of the pushes didn't go, or because you have
leftover local state.  Ideally, an automated script would do a fresh
clone and blow it away at the end so you don't end up using a repo in
a bad state.

Speaking of updates to the system: AFAIK, there's no way to rollback a
release with the GBP system, right?  It always picks the tag with the
highest version number.  Given that I just had to rollback a 'dry'
stack today, we will need to get this capability somehow.

i.e., right now

GBP repo = https://code.ros.org/svn/release/download/stacks/$STACK-NAME
fuerte.yaml + GBP repo tags = rosdistro

So either fuerte.yaml or the GBP repo state needs to be remodeled.

**Comment by gerkey** [comment]
One of the proposed changes is to make the branch/tag explicit in the
catkin.conf file.  Then we would remove the logic from
catkin-import-upstream that infers the tag from the upstream
stack.yaml.

**Comment by gerkey** [comment]
From @kwc:

Another example of what happens when the system doesn't know what the
actual desired version number is (note 0.12.8 suddenly becomes
0.12.7):

The latest upstream tag in the release repo is upstream/0.12.8
Upstream version is: 0.12.8
.. snip ...
- cd . && git add debian
- cd . && git commit -m + Creating debian mods for distro: lucid,
  rosdistro: fuerte, upstream version: 0.12.7
  [master a3103e3] + Creating debian mods for distro: oneiric,
  rosdistro: fuerte, upstream version: 0.12.7
  1 files changed, 1 insertions(+), 1 deletions(-)
  tag: debian/ros-fuerte-rospkg_0.12.7_oneiric
- cd . && git tag -f debian/ros-fuerte-rospkg_0.12.7_oneiric -m Debian
  release 0.12.7
  Updated tag 'debian/ros-fuerte-rospkg_0.12.7_oneiric' (was d67b9c6)

**Comment by dirk-thomas** [comment]
this is handled by bloom (not by catkin anymore) and has already been realized
