### ISSUE TITLE
circular dependency when using test_depend

### ISSUE THREAD

**Issue by fraukej** [ros/catkin#1182]
I have two packages, test1 and test2.
test1 is dependent on test2.
test2 is dependent on test1, but only for testing.

package.xml for test1:
```
<?xml version="1.0"?>
<package format="2">
  <name>test1</name>
  <version>0.0.0</version>
  <description>The test1 package</description>

  <maintainer email="bob@todo.todo">bob</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>test2</depend>

  <export>
  </export>
</package>
```

package.xml for test2:
```
<?xml version="1.0"?>
<package format="2">
  <name>test2</name>
  <version>0.0.0</version>
  <description>The test2 package</description>

  <maintainer email="bob@todo.todo">bob</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <test_depend>test1</test_depend>

  <export>
  </export>
</package>
```

Running catkin_make with `-DCATKIN_ENABLE_TESTING=OFF` or `-DCATKIN_SKIP_TESTING=ON` or both, I get the error: "Circular dependency in subset of packages:  test1, test2"

However, I thought I skipped testing / disabled it, so <test_depend> would not be used. Why is it used anyway?

For testing, wouldn't it be theoretically be possible to build test2, then test1 (witouht tests) and then build the tests for test2? Why isn't this possible?

**Comment by gbiggs** [comment]
Catkin does not have the ability to only build part of a package, so it can't break the circular dependency. You will need to break it yourself, such as by breaking apart one of the packages.
