### ISSUE TITLE
Placement of '/etc/ros/rosdep/sources.list.d' on OS X

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#119]
So, when I run rosdep on OS X I get:

```
    ∫ rosdep check ros_comm

ERROR: Rosdep experienced an internal error: [Errno 2] No such file or directory: '/etc/ros/rosdep/sources.list.d'
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 109, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 220, in _rosdep_main
    check_for_sources_list_init(options.sources_cache_dir)
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 166, in check_for_sources_list_init
    filelist = [f for f in os.listdir(get_sources_list_dir()) if f.endswith('.list')]
OSError: [Errno 2] No such file or directory: '/etc/ros/rosdep/sources.list.d'
```

So obviously there is no `/etc/ros/rosdep/sources.list.d` on the Mac, but the question is where should it go?

So if you follow the Homebrew isolation principals it should go in /usr/local/etc/..., but since this is a Python package I am not sure where it should go.  Perhaps it should go in `#{Python_prefix}/etc` or similar.

Input?

Furthermore, how does this list of repos get populated on Linux?  Is this part of the dpkg or is pip supposed to populate this and fails quietly on Mac?

Also, how does rosdep handle multiple versions of ROS being installed at the same time.  Is it the goal to decouple ROS versions from dependency versions?

**Comment by wjwwood** [comment]
So this is all kinds of wrong, sorry.

This needs to be on the rosdep tracker (where is that btw still on trac.ros.org?), also forgot to run `rosdep init`, which is where you get the repo lists from.

My apologies.

**Comment by tfoote** [comment]
For the new version in fuerte it is installed by rosdep init.  Before using rosdep you need to "sudo rosdep init&& rosdep update" before you use any rosdep rules.   See http://ros.org/doc/api/rosdep2/html/overview.html

There's probably a better place to put them.  I suggest we move the discussion to the rosdep ticket system: https://code.ros.org/trac/ros/ticket/3910
