### ISSUE TITLE
missing msg file for action message under /opt/ros/furte/share/

### ISSUE THREAD

**Issue by k-okada** [ros/catkin#122]
Missing msg/ directory for action/ message in packages under /opt/ros/furte/share/.
Other packages under /opt/ros/electric/stacks/navigation/move_base_msgs contains both action/ and msg/ directory.

See. http://answers.ros.org/question/31818/is-actionlibmsg-directory-deprecated-in-fuerte for more info.

**Comment by kwc** [comment]
This appears to be a catkin bug in add_action_files.   add_message/service_files auto-mark the files for installation.  As add_action_files bypasses this, it should do the same

**Comment by kwc** [comment]
Actually, its just that the add_message_files macro does not parse the arguments correctly or makes bad assumptions.  The files are being installed under /opt/ros/fuerte/share, but in:

./actionlib/tmp/buildd/ros-fuerte-actionlib-1.8.4-1lucid-20120413-1654/obj-x86_64-linux-gnu/actions_gen/TestRequestActionResult.msg

**Comment by k-okada** [comment]
congratulations for fuerte release! I just want to confirm that this problem will be fixed in future fuerte release?

**Comment by dirk-thomas** [comment]
The issue has been fixed in Groovy some time ago. But the fix requires certain changes in the genmsg CMake macros/functions which can not easily backported to Fuerte. There I will mark this request for Fuerte as "wont fix".
