### ISSUE TITLE
catkin's python_distutils_install.sh.in causes genlisp's homebrew formula to fail

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#123]
I have managed to auto generating homebrew formulae for packages listed in the `https://github.com/ros/rosdistro/blob/master/releases/fuerte.yaml` release list.  While testing the install of genlisp I ran into this problem:

```
Installed /usr/local/Cellar/genlisp/0.3.0/lib/python2.7/site-packages/genlisp-0.3.0-py2.7.egg
Processing dependencies for genlisp==0.3.0
Searching for genmsg
Reading http://pypi.python.org/simple/genmsg/
Couldn't find index page for 'genmsg' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for genmsg
error: Could not find suitable distribution for Requirement.parse('genmsg')
CMake Error at CMakeFiles/safe_execute_install.cmake:5 (message):
  Error executing process with arguments
Call Stack (most recent call first):
  cmake_install.cmake:51 (INCLUDE)


make: *** [install] Error 1
```

I think it has to do with this line in the `python_distutils_install.sh.in` file:

https://github.com/willowgarage/catkin/blob/master/cmake/templates/python_distutils_install.sh.in#L21

```
# todo --install-layout=deb per platform
/usr/bin/env \
    PYTHONPATH=@INSTALLED_PYTHONPATH@:@CMAKE_BINARY_DIR@/gen/py \
    CATKIN_BINARY_DIR=@CMAKE_BINARY_DIR@ \
    @PYTHON_EXECUTABLE@ \
    @CMAKE_CURRENT_SOURCE_DIR@/setup.py \
    install \
    $DESTDIR_ARG \
    @SETUPTOOLS_ARG_EXTRA@ --prefix=@CMAKE_INSTALL_PREFIX@
```

I think this line should include the PYTHONPATH from the environment.  When installing from via Homebrew each package's install prefix is `/usr/local/Cellar/<formula_name>/<version>/`, therefore genlisp installs it's python files to `/usr/local/Cellar/genlisp/version/lib/python2.7/site-packages`.  This is all fine but the problem is that the above line assumes that the target location for genlisp's egg is also going to contain genmsg's egg, but in this instance it doesn't at build/install time.  After the install is finished, they are all symlinked into `/usr/local/lib/python2.7/site-packages/`.  This causes the `make install` command to fail as above because it cannot find genmsg even though it is installed.

Normally, the work around is that I patch this file via Homebrew before calling make install to prevent this problem, but since it is part of catkin it's not local to the build environment until I run cmake, which is cumbersome.

What is the rational for excluding the PYTHONPATH from the environment in this case?  Should it be included?

**Comment by gerkey** [comment]
I've reproduced.  Working on a fix now.

**Comment by gerkey** [comment]
Added environment PYTHONPATH as suggested, 19b316c.  Tested in my repro setup and verified that it works.

**Comment by wjwwood** [comment]
Thanks Brian, I'll test this against genlisp ASAP.
