### ISSUE TITLE
Include contained ROS package names into description of debian stack package

### ISSUE THREAD

**Issue by ahornung** [ros/catkin#131]
Including the names of the ROS packages contained in the stack's debian package description makes it easy to search for the right package to install if there is a ROS package missing (apt-cache search <pkgname>). Finding the .deb package containing ROS package X is a question that comes up quite often ( http://answers.ros.org/question/1793/which-deb-package-contains-ros-package-x), and the current only workaround is using the wiki. This fails if there is a different version (distribution) documented than what is used in the system and the package moved into a different stack. 

The issue was already submitted 10 monthts ago (https://code.ros.org/trac/ros/ticket/3623) and closed due to the move to catkin, but I can't see that it's implemented in the current releases by catkin.

**Comment by ahornung** [comment]
E.g. "apt-cache search amcl" should turn up the navigation stack.

**Comment by dirk-thomas** [comment]
The description of all packages contained in a stack is embedded in the debian packages (not the stack description). I.e. call "apt-cache search multiarray" - this should list std-msgs (from Fuerte as well as Groovy).

**Comment by ahornung** [comment]
That works for multiarray, but not for amcl. I assume this is only in bloom / catkin? Could it be added to standard stacks with packages as well (see my original issue from 14 months ago)?

**Comment by ahornung** [comment]
Is this now the correct issue or a duplicate?
https://github.com/ros/bloom/issues/16

**Comment by wjwwood** [comment]
This is a bug in bloom, this issue is a duplicate/invalid tracker.
