### ISSUE TITLE
Unify build and install space

### ISSUE THREAD

**Issue by dirk-thomas** [ros/catkin#139]
Unify build and install space in order to be able to:
- load resources in build space
- run all tests in build space (i.e. pluginlib)
- be more FHS compliant

**Comment by housel** [comment]
The needs of cross-compilation should be taken into account when designing this.

**Comment by dirk-thomas** [comment]
Could you describe in more detail what you mean?

**Comment by housel** [comment]
See issue #143 for part of it. The build system needs to be aware that the build and install environments may be compiled for different architectures, and to distinguish between "native" (build system) and target system packages and other resources.

For cross-compilation, tests cannot be run in the build environment and need to be either skipped or deferred to the target environment.

**Comment by dirk-thomas** [comment]
Sure, but the reason for this issue is to make sure that the build-space acts as similar as an install-space as possible. Meaning you should be able to run everything in build-space with also works in install-space.

This should not be relevant for cross-compilation as you can never run the built binaries. And tests are not installed at all so they can not be run on the target-platform

**Comment by dirk-thomas** [comment]
This has finally been achieved in the last weeks.
