### ISSUE TITLE
Catkin's stack.xml files need the concept of all arch for debs or noarch for rpms

### ISSUE THREAD

**Issue by ngrennan** [ros/catkin#141]
I am working on making rpms for ros, and just made a catkin rpm. Technically in Fedora it should be a noarch rpm, because it doesn't have anything in it that is architecture dependent. I need a new field in stack.xml files to deal with this in a spec file generation bloom script. Technically this should also be done with deb packages too. Debian calls it all instead of noarch.

**Comment by housel** [comment]
This would be useful for OpenEmbedded too.

**Comment by tfoote** [comment]
We discussed this in the REP 127 review and as this is a packaging related thing we are not going to code it into the package.xml it should be more of a parameter at the bloom level.
