### ISSUE TITLE
Need to distinguish build-time dependencies for cross-compilation

### ISSUE THREAD

**Issue by housel** [ros/catkin#143]
For cross-compilation, the stack.xml build-time dependency list needs to distinguish between:
- Stacks or rosdeps that will be used as tools at build time. If these are compiled, they need to be for the build architecture.
- Stacks or rosdeps that provide header files and shared libraries that will be linked with the stack being built. These need to be for the target architecture.

At the moment there is not enough information to determine which is which.

**Comment by dirk-thomas** [comment]
The whole concept of catkin is to not rely on compiled stuff to build a workspace. The only exceptions are compilers and Python. Currently that includes:
- Python
- cmake
- gcc/g++
- qmake (if building qt stuff)
- sip / shiboken (if you generate Python bindings)

Integrating infrastructure to handle this seem to be very high cost. Probably it is easiest to put a proper comment in stack,xml where appropriate.

Do you have other cases which I am not aware of where tools are used in the buildstep which must match the build architecture?

**Comment by housel** [comment]
Right, so at the moment now there's no way of telling whether a build dependency is because something is being used as a build tool, or whether it's needed to link against.

As a concrete example, the stack.xml for ros_comm says:

```
<build_depends>apr</build_depends>
<build_depends>boost</build_depends>
<build_depends>catkin</build_depends>
<build_depends>genmsg</build_depends>
<build_depends>langs</build_depends> <!-- rosgraph_msgs, std_srvs -->
<build_depends>log4cxx</build_depends>
<build_depends>python-paramiko</build_depends>
<build_depends>python-yaml</build_depends>
<build_depends>ros</build_depends>
<build_depends>roscpp_core</build_depends>
<build_depends>std_msgs</build_depends>
```

My corresponding OpenEmbedded recipe's build dependencies end up looking like:

```
DEPENDS = "\
    ros-fuerte-catkin-native \
    ros-fuerte-ros \
    log4cxx \
    ros-fuerte-roscpp-core \
    ros-fuerte-gencpp-native \
    ros-fuerte-genpy-native \
    ros-fuerte-genlisp-native \
    apr \
    ros-fuerte-std-msgs \
    python-paramiko \
    boost \
    python-pyyaml \
"
```

This was hand-tweaked and I'm not certain it's correct (but it did build correctly). cmake-native, python-native, and the cross-compilers are additional inherent dependencies.

**Comment by housel** [comment]
Perhaps it might suffice to add a `<build_tool>` element to stack.xml, or an attribute such as `<build_depends use="tool">..</build_depends>`.

**Comment by tfoote** [comment]
Proposed in REP 127 and supported with

run_depends, build_depends, buildtool_depends, and test_depends.
