### ISSUE TITLE
documentation flaws

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#148]
Here is a list of things I missed in catkin documentation
- best practices of how to write a "clean" catkin CMakelists.txt are not complete, e.g. that catkin_project() should comme immediately after project() is mentioned elsewhere in catkin docu
- core ROS stacks in fuerte have a lot of variation in how the CMakelists.txt look, and some do not follow the cmake best practices. Those files are where developpers will copy&paste from, they need to be extra clean IMO (consider them part of catkin documentation for now)
- I don't understand what dependencies need to go into stack/stack.xml vs. stack/CMakelists.txt, and why fuerte ROS core stacks have redundant information there (e.g. ros_comm)
- The migration guide does not mention wet and dry (and the implication that one needs to make sure all dependencies are wet)
- The migration guide tells to delete manifest.xml, while the core ROS packages still have it. That's inconsistent, the migration guide should explain why it would be good to keep manifests for some time.
- The migration guide should explain that install targets are not required as long as one does not want to have an installable stack
- The migration guide currently does not mention the implication for rosws/rosinstall workspaces, e.g. a developer might think he can change one stack within his rosbuild workspace to catkin, and still continue to work with that workspace as before. Unless I am mistaken, currently we can only have fully wet or fully dry workspaces, right?

**Comment by dirk-thomas** [comment]
Please check the status of this issue.

**Comment by tkruse** [comment]
most of this is by now fixed, obsolete or being worked on, so I'll close this.
