### ISSUE TITLE
Replace catkin_sphinx

### ISSUE THREAD

**Issue by zklapow** [ros/catkin#149]
The documentation lists a catkin_sphinx() macro, however this does not appear to actually exist, and is a much needed feature.

**Comment by tfoote** [comment]
It's available here: https://github.com/ros/catkin-sphinx

**Comment by zklapow** [comment]
I found that but there is a catkin_sphinx macro in the docs that is no longer available.

**Comment by tfoote** [comment]
Ahh, just need to clean up the docs.

**Comment by dirk-thomas** [comment]
Doc updated in the meantime.
