### ISSUE TITLE
include dirs for catkin_project

### ISSUE THREAD

**Issue by isucan** [ros/catkin#150]
I seems that code like this:

catkin_project(${PROJECT_NAME} 
  LIBRARIES ${PROJECT_NAME}
  INCLUDE_DIRS include)

should also trigger an include_directories() command for INCLUDE_DIRS.

**Comment by vrabaud** [comment]
nope, the docs specify what this INCLUDE_DIRS is: it is for other packages that use it, not for itself to include directories
