### ISSUE TITLE
catkin should check stackname in stack.xml

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#151]
To reproduce, create to c++ catkin stacks, with the <name> value being the same for both packages. Not both packages are built. Catkin should warn the user. This is mostly an issue for new users doing their first step with catkin, having copied&pasted stack.xml and CMakelists from somewhere else, and forgetting to change the name (as project() and catkin_project()) already capture the same data twice.

If stack.xml goes away for manifest.xml, this ticket either applies to that as well, or becomes obsolete.

**Comment by dirk-thomas** [comment]
The current catkin version throws an ugly assertion. Nicer message should be easy...

**Comment by tfoote** [comment]
See my note on the commit.  It needs a sys.exit not just exit

**Comment by dirk-thomas** [comment]
fixed in 3098925687f7afaa84bdcb08752f683d63f4d770
