### ISSUE TITLE
catkin lint

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#153]
As long as catkin suggests/requires a a workspace layout with common cmake namespace and build space, I would find it helpful for users if a whitelist / blacklist of cmake functions was clearly defined, and a tool existed that checked the files.

A whitelist constains all constructs that are known to be conflict-free.

A blacklist contains all constructs that are known to be in conflict. All other ones are declared "unknown" and thus dangerous.

If the documentation existed, I could work on such a tool.

**Comment by jack-oquin** [comment]
I agree that this is badly needed. I was about to open a new issue for it, but discovered this 9-month-old one.

Catkin is so complex that even experts need help to figure out if their build files are logical and consistent and follow recommended practice.

**Comment by tkruse** [comment]
Also see:

More discussion on checking catkin packages for various flaws
https://groups.google.com/d/msg/ros-sig-buildsystem/HBHSTWx8lBo/GkFR17jwUyAJ

Related discussion:
https://groups.google.com/forum/?fromgroups=#!topic/ros-sig-buildsystem/sIWPA2A85Ks

Script prototype parsing catkin package manifest and CmakeLists.txt, can be extended for various checks
https://github.com/tkruse/catkin_pkg/blob/catkin_stats/bin/catkin_stats

**Comment by jbohren** [comment]
+1

**Comment by sotte** [comment]
I'm currently using catkinize a lot and something like catkin lint would be great!

**Comment by dirk-thomas** [comment]
The ticket is marked with the milestone "untargeted" since currently nobody plans to look into this. So without external contributions please don't expect any progress on this feature.

**Comment by jack-oquin** [comment]
If there are enough requests, maybe someone will decide to work on it.

**Comment by tfoote** [comment]
We've been looking at trying out [Bountysource](https://www.bountysource.com)

This might be a good test case: https://www.bountysource.com/issues/741065-catkin-lint

**Comment by jbohren** [comment]
+$5

**Comment by jack-oquin** [comment]
Bountysource is an interesting and innovative approach. 

But, let's not lose sight of the fact that catkin lint is not just a one-shot job. To useful, it will require on-going maintenance and enhancements. It may become unwieldy, paying for each upgrade separately.

**Comment by dirk-thomas** [comment]
If at any time someone will work on this feature it would be feasible to add hooks in catkin before and after each package has been configured (as described in #543).

**Comment by roehling** [comment]
I started work on a catkin linter recently. It's a static analyzer with a simple cmake parser that can handle the most common constructs.

https://github.com/fkie/catkin_lint

**Comment by dirk-thomas** [comment]
I will close this ticket since this won't be a feature provided by catkin itself but from a different package.

**Comment by jbohren** [comment]
@roehling I think you're owed $10 https://www.bountysource.com/issues/741065-catkin-lint
