### ISSUE TITLE
gtest needs to be integrated into catkin build

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#157]
See:

http://code.google.com/p/googletest/wiki/FAQ#Why_is_it_not_recommended_to_install_a_pre-compiled_copy_of_Goog

Following the recommendation above, Homebrew (OS X package manager) has removed gtest.  Catkin however will fail to build without it.  The recommendation is to integrate gtest into the catkin build system or make the gtest dependency optional.

Flann had a similar problem:

https://github.com/mxcl/homebrew/issues/14126

Homebrew issue related to this:

https://github.com/mxcl/homebrew/issues/14099

**Comment by dirk-thomas** [comment]
Ubuntu Precise ships the sources of gtest instead of binaries.
The current version of catkin already uses these and builds them for each workspace.

**Comment by wjwwood** [comment]
Is there a release of catkin with this feature yet?

**Comment by wjwwood** [comment]
I see that it is optional now, on Ubuntu it looks like it is expect the sources to be in `/usr/src/gtest/`.  Should we instead ship the gtest source with catkin and drop any dependency on a system gtest?  Or should I suggest that Homebrew carry the sources in a similar fashion to ubuntu?

**Comment by wjwwood** [comment]
Also, I can see that there isn't a new release with that fix yet.  I might do a patch for 0.4.5 in Homebrew in the mean time.

**Comment by dirk-thomas** [comment]
The catkin version released with Fuerte uses that approach already. See /opt/ros/fuerte/share/catkin/cmake/tools/gtest.cmake in your installation.

Bundling code from external projects is something we want to get rid of in the future for ROS. So I would suggest that Homebrew carries the sources in a similar fashion to Ubuntu.

**Comment by wjwwood** [comment]
I have suggested that be the case on the Homebrew mailing list just now, we'll see what they say.

Thanks.

**Comment by vrabaud** [comment]
I need to mention that Ubuntu has not fully switched to that solution either:
https://bugs.launchpad.net/ubuntu/+source/gtest/+bug/969556

But there seems to be a better/more flexible solution than my original patch:
http://stackoverflow.com/questions/9689183/cmake-googletest

any thoughts ? (I'd be down for it)

**Comment by wjwwood** [comment]
That looks like a portable solution, but does Google not recommend how to do this, or is this their recommendation?

**Comment by vrabaud** [comment]
That is not their official recommendation but that follows it (I am talking about the seonc link, not the first one): you just make gtest part of your workspace so that you build it with your flags. It works for me locally, I'll commit it after a meeting.

**Comment by vrabaud** [comment]
ok, I just added a very simple fix with ffd634cbf74752c61885acd08128c12eb4bfc5a9
We can add more paths to search for gtest as time goes by but for now it looks into the Ubuntu one and in a gtest folder in your workspace (which can be a straight checkout from the official gtest repo).
Bug closed indeed :)
