### ISSUE TITLE
Handling of Multiple Boost installs is broken in ROS Fuerte

### ISSUE THREAD

**Issue by Arrakis-10191** [ros/catkin#160]
Please see
http://answers.ros.org/question/42285/handling-of-multiple-boost-installs-is-broken-in-ros-fuerte/
for details

**Comment by wjwwood** [comment]
This is not a caktin bug, I posted a response on answers.ros.org.

**Comment by Arrakis-10191** [comment]
@wjwwood, you closed this ticket but you have not explained why ROS_BOOST_VERSION is not performing as it should be.  If it is not a catkin bug, can you please state how you came to this conclusion?

**Comment by wjwwood** [comment]
@Arrakis-10191 `ROS_BOOST_VERSION` is not part of catkin, if you think it is still an issue please open an issue against `rosboost_cfg`, which is in the `ros` repository:

https://github.com/ros/ros/tree/groovy-devel/tools/rosboost_cfg

As I mentioned in the post on ros answers, I think the reason that your getting the wrong version of Boost linked is that `rosboost_cfg` is not using the `Boost_LIBRARY_DIRS` CMake variable. This is probably a bug, but I haven't reproduced it nor have I looked into the code to see what's going on there. As I said before, you can likely prove that this is a bug if adding `link_directories(${Boost_LIBRARY_DIRS})` fixes your problem.

**Comment by Arrakis-10191** [comment]
@wjwwood  Thanks a lot
