### ISSUE TITLE
shebangline in catkin shell scripts

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#174]
catkin shell scripts should start with
# ! /usr/bin/env sh

or at least
# ! /usr/bin/env bash

instead of 
# ! /bin/bash

First of all, sh is more general than bash, and second other *nis OSes may put bash in other places than /bin.
I cannot do a pull request since I cannot tell whether the scripts require bash extentions or just sh. If they depend on bash, they probably should be rewritten to rely just on sh.

**Comment by tkruse** [comment]
this relates to 
bin/catkin-build-debs-of-workspace
bin/github   # That cannot be a good name for a global script 

but also to several template in:
$ find cmake/ |xargs grep '#!'

**Comment by dirk-thomas** [comment]
fixed where possible.
I.e. #!/usr/bin/env sh -x is not possible.
catkin-build-debs-of-workspace is neither used nor installed.
