### ISSUE TITLE
missing catkin_pkg

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#175]
# 7bf78e32ca9e88520deae extracted catkin_pkg, removed obsolete stuff, updated deps

is broken:
catkin_topological_order 
Traceback (most recent call last):
  File "./catkin_topological_order", line 13, in <module>
    from catkin.topological_order import topological_order
  File "./../python/catkin/topological_order.py", line 5, in <module>
    from catkin_pkg.package import parse_package
ImportError: No module named catkin_pkg.package

maybe forgot to git add a folder named catkin_pkg

**Comment by wjwwood** [comment]
This is now an external project to catkin, to make it easier for packages like rospkg, bloom, and others to depend on catkin related stuff.

https://github.com/ros-infrastructure/catkin_pkg

If catkin doesn't declare this dependency then this is a bug.

There are debs for this in shadow-fixed (python-catkin-pkg) and in pip (catkin_pkg).

**Comment by tkruse** [comment]
I see, sorry. I cannot install it via pip, though I see it on pypi. When will the sources be available on github?

**Comment by dirk-thomas** [comment]
You should install the Debian package "python-catkin-pkg".
It is also available on pypi with the name "catkin_pkg" but this is not recommended for platforms which support installing Debian packages.
The repository is located at https://github.com/ros-infrastructure/catkin_pkg

**Comment by tfoote** [comment]
The source is at: https://github.com/ros-infrastructure/catkin_pkg
