### ISSUE TITLE
update the docs

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#181]
- now that REP 127 is almost out, the docs should mention it more (at least on the migration guides)
- almost all instances of "stack.xml" should be replaced by "package.xml"
- the rosbuild_migration page should be completed for all the test macros (maybe a big TODO for what's missing ?)
  Thx.

**Comment by tkruse** [comment]
Please review #210 for a first fix of this.

**Comment by vrabaud** [comment]
ok, the first two points are fine. The test macros have not been updated though (rosbuild_add_rostest is now add_rostest and so on).

**Comment by dirk-thomas** [comment]
improved in ef79ed9e27c9356f0346bf70265db41c1c44c7ed
