### ISSUE TITLE
multiple debs per stack:  -dbg, -doc, -dev

### ISSUE THREAD

**Issue by straszheim** [ros/catkin#20]

**Comment by ethanrublee** [comment]
Could also be cool to have a deb for each catkin_project

**Comment by tfoote** [comment]
To do the dbg it looks like you need a --dbg-package arg to dh in your rules file.  
%:
        dh $@ --parallel --builddirectory=Build --dbg-package=PACKAGENAME-dbg

And an additional rule in the control file for the PACKAGENAME-dbg

**Comment by tfoote** [comment]
We may also need dh_strip 

dh_strip --dbg-package=PACKAGENAME-dbg

I haven't been able to find another technique.

**Comment by tfoote** [comment]
semi official way to do it by debian is here: http://wiki.debian.org/DebugPackage  of course it doesn't just work.

**Comment by tfoote** [comment]
Ok, i've gotten it working in my fork.  To do this correctly we should see if we can get cmake/catkin to produce the install files.  http://manpages.ubuntu.com/manpages/natty/man1/dh_install.1.html

**Comment by tfoote** [comment]
Ticket for old style info at https://code.ros.org/trac/ros/ticket/3365

**Comment by tfoote** [comment]
Moved to ros-infrastructure/bloom#32

**Comment by po1** [comment]
Any progress on this?
There was a discussion some time ago about adding semantic versioning and a more debian-y way to make ROS debians.
To me, this also calls for spliting debians, at least into separate a `-dev` package and a binary lib package. The former with only the API version, the latter with the ABI version in the SONAME.
Are there any plans to split a ROS package `foo` into any subset of the following?
- `ros-distro-foo` : the nodes, scripts, config & launch files
- `ros-distro-libfoo1` : shared libs, messages and services
- `ros-distro-libfoo-dev` : headers
- `ros-distro-python-foo` : python libs
- `ros-distro-foo-dbg` : debug symbols for the nodes
- `ros-distro-libfoo1-dbg` : debug symbols for the shared libs
- `ros-distro-libfoo-doc` : documentation for the libs, msgs & srvs
- `ros-distro-foo-doc` : documentation for the nodes, scripts, config & launch files

If there is any ongoing work towards this, I'd be willing to contribute.

This is mostly relevant for ros-infrastructure/bloom#32, but will likely affect catkin too.

**Comment by dirk-thomas** [comment]
As you can see in the previous comment this ticket had been moved to bloom as it is related to packaging only. That ticket is marked with the milestone "untargeted" which implies that nobody is actively working on it and none of the maintainers is planning to spend time on this ticket.

If you would like to contribute to this feature that would be more then welcome but it would likely require a very significant amount of work to get all involved parts implemented.

**Comment by tfoote** [comment]
Stripping the debug flags is probably on the dooable side. I have a branch I played with this 2 years ago. https://github.com/tfoote/catkin/tree/fix_issue_20 It is way out of date, and as the above ticket mentions its implementation would want to mostly move to bloom. 

The other splits are much harder because the differentiation is more semantic and we would need to allow/require the maintainer/developer to list where all targets go.

**Comment by wjwwood** [comment]
> ...we would need to allow/require the maintainer/developer to list where all targets go.

And dependencies.
