### ISSUE TITLE
bat files still generated on linux

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#205]
I think these were there for debugging.

**Comment by dirk-thomas** [comment]
This applied only to environment hooks. Currently there is no way to determine which file extension is specific to a platform.

I would suggest that this can/should not be fixed in catkin but each invocation of catkin_add_env_hooks() should call it with the platform specific arguments

**Comment by dirk-thomas** [comment]
All package of base ros now install only platform specific env hooks.
