### ISSUE TITLE
Consistent names for folder spaces

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#208]
the current catkin layout is:
build/
- buildspace
  -- .CATKIN_WORKSPACE
  /opt/ros/groovy/
- .CATKIN_WORKSPACE

The words 'buildspace' and workspace are chosen badly in my opinion, here.
Firt, the whole 'build' folder is commonly considered the build space, so calling a sub folder of it buildspace does not make too much sense to a novice user.

Also, the workspace is commonly the folder containing all sources, or both sources and build space, so
.CATKIN_WORKSPACE is confusing as well, as a name (and contradicts catkin_init_workspace).

My humble suggestion is something like 'runspace', or 'installspace', 

Consistent terminology makes writing and reading docs (and sourcecode) and support for problems easier.

**Comment by dirk-thomas** [comment]
I do see that the current terminology is not great. Please post a complete list of folders, their current names and relation to each other on the catkin mailing list. Based on that we can find a better terminology.

**Comment by dirk-thomas** [comment]
REP 128 implemented in d328c8c8b0e81596424699d0d2e67a357deb886a and 03aaffc342431c5e61b34bbb0535a75f2576b31c
