### ISSUE TITLE
reshuffling of the docs for what belongs to the user/developer guide

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#215]
The following topics should definitely belong to the user guide :
- environment files
- variables
- code generation (and somewhere in there, the special target ${PROJECT_NAME}_gencpp should be mentioned. Maybe dynamic_reconfigure should be part of that too with the *_gencfg)
- extracted CMake API reference (part of it at least)

"how to build the docs" should maybe belong to the developer guide ?

Installation and build parameters in the developer guide also contain the global TOC tree which is confusing.

Just shuffling. Pretty good otherwise, good job guys !

**Comment by tkruse** [comment]
In my head, the section "user guide" translates to "what the most
inexperienced user I can imagine needs to know to create their first
workspace and package", and dev guide to "Everything else". I understand
that the labels I chose may not be philosophically sound.

So maybe the dev guide could also be labelled as "advanced users guide" and
the user guide to "catkin introduction" or something.
In general I would like to keep the split. As an example, in environment
files, it says:

"That `env.sh` executes a subshell means that your shell
   initialization files will be read `after` the environment
   is set by catkin's env hooks; this means that what these
   files want to do may get clobbered."

The most inexperienced user I can imagine will not understand any of it,
and get scared and frustrated. That's to be avoided.

For variables the same, though we need a section explaining more how to
write a CMakeLists.txt and how to use those variables, as a copy&paste
guide for the most inexperienced user imaginable.

I hope my point of view is convincing, I only care about the split, I am
dispassionate about the labels. I want inexprienced users to see at a
glance in the structure what they need to know, and what not.
So if you suggest better labels to the two (or maybe three) large sections
to justify the split, I will happily make it so.

**Comment by vrabaud** [comment]
ok, I guess the following would be appropriate then no ?
- user guide
- advanced user guide
- developer guide

No user (experienced or not) will ever care about the following so they should be independent I believe :
Design sketch
Pre- and Post-installation Disk Layout reference (not sure about this one)
Catkin Maintainers guide
Upload catkin documentation
Indices and tables
How to build the docs (not sure about this one)

**Comment by tkruse** [comment]
Fair enough, did so and pushed to groovy_doc pull request
https://github.com/ros/catkin/pull/216
