### ISSUE TITLE
Add macro for python libraries compiled from C/C++

### ISSUE THREAD

**Issue by hershwg** [ros/catkin#218]
Sometimes Python libraries are created by compiling C or C++ code and creating python bindings for them.  For python programs to find those libraries, they need to be in a directory in the $PYTHONPATH environment variable.  Thus far, all compiled libraries end up in /opt/ros/groovy/lib or similar, which is not in the $PYTHONPATH.

Geometry/tf has this issue.  In the latest version of geometry/tf (this rev: https://kforge.ros.org/geometry/geometry/rev/9756623dcf4e ) I wrote some custom cmake stuff to install the library to ${CMAKE_INSTALL_PREFIX}/${PYTHON_INSTALL_DIR}/tf, and to compile the library into a place in build space where python would find it: 

set_target_properties(pytf_py LIBRARY_OUTPUT_DIRECTORY ${CATKIN_BUILD_PREFIX}/${PYTHON_INSTALL_DIR}/tf)

So, since this will happen from time to time (rqt, rviz at least), it seemed like it might be useful to have a catkin macro that would declare that a given compiled library was needed by python.

**Comment by dirk-thomas** [comment]
Why does this require a catkin-specific macro/function if there is a one-line CMake command as you mentioned it:
set_target_properties(target PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CATKIN_BUILD_PREFIX}/${CATKIN_PACKAGE_PYTHON_DESTINATION})

**Comment by tfoote** [comment]
We could also just document it well.  We filed this ticket because it took
Dave and me quite a while to find this invocation to make it work.

**Comment by dirk-thomas** [comment]
Has been documented at http://ros.org/wiki/catkin/CMakeLists.txt
