### ISSUE TITLE
generated manifest.xml not backward compatible

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#219]
E.g., pcl_ros does have a dependency on PCL:
https://github.com/ros-perception/perception_pcl/blob/master/pcl_ros/CMakeLists.txt

But when using it from a dry package, PCL is not found:
http://jenkins.willowgarage.com:8080/job/ros-groovy-calibration_binarydeb_precise_amd64/132/console

That is because the manifest.xml has no mention of PCL (which installs its headers in a subfolder of include and that's why this issue only pops up with PCL):
<package>
  <description brief="pcl_ros">
    Generated manifest for package "pcl_ros" to pass compiler and linker flags to rosbuild packages.
  </description>

  <export>
    <cpp cflags="`pkg-config --cflags pcl_ros`" lflags="`pkg-config --libs pcl_ros`"/>

  </export>
</package>

Then again, maybe that whole issue is due to the fact that the meta-package (perception_pcl in this case) does not install a manifest.xml

**Comment by dirk-thomas** [comment]
The described problem has nothing to do with manifest.xml or metapackages.

The header from PCL is installed under PREFIX/include/pcl-1.6/pcl/point_types.h.
The failing code includes pcl/point_types.h.
Catkin currenly only adds PREFIX/include to the include path.

I am not yet sure how the CMake code for PCL and catkin would need to be modified to support that weird scenario because it requires build and install space to have different include paths.

**Comment by vrabaud** [comment]
ok, but PCL is in the DEPENDS of pcl_ros so its INCLUDE_DIRS should be added to the pcl_ros INCLUDE_DIRS right ?

This is not happening. Should it ? or should we just stick to adding  PREFIX/include as you mention ?

**Comment by dirk-thomas** [comment]
Yes and no. Catkin makes some decisions on that which are non-obvious. Anything you specify as INCLUDE_DIRS will be passed to depending packages find_package()-ing another package (which usually passes that variable to include_directories() ). This is used to be able to include from various location in source- and buildspace.

But this is not true for installspace. There catkin assumes that all of these headers have been installed from the various folders to one single standard location (${CMAKE_INSTALL_PREFIX}/include) which is then returned as INCLUDE_DIRS.

This usually makes sense - the usage in PCL is a bit different. The question is if that is a valid use case and catkin should support it or if PCL should do the versioned includes somehow different.

**Comment by wjwwood** [comment]
Just FYI this is blocking calibration also:

/tmp/buildd/ros-groovy-calibration-0.9.5/debian/ros-groovy-calibration/opt/ros/groovy/stacks/calibration/image_cb_detector/src/rgbd_cb_detector_action.cpp:48:29:
fatal error: pcl/point_types.h: No such file or directory
  compilation terminated.

## 

On Sun, Oct 14, 2012 at 12:12 AM, Dirk Thomas notifications@github.comwrote:

> Yes and no. Catkin makes some decisions on that which are non-obvious.
> Anything you specify as INCLUDE_DIRS will be passed to depending packages
> find_package()-ing another package (which usually passes that variable to
> include_directories() ). This is used to be able to include from various
> location in source- and buildspace.
> 
> But this is not true for installspace. There catkin assumes that all of
> these headers have been installed from the various folders to one single
> standard location (${CMAKE_INSTALL_PREFIX}/include) which is then returned
> as INCLUDE_DIRS.
> 
> This usually makes sense - the usage in PCL is a bit different. The
> question is if that is a valid use case and catkin should support it or if
> PCL should do the versioned includes somehow different.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/catkin/issues/219#issuecomment-9416887.

## 

William Woodall
Willow Garage - Software Engineer
wwoodall@willowgarage.com

**Comment by dirk-thomas** [comment]
We talked about that special case today. PCL should provide custom pclConfig.cmake and pcl.pc files to return these custom include directories. That seems to be the cleanest solution.

While catkin currently allows to override the find_package() template it does not provide that ability for the pkgconfig template. This should be added soon to enable a custom .pc file for that use case.

**Comment by dirk-thomas** [comment]
PCL should provide it's own find_package() implementation overriding the catkin template by providing a ${pcl_EXTRAS_DIR}/pclConfig.cmake.in file. From there it can provide custom (non FHS compliant INCLUDE DIRS).
