### ISSUE TITLE
catkin version missing, catkin_stack not properly deprecated

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#223]
Since we have very different catkin versions now, all catkinized packages should declare a catkin version dependency in CMakeLists.txt, e.g.:
find_package(catkin 0.5 REQUIRED)
(Should I raise an issue for each package?)

What catkin versions should be used with what distro (or catkin ABI?) should be documented.

Also it would be useful if catkin_fuerte was extended to have a catkin_package() macro that gives an error message to the user that catkin_groovy is required, and the same for catkin_stack vice versa.

The error message
Unknown CMake command "catkin_package".
is not acceptable, even if all catkin developers understand what it means.

**Comment by dirk-thomas** [comment]
We should not depend on a specific catkin version. Could you please describe why that is necessary/beneficial?
What happens if we make slight changes to catkin in the future - do you expect to update ALL existing packages?

Adding back-/forward compatible functions with better error messages is an option though.

**Comment by tkruse** [comment]
I would hope that when we make slight changes that do not require changes
to CMakelists we only change the minor version number, and if we make API
breaking changes (like from fuerte to groovy), we change the major version
number.
Any package should declare what major "API" version it assumes, so that it
fails early and does not generate more mysterious error messages due to API
breaking changes.

Unless I am mistaken
find_package(catkin 0.5 REQUIRED)
works with version 0.5.0 to 0.5.xxx

If the catkin API changes in a way that requires us to change all packages
anyway (such as from fuerte to groovy), I would expect to change the
version in find_package accordingly in all packages.

A user checking out package foo from some repository into his workspace
should get an early warning that the sources require a different version of
catkin than what he has, if there is no API compatibility.

What number of the API we use for what version is up to you, maybe groovy
should be 1.0.0 instead of 0.5.

Currently catkin sources that were created for fuerte fail with
catkin_groovy and vice versa, and the error message is usually not
something that a novice user will understand.

**Comment by dirk-thomas** [comment]
I am not convinced that introducing another level (beside the multiple ways we already have in place) for specifying versioned dependencies is a good idea. And I do not see that as a priority right now.

**Comment by tkruse** [comment]
If it works, I would be even happier with declaring the versioned
dependency in the package.xml. Then still all packages need to declare that
in their package.xml.

All I am saying is that before groovy gets released, we should make sure
that users trying to build fuerte sources with groovy catkin get a useful
error message, and vice versa. If for now it is easier to only create

macro(catkin_stack)
  message(FATAL "catkin_stack not supported by catkin anymore")
endmacro()

and

macro(catkin_package)
  message(FATAL "catkin_package requires at least groovy release of catkin")
endmacro()

in the respective catkin branches, that is just as well with me.
