### ISSUE TITLE
use CMAKE_SOURCE_DIR consistently in toplevel.cmake

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#225]
I believe CMAKE_SOURCE_DIR should be used also for the lines below. Not sure whether this can ever fail, though.
-  include(catkin/cmake/all.cmake NO_POLICY_SCOPE)
-  add_subdirectory(catkin)
-  include(${CMAKE_SOURCE_DIR}/catkin/cmake/all.cmake NO_POLICY_SCOPE)
-  add_subdirectory(${CMAKE_SOURCE_DIR}/catkin)

**Comment by dirk-thomas** [comment]
Do you have a case where the current code (without the CMAKE_SOURCE_DIR) does not work?

**Comment by tkruse** [comment]
Maybe if somebody changed the var in workspace.cmake to point at a catkin
installation. Don't know a case where this would be useful, but maybe the
case exists.

**Comment by dirk-thomas** [comment]
Both functions include the file/folder specified as a parameter relatively to the CMAKE_SOURCE_DIR.
So without a scenario where this is actually wrong (I can currently not imagine any) I would keep it as it is for the advantage of shorter and better readable code.

**Comment by tkruse** [comment]
The toplevel.cmake looks like this for me:

include(workspace.cmake OPTIONAL)

set(CATKIN_TOPLEVEL TRUE)

# include catkin directly or via find_package()

if(EXISTS "${CMAKE_SOURCE_DIR}/catkin/cmake/all.cmake" AND EXISTS
"${CMAKE_SOURCE_DIR}/catkin/CMakeLists.txt")
  set(catkin_EXTRAS_DIR "${CMAKE_SOURCE_DIR}/catkin/cmake")
  # include all.cmake without add_subdirectory to let it operate in same
scope
  include(catkin/cmake/all.cmake NO_POLICY_SCOPE)
  add_subdirectory(catkin)

if, in workspace.cmake, somebody adds this line:

set(CMAKE_SOURCE_DIR /tmp/my_catkin)

with catkin lying there, then the if statement suceeds, but the include
statement fails.

Another way to make this consistent is by removing all mentioning of
CMAKE_SOURCE_DIR there (also making that part shorter and more readable,
working without failure).

Mixing first CMAKE_SOURCE_DIR in a less readble form and later no
CMAKE_SOURCE_DIR to be more readable seems inconsistent to me.

**Comment by dirk-thomas** [comment]
Indeed. But setting CMAKE_SOURCE_DIR is asking for trouble - no sane code (which is not fully isolated) should do things like that. Same problems would arise if variables like CMAKE_CURRENT_SOURCE_DIR are modified.

Removing CMAKE_SOURCE_DIR is not possible since EXISTS requires an absolute path.
