### ISSUE TITLE
source reminder

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#226]
Could be good for rosbuild users to add something to toplevel.cmake or catkin_workspace.cmake like:

message(STATUS "+++ !!")
message(STATUS "+++ !! Remember to source ${CATKIN_BUILD_PREFIX}/setup.sh !!")
message(STATUS "+++ !!")

**Comment by dirk-thomas** [comment]
The use of this message at the end of the CMake invocation is pretty limited as it is usually lost in the amount of make output generated afterwards. Documentation seems to be the better way to deal with it.
