### ISSUE TITLE
catkin_migrate_package

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#227]
Just an idea: How about helping with migration by having a small script that transforms the manifest.xml into a package.xml, and hacks a CMakeLists.txt? I have not migrated so far, so i cannot tell how frustrating it is or not.

**Comment by tfoote** [comment]
@ijt has been working on this

**Comment by jbohren** [comment]
I have migrated joystick_drivers (with help) and there were definitely some "gotchas" even when using the scripts that @ijt wrote.

**Comment by dirk-thomas** [comment]
New repository is dealing with this topic: https://github.com/ros-infrastructure/catkinize
