### ISSUE TITLE
PROJECT_SHARE_INSTALL_PREFIX is not accessible from outside the catkin_project function

### ISSUE THREAD

**Issue by meyerj** [ros/catkin#228]
According to http://ros.org/doc/fuerte/api/catkin/html/variables.html#PROJECT_SHARE_INSTALL_PREFIX the PROJECT_SHARE_INSTALL_PREFIX variable can be used in install() macros as the installed location of the package. But as catkin_project() is a cmake function, it is not accessible from the outside. Although this variable is replaced by CATKIN_PACKAGE_SHARE_DESTINATION in groovy, either the catkin_project() function or the documentation should be fixed for the fuerte release, too.

**Comment by dirk-thomas** [comment]
Since using catkin in Fuerte is not recommended this will not be fixed. In Groovy this has been solved.
