### ISSUE TITLE
.rosinstall file needs ros definitions for backwards compatability

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#229]
rosinstall generating a dry overlay on wet installation crashes if it cannot find a ros element to be able to set ROS_ROOT.   It used to have autogenerated rules how to find ros.  Diff is below:

```
--- /opt/ros/fuerte/.rosinstall 2012-09-08 09:19:16.000000000 -0700
+++ /opt/ros/groovy/.rosinstall 2012-10-11 23:39:51.000000000 -0700
@@ -1,9 +1,2 @@
-- other:
-    local-name: /opt/ros/fuerte/share/ros
-- other:
-    local-name: /opt/ros/fuerte/share
-- other:
-    local-name: /opt/ros/fuerte/stacks
 - setup-file:
-    local-name: /opt/ros/fuerte/setup.sh
-
+    local-name: /opt/ros/groovy/setup.sh
```

ROS_ROOT is currently exported in 10.ros.sh  added by ros.  How can we fix this so that rosinstall can find the ROS_ROOT.  rosinstall itself could test if each setupfile elements sets ROS_ROOT and pass if it is set by the script?
Something like this

```
$ bash -c ". /opt/ros/groovy/setup.sh && env | grep ROS_ROOT"
ROS_ROOT=/opt/ros/groovy/share/ros
```

This would require a popen with an empty env, but I think that should work.

**Comment by dirk-thomas** [comment]
the performed command should be:
`$ /opt/ros/groovy/env.sh env | grep ROS_ROOT`

Updated:
but that is not available in the .rosinstall file.

**Comment by dirk-thomas** [comment]
The described behavior sounds reasonable and should be implemented in rosinstall as described.
