### ISSUE TITLE
catkin-sphinx instructions bad path

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#230]
in builddocs.rst:
cp -a theme/ros-theme ~/sphinx
should be:
cp -a src/catkin-sphinx/theme/ros-theme ~/sphinx

On the other hand, maybe the whole rst should be replaced with a reference to catkin-sphinx README, where those instructions should be added.

**Comment by tfoote** [comment]
Isn't this unnecessary now that it's installable?

**Comment by tkruse** [comment]
Yes, it seems you are right.

**Comment by dirk-thomas** [comment]
This has already been fixed in bd4ebe9e8d5ea438c2b95fed00ae23d5308811e9
