### ISSUE TITLE
Documentation needed for potentially counter-intuitive <build_depend> vs <run_depend>

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#233]
I'm finding myself marking all dependencies as both `<build_depend>` and `<run_depend>`. What sort of things need to be in each category? A package like `genmesg`, for example I would only expect to be a build dependency, but catkin says this needs to be a run dependency, too.

**Comment by dirk-thomas** [comment]
The following Wiki page contains an explanation of the various dependency type and states example when the are necessary: http://ros.org/wiki/catkin/package.xml
