### ISSUE TITLE
cmake -DCATKIN_PREFIX_PATH fails with multiple arguments

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#241]
Maybe my invocation is wrong, but this works for me:

```
@ krulap : ~/catkin_overlay/build $ echo $CMAKE_PREFIX_PATH
/usr/wiss/kruset/groovy_underlay/build/buildspace:/usr/wiss/kruset/local/ubuntu-amd64/
 @ krulap : ~/catkin_overlay/build $ cmake ../src
...
```

While this does not:

```
$ cmake ../src -DCMAKE_PREFIX_PATH=/usr/wiss/kruset/groovy_underlay/build/buildspace:/usr/wiss/kruset/local/ubuntu-amd64/
CMake Error at CMakeLists.txt:40 (find_package):
  Could not find a configuration file for package catkin.
```

Using latest catkin from source. Giving only one path to  -DCMAKE_PREFIX_PATH works.

**Comment by dirk-thomas** [comment]
You are using cmake arguments wrongly. The correct invocation would be:
`cmake ../src -DCMAKE_PREFIX_PATH="/usr/wiss/kruset/groovy_underlay/build/buildspace;/usr/wiss/kruset/local/ubuntu-amd64/"`
