### ISSUE TITLE
rostest-extras.cmake string index problem

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#248]
Hi, while trying to build groovy on Natty from source, I get this error a lot

```
CMake Error at /home/thibault/groovy_underlay/build/buildspace/share/rostest/cmake/rostest-extras.cmake:37 (string):
   string end index: -1 is out of range 0 - 31
Call Stack (most recent call first):
  ros_comm/tools/rosbag/CMakeLists.txt:53 (add_rostest)
```

Maybe things are in flux a lot and this will be fixed tomorrow, but this still suggests the cmake code could be wrapped to produce a better error message such as:
"PROJECT_SOURCE_DIR not set" or so.

**Comment by dirk-thomas** [comment]
Can you post the lines in question of that CMake file and what the values of the variables are in that case?
Or a step-by-step description how you ran into that?

**Comment by dirk-thomas** [comment]
Anyway it might be good to move this issue to https://github.com/ros/ros_comm since this does not look like a catkin issue.

**Comment by tkruse** [comment]
https://code.ros.org/trac/ros/ticket/4061
