### ISSUE TITLE
catkin workspaces break rosws workspace binding

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#249]
Some part of the rosws convenience CLI is based on there being a ROS_WORKSPACE env variable defining the workspace source location.

That way,
rosws update navigation
can works from anywhere in the filesystem. 
ROS_WORKSPACE is set by setup.sh, which in the catkin case is not generated by rosws anymore. I wonder whether catkin could play nice with rosws and to set this variable to abspath(${CMAKE_SOURCE_DIR}), where CMAKE_SOURCE_DIR is whatever you invoke cmake with.

This should obviously not be set for installed setup.sh files.

This would not work across chained workspaces, but that's fine by me.

**Comment by tkruse** [comment]
Word to the wise: in the chaining case this should be set to the uppermost workspace's source folder.

**Comment by dirk-thomas** [comment]
At which step should that be the case?

The catkin_init_workspace script is currently stateless so I think that would not be a good location. But after invoking CMake and sourcing the setup.sh rosws can use the existing variables (CMAKE_PREFIX_PATH) and the .catkin marker files.

**Comment by tkruse** [comment]
I thought about using CMAKE_PREFIX_PATH and marker files, but this does not
work well for dry-on-wet.

And I hoped the ROS_WORKSPACE variable could be set in the generated
setup.sh in the devel space (not install space).

I can try to produce a pull request if that helps.

**Comment by dirk-thomas** [comment]
If catkin can generate the information into the setup.sh file than it should be equally possible to extract these information from the existing variable and files. I hesitate to introduce yet another variable for the same information.

**Comment by tkruse** [comment]
As far as I can see, currently with catkin I can get the buildspace using
CPP and marker file. However I cannot get whether this is a devel space or
an install space, and I cannot get where to look for the CMAKE_SOURCE_PATH.
If you can tell me how to get these two items of information from catkin, I
could try to use them.

But even then, the following use case is problematic:
source ~/rosbuild_fuerte_workspace/setup.sh # sets ROS_WORKSPACE
source groovy_ws/devel/setup.sh # sets CMAKE_PREFIX_PATH

for rosws, it is impossble to tell whether it should consider ROS_WORKSPACE
or CMAKE_PREFIX_PATH.

**Comment by dirk-thomas** [comment]
You can get the necessary information from the .catkin file in devel/install space as described in https://github.com/tfoote/rep/blob/workspaces/rep-0128.rst

The backward compatibility case is difficult but we should not have these variable around to solve that. rosws could just warn about that and either pick one or error out.

**Comment by tkruse** [comment]
Maybe I miss some detail about dry-on-wet. If the user sources a dry workspace that overlays a wet workspace, then this will mean e.g. rosrun or roslaunch will overlay rosbuild packages from the ROS_PACKAGE_PATH over catkin packages from the CMAKE_PREFIX_PATH? And if the user with the same shell now sources any wet setup.sh, does this delete the ROS_PACKAGE_PATH? If not, how does this prevent from dry packages still overlaying wet ones?

The other problem is that unless I am mistaken, the .catkin file may contain a list of source locations. So a user could invoke cmake like this: cmake "../src1;../src2;../src3". In that case, How should rosws decide which of those to act upo as "the workspace"?

**Comment by dirk-thomas** [comment]
Every time a wet setup.sh is sourced the catkin-specific variables are reset (prefixes added based on the CMAKE_PREFIX_PATH are rolled back) and other variables defined by environment hooks (i.e. ROS_PACKAGE_PATH) are overwritten.

It is only possible to pass a single path to CMake. What do you expect to happen when passing a list of source folders?

**Comment by tkruse** [comment]
Sorry, I must have been confused.
rep128 says:

 .catkin --Marking the folder as a development space (the file
contains a semicolon separated list of Source space paths)

So how can this file ever contain more than one path?

I do not know enough about the environment hooks. Can you point me to a
documentation or sourcefile as to how the ROS_PACKAGE_PATH is reset? Maybe
this could reset ROS_WORKSPACE as well.

**Comment by dirk-thomas** [comment]
catkin writes that file so that catkin_pkg is able to perform lookups. The content of the file is never passed directly to CMake.

**Comment by dirk-thomas** [comment]
It looks like this can be dealt with in rosws with the already available information. If not please reopen.
