### ISSUE TITLE
develspace foldername

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#250]
I notice catkin source now changed the foldername from buildspace to develspace.
The current REP128 draft however suggests 'devel', not 'develspace'.

**Comment by dirk-thomas** [comment]
The REP defines the name of the folder when it is a sibling of building. That will be the case when a tools like catkin_make will invoke cmake for the user and passes that CATKIN_DEVEL_SPACE parameter. By default catkin keeps the develspace inside of build to match vanilla cmake expectations.

**Comment by tkruse** [comment]
Is there a good reason to name the folders differently, one "devel" and the other "develspace"?
