### ISSUE TITLE
`catkin_package()` could be more explicit

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#258]
At first glance, it's not obvious what the `catkin_package()` CMake macro is doing. (I've asked a few people around my lab). I understand that it's use and behavior is documented, but could we change this to `catkin_declare_package()`? Would such language be appropriate? If not, why?

(also, I understand that this would be a change that wouldn't come in until after the groovy release)

**Comment by dirk-thomas** [comment]
It is called `catkin_package()` for a longer time now.
The proposed name `catkin_declare_package()` does not make the semantic more obvious without reading the documentation. Also is it similar to vanilla cmake `project()` which is not `declare_project()`.
So we will stick to the current naming.
