### ISSUE TITLE
There is no documentation for the "test_depend" package.xml tag

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#261]
`build_depend` and `run_depend` are documented here: http://ros.org/doc/groovy/api/catkin/html/user_guide/package.html?highlight=build_depend but there's no documentation for test_depend.

See search: http://ros.org/doc/groovy/api/catkin/html/search.html?q=test_depend

The ROS wiki mentions `test_depend` here: http://www.ros.org/wiki/catkin/package.xml

**Comment by dirk-thomas** [comment]
Described here: http://ros.org/wiki/catkin/package.xml
