### ISSUE TITLE
configure packages more isolated

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#265]
With catkin, global cmake variables in one package affect following projects. This leads to confusion and bad practices. I suggest that before the call to add_subdirectory() in catkin_workspace.cmake, catkin clears at least all variables it can safely assume to be undesired for the next packages.

The following snippet lists vars by name:

```
GET_CMAKE_PROPERTY(res VARIABLES)
foreach(var ${res})
  message(STATUS ${var})
endforeach()
```

Parsing this list for suffixes like _LIBRARY or _FOUND should give a good list of vars to unset before configuring the next package.

Another approach would be to use an env caching for cmake variables, meaning the state of all cmake variables before a project configuration is stored, and restored after the project configuration. This would be even cleaner but would break variables users intentionally wanted to be global (and could also break cmake). another approach would be to also store the changeset after each project configuration, and once all projects have been build, replay all changesets again.

**Comment by tkruse** [comment]
Note I don't know cmake enough to judge whether this would break the build process.
An alternative approach here would be to define a constraint that all shared vars set by a package should be set to the same value by all packages. So if that is not the case, catkin could fail with an error message saying that package fo wants shared variable X to be set to 1, while package bar wants it to be set to 2.

Note that doing so will also slow down catkin configuration process, since find_package will not be able to reuse the results from invocations in other projects. if that's undesired, just close this ticket.

**Comment by dirk-thomas** [comment]
If you want CMake isolation between packages use `catkin_build_isolated` which actually invokes CMake separately on each package.

Modifying the variable as described above is highly dangerous and very likely to cause tons of problems.
