### ISSUE TITLE
catkin failure when catkin_pkg is not found is very unexplicit

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#268]
ERROR Cannot find a module of catkin_pkg, make sure it is up to date and on the PYTHONPATH, see catkin install instructions: No module named catkin_pkg.package

Complaints a user reported to me:
"""
where are the install instructions?  and where do i get catkin_pkg?
The version of catkin_pkg that works with this version of catkin?
"""

Just a URL would be fine I guess. Thx.

**Comment by tkruse** [comment]
Install instructions are here:
http://ros.org/wiki/catkin
but not here:
http://ros.org/doc/groovy/api/catkin/html/index.html

We should add install instruction to the rst docs, not sure whether we really need help URL in this error. Finding install instruction in general should be something users can do using Google.
