### ISSUE TITLE
interrogate_setup_dot_py monkey_patches too much

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#270]
in interrogate_setup_dot_py.py:

```
  sys.modules['setuptools'] = dummy
  sys.modules['distutils.core'] = dummy
```

This causes the basic setuptools use case to break:
http://packages.python.org/distribute/setuptools.html#basic-use

```
from setuptools import setup, find_packages
setup(
    name = "HelloWorld",
    version = "0.1",
    packages = find_packages(),
)
```

because setuptools.find_package does not exist, then. Suggest only patching setuptool.setup and distutils.core.setup functions, instead of the whole module. I can create a pull request if so desired.

**Comment by tkruse** [comment]
Else documentation should be extended, and maybe the error message improved:

```
Traceback (most recent call last):
  File "/home/kruset/groovy_underlay/src/catkin/cmake/interrogate_setup_dot_py.py", line 167, in <module>
    main()
  File "/home/kruset/groovy_underlay/src/catkin/cmake/interrogate_setup_dot_py.py", line 163, in main
     exec(fh.read())
  File "<string>", line 7, in <module>
AttributeError: Dummy instance has no attribute 'find_packages'
```

**Comment by dirk-thomas** [comment]
Sure, a pull request for that would be great.
