### ISSUE TITLE
No longer builds under Windows

### ISSUE THREAD

**Issue by ghost** [ros/catkin#276]
Using the command 'cmake -G "Visual Studio 10"' no longer sucessfully builds under windows,  with the following error:

[code]
-- catkin 0.5.54
CMake Error at cmake/safe_execute_process.cmake:3 (foreach):
  Syntax error in cmake code at

```
C:/Downloads/catkin/cmake/safe_execute_process.cmake:3
```

  when parsing string

```
C:\Python27\lib\site-packages\em.pyc;--raw-errors;-F;C:/Downloads/catkin/catkin_generated/setup.develspace.context.py;-o;C:/Downloads/catkin/devel/setup.bat;C:/Downloads/catkin/cmake/em/setup.bat.em
```

  Invalid escape sequence \P
Call Stack (most recent call first):
  cmake/em_expand.cmake:23 (safe_execute_process)
  cmake/catkin_generate_environment.cmake:38 (em_expand)
  cmake/all.cmake:159 (catkin_generate_environment)
  CMakeLists.txt:8 (include)
[/code]

This is obviously to do with Windows paths using the opposite slash to more compliant operating systems. It's pretty clear this just requires a string replace similar to ('\', '\'), but I don't know anything about cmake so I'll leave it to somebody more apt to fix it :).

The Windows-fixes branch merged in to main ~3 months ago compiles successfully under the same environment if a workaround is desired by others in the same situation :)

**Comment by dirk-thomas** [comment]
Please recheck with catkin 0.5.56.

Besides: using the three month old version of catkin from the branch will not work since the current master has diverged from that significantly.
