### ISSUE TITLE
built executables are not easy to find

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#283]
In build space, there are 4 different possible paths for executable:
- the devel/bin folder for a generic compiled binary
- the devel/lib/package_name/ folder for a compiled binary
- any folder in the source folders if the user wants to (e.g. Python scripts)
- any folder in the build folders if the user chooses to

In install space, the last two should not happen but people can choose to install to a custom folder, why not.

Now, how do I make people find my binaries after they find_package me ? The most generic/flexible way to do so is to create variables for each executable, e.g. package_name_EXEC_NAME, and add those to an extras cmake file e.g.:
https://github.com/ros/gencpp/blob/master/cmake/gencpp-extras.cmake.em
(I believe this part is not well documented and not trivial for a novice user)

And I would agree that this is the way to go for custom folders (case 3 and 4). The bin folder (case 1) is on the path so people will always find my binaries.

Now, there is the last case that I think needs attention: the devel/lib/package_name/ (case 2). It seems really weird to me that most people would install their binaries using the variable ${CATKIN_PACKAGE_BIN_DESTINATION} but that this variable would be lost to them afterwards.

I propose that the variable package_name_BIN is defined whenever a package is find_packaged.
@[if DEVELSPACE]@
set(package_name_BIN @(CATKIN_DEVEL_PREFIX)/@(CATKIN_PACKAGE_BIN_DESTINATION)/)
@[else]@
set(package_name_BIN @(CMAKE_INSTALL_PREFIX)/@(CATKIN_PACKAGE_BIN_DESTINATION)/)
@[end if]@
This is how people are used to find execs in rosbuild, e.g.:
https://code.ros.org/svn/wg-ros-pkg/stacks/pr2_common/trunk/pr2_description/CMakeLists.txt
Look for:
 COMMAND ${convex_decomposition_PACKAGE_PATH}/convex_decomposition/bin/convex_decomposition

I understand this is worse than a package_name_EXEC_NAME variable, but it is easier for people to transition. If we decide that package_name_EXEC_NAME is the way to go, I'd like a macro:
catkin_define_executable_variable(exec, path_to_exec_in_build_space, path_to_exec_in_install_space)
that would define the package_name_EXEC variable variable in source/build accordingly.

**Comment by vrabaud** [comment]
and btw, I am waiting on a decision/standard on that so that I can fix pr2_common (which requires convex_decomposition but cannot find it as it got catkinized).

**Comment by dirk-thomas** [comment]
While an extra file is the cleanest way to do it I do see the reason to get this kind of information from a found catkin package. Instead of exposing specific directories (like lib/package_name) we can add variables which expose the base directories. Based on that and the already existing destination variable you can always construct the full path.

So for the generated cmake config file we will introduce pkgname_SOURCE_PREFIX, pkgname_DEVEL_PREFIX, pkgname_INSTALL_PREFIX (where either the first two are set or the last one).

To make the usage for the user easier there will also be a pkgname_PREFIX which points to either the devel or the install variable.

**Comment by vrabaud** [comment]
ok that will work. Anyway, executable that should be accessed from CMake are either a standard CMake tool and people developing them should make it easy to access through a variable, or an operation that should not belong to CMake but your variables give that flexibility. Thx.

**Comment by tkruse** [comment]
Can either of you document those variables in the catkin docs, preferrably
with some context of when to use them?
