### ISSUE TITLE
requirement for directories to have the same name as specified in stack.yaml : Catkin-Projectname

### ISSUE THREAD

**Issue by ethanrublee** [ros/catkin#29]
This seems to be arbitrary.

If my project is "ecto_opencv" and locally it exists in a directory named opencv, catkin can't handle it.  Seems like catkin shouldn't require the project name to be the same as the directory name.

Is there some good reason for this?

**Comment by vrabaud** [comment]
I cannot reproduce this bug locally, I guess it got fixed

**Comment by tfoote** [comment]
Sounds good.
