### ISSUE TITLE
catkin_make does not trigger re-configure when new packages are added

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#290]
To reproduce:

$ mkdir -p bug_ws/src
$ cd bug_ws
$ catkin_make
$ cd src
$ catkin_create_pkg beginner_tutorials std_msgs rospy roscpp
$ cd ..
$ catkin_make
$ ls build
catkin/  catkin_generated/  CATKIN_IGNORE  CMakeCache.txt  CMakeFiles/  cmake_install.cmake  gtest/  Makefile

the catkin_makecommand does not generate build artifacts  for project beginner-tutorials

**Comment by dirk-thomas** [comment]
A workaround for that is calling `catkin_make --force-cmake`.
