### ISSUE TITLE
genlisp can occur twice in workspace

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#292]
To reproduce, use a simple groovy underlay workspace with genlisp, and duplicate the package

```
$ cd src
$ mkdir foo
$ cp -r genlisp foo/
$ cd ../build
$ cmake ../src
```

should raise error duplicate package, does not for me. Note for other packages error is raised, not sure what causes this for genlisp.

**Comment by dirk-thomas** [comment]
First your steps to reproduce are incomplete: it is unclear where genlisp comes from and the source folder does not contain a CMakeLists.txt.

When  I use the following commands:

```
mkdir /tmp/issue292
cd /tmp/issue292
mkdir src
git clone https://github.com/ros/genlisp.git src/genlisp1
git clone https://github.com/ros/genlisp.git src/genlisp2
source /opt/ros/groovy/setup.bash
catkin_make
```

the result is as expected:

```
RuntimeError: Two packages found with the same name "genlisp":
- genlisp
- genlisp-second
```

**Comment by tkruse** [comment]
I confirm there is no problem for me when I do your steps. But still the problem occurs, I could reproduce it this time somewhat differently, using symlinks. i am not 100% sure whether the first time I tried was also using symlinks, since I tried to perform the instructions as I posted in the ticket, but i cannot be sure.

So I try to give a complete set of steps now, for which it just failed for me (by not raising an error)

```
mkdir genmsg_underlay
cd genmsg_underlay/
mkdir src
cd src
git clone https://github.com/ros/genmsg.git
git clone https://github.com/ros/catkin.git
git clone https://github.com/ros/genlisp.git
cd ..
src/catkin/bin/catkin_make
. devel/setup.bash 
cd ..
mkdir genmsg_overlay
cd genmsg_overlay/
mkdir src
cd src
ln -s ../../genmsg_underlay/src underlay
git clone https://github.com/ros/genlisp.git
cd ..
catkin_make
```

**Comment by dirk-thomas** [comment]
Your command sequence - my output:

```
Base path: /tmp/issue292/genmsg_overlay
Source space: /tmp/issue292/genmsg_overlay/src
Build space: /tmp/issue292/genmsg_overlay/build
Devel space: /tmp/issue292/genmsg_overlay/devel
Install space: /tmp/issue292/genmsg_overlay/install
Creating symlink "/tmp/issue292/genmsg_overlay/src/CMakeLists.txt" pointing to "/tmp/issue292/genmsg_underlay/src/catkin/cmake/toplevel.cmake"
Two packages found with the same name "genlisp":
- genlisp
- underlay/genlisp
```

With return code 1.

**Comment by tkruse** [comment]
You must think I am hallucinating by now.
I confirm my sequence of steps fails as expected when run in /tmp/issue92

But it they still succeed (which is an error) for me when run at ~
If this does not occur for you at ~, I have to give up, and assume my setup is somehow broken.

**Comment by dirk-thomas** [comment]
Executed in ~ works as expected for me, too.

I don't know what to suggest except check your environment:
- clean shell environment, nothing sourced before
- up-to-date versions of Debian packages, i.e. catkin_pkg 0.1.8-1
- Python using these up-to-date packages and nothing which overlays, i.e. from pip

**Comment by tkruse** [comment]
I'll debug the code and check the state where it should fail. But tomorrow.

**Comment by tkruse** [comment]
https://github.com/ros-infrastructure/catkin_pkg/issues/25
