### ISSUE TITLE
Should _setup_util.py remove /opt/ros/groovy/bin from PATH environment variable?

### ISSUE THREAD

**Issue by payneio** [ros/catkin#295]
It makes following the existing groovy ROS tutorial impossible since it asks us to run rospack after sourcing devel/setup.bash.

**Comment by tkruse** [comment]
Can you give a link to the tutorial that fails, and the error you get?

Sourcing the setup.sh of a catkin workspace may remove references to /opt/ros/groovy in the environment if the given workspace was created without those references.

So it is likely that you created your catkin workspaces without sourcing /opt/ros/groovy/setup.bash first. Catkin remembers that (this feature is called env caching). You should be able to fix that by going into the build folder of your catkin workspace, then sourcing /opt/ros/groovy/setup.bash, and then invoking cmake.

If you do it like that then sourcing devel/setup.bash should always add /opt/ros/groovy/bin to the PATH (unless you discovered a bug).

**Comment by tkruse** [comment]
Related:
http://answers.ros.org/question/51647/catkin-setupsh-overwrites-path-environment-variable/

**Comment by payneio** [comment]
The tutorial link is here: http://www.ros.org/wiki/ROS/Tutorials/InstallingandConfiguringROSEnvironment
Section 4 says to:

$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws
$ catkin_make
$ source devel/setup.bash

and then immediately says to go on to the ROS file system tutorial:
http://www.ros.org/wiki/ROS/Tutorials/NavigatingTheFilesystem

which uses rospack and rosstack.

Even if I delete the ~/catkin_ws/devel and ~/catkin_ws/build directories, source /opt/ros/groovy/setup.bash and then rerun catkin_make, the path is again not preserved.

**Comment by payneio** [comment]
Ahhh... I figured out what I was doing wrong. I had initially gone deeper into the documentation (as suggested) here:
http://www.ros.org/wiki/groovy/Installation/Overlays

The process it explains was causing my failure:

$ mkdir -p ~/catkin_ws/src
$ rosws init --catkin ~/catkin_ws/src /opt/ros/groovy
$ cd ~/catkin_ws
$ catkin_init_workspace
$ catkin_make
$ source ~/catkin_ws/devel/setup.bash

Even if I ensure /opt/ros/groovy/setup.bash was installed previously.

To get back on track in the tutorial, I deleted the ~/catkin_ws directory, re-sourced /opt/ros/groovy/setup.bash and just did the basic tutorial steps of:
$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws
$ catkin_make
$ source devel/setup.bash

**Comment by tkruse** [comment]
Thanks, the wiki page for overlays was outdated, sorry this went unnoticed. I changed the wiki page to point to the tutorials with the correct instructions.

Your new list of steps seem correct. I guess we can close this ticket.
