### ISSUE TITLE
Provide a way to conditionally run tests if gl is available

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#296]
https://code.ros.org/trac/ros/ticket/1844

use glxinfo or similar to check hudson build machines for GL capabilities before executing tests that require hardware graphics acceleration (ogre, gazebo).

**Comment by dirk-thomas** [comment]
Is far as I understand the feature request this should be solved in user land CMake code. The package can perform whatever check in CMake and only condtionally register the GL specific unit tests.
