### ISSUE TITLE
install lists of messages/servs/etc

### ISSUE THREAD

**Issue by straszheim** [ros/catkin#3]
so that custom generators can use installed messages via cmake variables.

**Comment by straszheim** [comment]
if i add a json serializer and want to generate messages for std_msgs and geometry_msgs.    each package installs a variable std_msgs_MESSAGES or something that my other package could use.

**Comment by gerkey** [comment]
Morten, is this resolved already?

**Comment by mkjaergaard** [comment]
Not resolved yet. And not really required yet until we want to add support for more exotic message generators.
I suggest we postpone it, to avoid tinkering unnecessarily with the genmsg cmake stuff for the fuerte release.

**Comment by kwc** [comment]
closing as we don't have a use case for it
