### ISSUE TITLE
Link flag error

### ISSUE THREAD

**Issue by hsu** [ros/catkin#300]
Some of the catkin added link flags in the package installed `.pc` files appears incorrect.  For example, `ros-groovy-console-bridge` installs:

`/opt/ros/groovy/lib/pkgconfig/console_bridge.pc`

which contains a line:

```
Libs: -L/opt/ros/groovy/lib -lconsole_bridge -l/usr/lib/libboost_thread-mt.so -lpthread
```

But the `libboost_thread_mt` link flag is wrong, it should be

```
Libs: -L/opt/ros/groovy/lib -lconsole_bridge /usr/lib/libboost_thread-mt.so -lpthread
```

The extra `-l` triggers a compile error:

```
Linking CXX shared library libgazebo_sdf_interface.so
/usr/bin/ld: cannot find -l/usr/lib/libboost_thread-mt.so
```

It seems `catkin_depends` might be adding the extra boost library link flags incorrectly?

**Comment by dirk-thomas** [comment]
Please provide a description what you do to reproduce the failure.

**Comment by hsu** [comment]
checkout [simulator_gazebo from trunk](https://code.ros.org/svn/ros-pkg/stacks/simulator_gazebo/trunk/), edit [gazebo/CMakelists.txt](https://code.ros.org/svn/ros-pkg/stacks/simulator_gazebo/trunk/), modify the line:

```
set(USE_HG false)
```

to

```
set(USE_HG true)
```

then

```
rosmake gazebo
```

this will checkout gazebo into `gazebo/build/gazebo-hg`.  When compile is finished, edit [gazebo/build/gazebo-hg/cmake/SearchForStuff.cmake](https://bitbucket.org/osrf/gazebo/src/d9edb000a87db61d30b85c7f14885be451dda876/cmake/SearchForStuff.cmake?at=deprecated_parser_sdf_1.2_support)  and modify [line 268](https://bitbucket.org/osrf/gazebo/src/d9edb000a87db61d30b85c7f14885be451dda876/cmake/SearchForStuff.cmake?at=deprecated_parser_sdf_1.2_support#cl-268), change `find_package` to `pkg_check_modules`:

```
pkg_check_modules(console_bridge console_bridge)
```

Next,

```
rm -rf gazebo/build/gazebo-hg/build
```

then, re-compile, and you should be able to see the error.

```
rosmake gazebo
```
