### ISSUE TITLE
package name used instead of generator name

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#303]
Not sure whether this is a catkin_issue or a message_generation issue.

For fun I renamed genlisp to genlisp2, meaning the folder, the <name> entry in package.xml and the entry in CMakeLists.txt. In package.xml, the generator entry was left as:

```
<message_generator>lisp</message_generator>
```

running catkin_make, I get this error:

```
CMake Error at /home/kruset/catkin_ws/build/beginner_tutorials2/cmake/beginner_tutorials-genmsg.cmake:64 (_generate_msg_lisp2):
  Unknown CMake command "_generate_msg_lisp2".
Call Stack (most recent call first):
  /opt/ros/groovy/share/genmsg/cmake/genmsg-extras.cmake:215 (include)
  beginner_tutorials2/CMakeLists.txt:26 (generate_messages)
```

So to reproduce, you also need some project that generates messages, obviously.

It seems from the error message that something bad is going on, as the command _generate_msg_lisp2 seems to have been generated somewhere, without reasonable cause.

**Comment by dirk-thomas** [comment]
This is obviously genmsg related as the stack trace indicates. genmsg calls a CMake macro `_generate_msg_` with the project name of the generator minus the `gen` prefix concatenated.

In a fresh workspace with genlisp renamed to genlisp2 and std_msgs it works fine for me. When you fill issues please always provide a sequence of commands which lets other people reproduce what you did. Without that your description has too many uncertainties. If still an issue please refill against genmsg.
