### ISSUE TITLE
Tags in package documentation

### ISSUE THREAD

**Issue by DIdro** [ros/catkin#305]
Hello!
I have a feature request to solve issue, that described there (http://answers.ros.org/question/51928/how-to-search-for-ros-packages/?comment=52006#comment-52006)

It seems to be a not bad idea to add a tag field to package manifest ? And then generate tag field on package's documentation page on ros.org site. It'd allowed user to use these tags to search for some specific category of packages.

Thank you

**Comment by tfoote** [comment]
There's free space in the exports section that this could be done.  

This was part of a short [review thread](https://groups.google.com/forum/#!msg/ros-sig-buildsystem/_jRvhXFfsVk/tnzbddnmogQJ).(only 69 replies)

But the thought was to keep the minimum number of required and named fields, but we left the exports section unstructured to allow for optional extensions.  

To make this happen I'd suggest an informational REP proposal for how to fill in standard tags that tools can then pickup and parse in a standard way.

**Comment by DIdro** [comment]
Sorry if my answer is offtopic, but I don't clearly understand what did you mean.

> To make this happen I'd suggest an informational REP proposal for how to fill in standard tags that tools can then pickup and parse in a standard way.
> Should I do something, that you called as "informational REP proposal", myself to help to solve these issue (with sorting ROS packages by topic)?
> Or did you mean that this enhancement could be in principle realize in future by committers?

**Comment by tfoote** [comment]
The package.xml format was defined in [REP 127](http://www.ros.org/reps/rep-0127.html) leaving unstructured space in the exports area for extensions.  

To add support for tagging we need a standard way to tag.  This should be written up and proposed in a new REP following the [REP review process](http://www.ros.org/reps/rep-0001.html) to allow for community feedback.  And after we have a REP we can implement support for it in the various tools.

**Comment by tkruse** [comment]
@didro: The concept here is that the catkin maintainers are already aware
of this idea of tags, but currently this idea is not considerd valuable or
important enough (compared to other features waiting to be implemented) to
spend time researching on how exactly to implement it best. So if anyone in
the ROS community feels more strongly about this feature, he or she can
speed up the decision process by working out a design specification,
justifying the value of the feature and why it should be implemented one
way or the other, compared to alternatives. You do not need to do all of
this by yourself, you can set up a very small draft and ask others for
help, but if nobody does this, the feature will not be implemented soon.

**Comment by dirk-thomas** [comment]
I will close this ticket since _catkin_ only implements the spec defined in a REP. If there is further interest in this feature please consider discussing it on the buildsystem mailing list (ros-sig-buildsystem@googlegroups.com) and/or proposing a REP.
