### ISSUE TITLE
native cmake support for isolated builds

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#307]
This is a suggestion/question. Could isolated builds maybe be supported natively by cmake as something like a -DCATKIN_ISOLATED option to cmake?

This would probably create a mess if users switched this option from on to off or the other way round, but still would provide a better abstraction of the building process.

**Comment by dirk-thomas** [comment]
I am not sure if I understand your suggestion correctly. Do you want to perform an isolated build with a single invocation of:

  cmake -DCATKIN_ISOLATED path/to/toplevel.cmake

By definition an isolated build must be separate CMake invocations for each project. Using CMake as a kind of scripting environment to call out to CMake for each project looks like a weird approach. Basically the toplevel CMake file would need to perform all the same logic currently done in catkin_make_isolated.

I don't see how that would be an advantage - I would consider that even counterintuitive for people who are familiar with CMake.

**Comment by tkruse** [comment]
Yes, that's what I meant. i am not too sure about advantages and
disadvantages yet. The main advantage i currently think of is having a
single real buildspace, just as for the non-isolated case. This would help
for any tools that rely on there being a single real build space.

It's weird, but catkin itself is also weird.

**Comment by dirk-thomas** [comment]
The one/first buildspace would not contain the same as a non-isolated build. It would be just a dummy triggering other cmake instance (basically what catkin_make_isolated currently does). I will keep this closed since there is neither a benefit nor a need for such a feature.
