### ISSUE TITLE
catkin_make_isolated fails build of qt_gui_cpp

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#308]
Not sure whether this is a catkin or qt bug, since the build vars are supplied by catkin. To reproduce:

```
mkdir qt_ws
cd qt_ws/
mkdir src
echo "- git: {local-name: catkin, uri: 'https://github.com/ros/catkin.git', version: 'groovy-devel'}
- tar: {local-name: python_qt_binding, uri: 'https://github.com/ros-gbp/python_qt_binding-release/archive/release/python_qt_binding/0.2.7.tar.gz',
    version: python_qt_binding-release-release-python_qt_binding-0.2.7}
- tar: {local-name: qt_gui_cpp, uri: 'https://github.com/ros-gbp/qt_gui_core-release/archive/release/qt_gui_cpp/0.2.9.tar.gz',
    version: qt_gui_core-release-release-qt_gui_cpp-0.2.9}" > src/.rosinstall
wstool update -t src -j3
src/catkin/bin/catkin_make_isolated
```

yields

```
CMake Error at src/qt_gui_cpp_shiboken/CMakeLists.txt:41 (include):
  include could not find load file:

    /tmp/qt_ws/install_isolated/share/python_qt_binding/cmake/shiboken_helper.cmake
```

note catkin_install_isolated is invoked without --install, yet dependency cmake file is searched for at .../install_isolated/

qt tar versions taken from todays
http://packages.ros.org/web/rosinstall/generate/raw/groovy/desktop-full

**Comment by dirk-thomas** [comment]
You are mixing a new catkin and an old python_qt_binding version. Either use catkin 0.5.58 or older or python_qt_binding 0.2.8 or the groovy-devel branch.

**Comment by tkruse** [comment]
I see. maybe it would be good to use cmake macros instead of cmake variables in general as API, so that if something is removed (like BUILDSPACE var), it can be properly deprecated with deprecation warnings.
