### ISSUE TITLE
configuration dependencies

### ISSUE THREAD

**Issue by ethanrublee** [ros/catkin#31]
If my project depends on A B and C catkin projects, need to auto find_package these in my config.cmake file.

Also, if i depend on boost or some other library, this must also be added to my config.cmake file.

**Comment by gerkey** [comment]
Also make sure the analogous thing happens in .pc files.

**Comment by gerkey** [comment]
Seems to be working.  E.g., `roscpp-config.cmake` contains:

```
foreach(dep cpp_common;rostime;rosconsole;roscpp_serialization;roscpp_traits;std_msgs;rosgraph_msgs;xmlrpcpp)
  if(NOT ${dep}_FOUND)
    find_package(${dep})
    list(APPEND roscpp_INCLUDE_DIRS ${${dep}_INCLUDE_DIRS})
    list(APPEND roscpp_LIBRARIES ${${dep}_LIBRARIES})
  endif()
endforeach()
```

And `roscpp.pc` contains:

```
Requires: cpp_common rostime rosconsole roscpp_serialization roscpp_traits std_msgs rosgraph_msgs xmlrpcpp
```

**Comment by gerkey** [comment]
And, for future reference, that information comes from the `DEPENDS` argument of the `catkin_project()` call.
