### ISSUE TITLE
404 Error 

### ISSUE THREAD

**Issue by atomicsunshine** [ros/catkin#312]
"https://raw.github.com/ros/catkin/master/rosinstalls/base.rosinstall" results in a 404 error.  This is required as per step 2 of "http://www.ros.org/wiki/groovy/Installation/OSX/MacPorts/Source"

**Comment by tkruse** [comment]
Changed the wiki entry to:
http://packages.ros.org/web/rosinstall/generate/raw/groovy/ros_comm

You can look at the source instructions for Ubuntu probably for many of the steps, but please continue to either report such errors or repair the wiki page yourself if you feel competent enough.
