### ISSUE TITLE
catkin environment ignores env hooks from parent workspaces

### ISSUE THREAD

**Issue by dirk-thomas** [ros/catkin#316]
When sourcing the setup.bash from a custom workspace catkin does not source the environment hooks from the parent workspaces present in the CMAKE_PREFIX_PATH.

As a workaround you need to source the setup.bash from all parent workspaces which provide env hooks - usually that is only /opt/ros/groovy - before sourcing the own workspace.

**Comment by aleeper** [comment]
The above workaround is not sufficient for me, I am also having to manually add the src directory for my catkin workspace to my ROS_PACKAGE_PATH.
