### ISSUE TITLE
catkin_make does not retrigger configure if new package is added to EMPTY workspace

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#321]
related to #290 , which has been fixed, but the problem still appears when starting with an empty workspace:

```
mkdir dup_ws
cd dup_ws
. /opt/ros/groovy/setup.bash 
mkdir src
catkin_make
cd src
catkin_create_pkg mypack message_generation rospy
cd ..
catkin_make
```

last invocation should recognize new project, does not for me.

**Comment by dirk-thomas** [comment]
Please post the version of catkin you are using. Works fine for me.

**Comment by tkruse** [comment]
this was using -- catkin 0.5.58, so I guess the fix of 290 had not been packaged yet. Sorry.

**Comment by dirk-thomas** [comment]
The feature was added in 0.5.59. By now 0.5.62 is in shadow-fixed.
