### ISSUE TITLE
catkin packages can find_package things that are not declared in package.xml

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#324]
In any CMakeLists, adding a line like

```
find_package(nav_msgs)
```

works, even if that dependency has not been declared in package.xml. This confuses users and makes the package.xml potentially invalid.

I suggest that after each package was configured by cmake, the packages used, as determined by cmake variables xyz_FOUND, are checked against package.xml.
I know that would be a lot of work and hacking, so I expect this ticket to get closed, really, but then at leastthis feature was mentioned and a reason was given why i has not been implemented. And maybe somebody will have a better idea of how to implement this.

**Comment by dirk-thomas** [comment]
This is a native CMake. The only custom code involved in this is the generated CMake config file of nav_msgs. But this code has no information about the context and can therefore not check anything like package.xml.

The feedback you desire would not be a lot of work to implement, it is conceptually not possible to realize.
