### ISSUE TITLE
catkin_make: basic tab auto-completion for make build targets

### ISSUE THREAD

**Issue by mirzashah** [ros/catkin#325]
catkin_make does not currently expose
-  the ability to see available make targets with tab completion
- the ability to make individual targets (including 'clean' and 'run_tests_*).

Without this feature, the user has to go into the 'build' folder and run 'make' from there. Non-power users should be able to run tests, clean their projects, and build individual targets without having to understand the buildspace.

**Comment by dirk-thomas** [comment]
Individual targets can already be passed to catkin_make. I refined the help text a bit to state target names explicitly.

**Comment by dirk-thomas** [comment]
Providing completion for bash for now. If someone would like to have tcsh/zsh please consider to provide a pull request.
