### ISSUE TITLE
catkin_make should invoke make with -j -lx rather than -jx

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#326]
See https://code.ros.org/trac/ros/ticket/2920 for rosmake discussion, I believe the same reasons still apply. Also holds for catkin_make_isolated.

**Comment by dirk-thomas** [comment]
`-jN -lN` is required. Without an N for -j it will spawn unlimited jobs in the beginning (since the load is zero) and therefore overshoot the desired maximum load average.
