### ISSUE TITLE
catkin_make_isolated does not output catkin version

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#331]
catkin_make does by default.
That would help for debugging user problems.

also catkin_make_isolated should get --version option

**Comment by dirk-thomas** [comment]
-1 on adding a command line argument like `--version``.
I would propose that catkin_make_isolated should be default print the CMake and make output (as it does with --verbose). Instead there could be an option`--quiet` which hides the output (as long as there is no error) as it is currently done by default.

**Comment by wjwwood** [comment]
To be clear, CMake outputs the catkin version not `catkin_make`.

I would be fine with either defaulting to verbose output (so you can see the CMake output for each package which contains the catkin version) or having `catkin_make_isolated` output the version explicitly.  Either way there should be an easy way of detecting the catkin version without invoking CMake, so maybe we should set that up.
