### ISSUE TITLE
Avoid duplicate configuration overhead in default catkin build

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#333]
Most catkin_packages are find_packaged  multiple times within a given workspace. This means the same steps are often duplicated, and to me it seems this happens unnecessarily.

I looked into catkin/cmake/template/pkgConfig.cmake.in, and found

```
if(@PROJECT_NAME@_CONFIG_INCLUDED)
  return()
endif()
set(@PROJECT_NAME@_CONFIG_INCLUDED TRUE)
```

This however only ever has effect if the same cmake project attempts to find_package that catkin package more than once. For two different catkin packages the variable @PROJECT_NAME@_CONFIG_INCLUDED is in a different scope. I wonder whether catkin could benefit from using a more global scope, such as by adding the PARENT_SCOPE option (I think that means two invocations of set, one for the parent scope, one for the current). Not sure whether this would be bad cmake practice.

To get this to work for a small workspace, I also had to modify genmsg a bit to set vars in the PARENT_SCOPE and current scope.

**Comment by tkruse** [comment]
Actually even my small workspace example does not work well. The main problem being that genmsg-extras.cmake is written to be reconfigured for each find_package invocation (local variable scope), and so may other -extras.cmake files. So maybe the whole ticket is rubbish and we just have to live with the same variables having to be set again and again to the same values for each project.

**Comment by dirk-thomas** [comment]
All variables set by find_package() are in the local scope so it must be invoked for each project in its own scope. And again: you can anyway not assume that there is a parent scope.
