### ISSUE TITLE
location of executables in devel space

### ISSUE THREAD

**Issue by mkjaergaard** [ros/catkin#337]
When building executables catkin by default puts them in /devel/lib/pkg_name instead of /devel/bin/pkg_name

The location is set in catkin/cmake/catkin_destinations.cmake(46)

``` cmake
set(CATKIN_PACKAGE_BIN_DESTINATION ${CATKIN_GLOBAL_LIBEXEC_DESTINATION}/${PROJECT_NAME})
```

change to:?

``` cmake
set(CATKIN_PACKAGE_BIN_DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION}/${PROJECT_NAME})
```

**Comment by dirk-thomas** [comment]
The current location complies with FHS while you proposed location does not.
