### ISSUE TITLE
setup.zsh adds wrong path to PATH environment

### ISSUE THREAD

**Issue by jkammerl** [ros/catkin#338]
After sourcing setup.zsh (I am using zsh), /opt/ros/groovy is added to the PATH environment. 

PATH=/opt/ros/groovy:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/kammerl/bin

However, in order to include groovy binaries, PATH should contain this:
PATH=/opt/ros/groovy/bin

This is my catkin installation from ros-shadow-fixed:

ii  python-catkin-pkg                           0.1.9-1                                             catkin package library
ii  python-catkin-sphinx                        0.2.1-1                                             ROS package library
ii  ros-groovy-catkin                           0.5.63-0precise-20130125-0320-+0000                 Low-level build system macros and infrastructure for ROS.

**Comment by dirk-thomas** [comment]
One of the temp variable in setup.sh ($path) collides even if it is lower case.
