### ISSUE TITLE
catkin_make_isolated does not produce setup.bash etc.

### ISSUE THREAD

**Issue by piyushk** [ros/catkin#339]
The [rosbuild + catkin workspace tutorial](http://www.ros.org/wiki/catkin/Tutorials/using_rosbuild_with_catkin) does not work if you are using catkin_make_isolated instead of catkin_make.

No setup.bash (etc.) files are produced in devel_isolated that can be used as the setup-file for the rosbuild workspace (or source directly from bashrc for that matter)

**Comment by piyushk** [comment]
Here's the answers.ros thread for a bit more context: http://answers.ros.org/question/52756/issues-creating-a-rosbuild-overlay-on-top-of-catkin-packages/

**Comment by tkruse** [comment]
I think this is a duplicate of #327

**Comment by tkruse** [comment]
Actually I think this is a valid issue, the isolated devel space could really produce a .rosinstall file

```
- setup-file:
     local-name: /path/to/devel_isolated/setup.sh
```

Then a rosbuild overlay should be possible I think.

**Comment by tkruse** [comment]
Reopen and assign to William, please.
