### ISSUE TITLE
CATKIN_IGNORE for devel and install spaces

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#341]
Unless I am mistaken, catkin devel and install spaces should not be crawled for packages to be build. So in a workspace layout with packages at the workspace root, and devel and install spaces somewhere below workspace root as well, it would be best if devel and install spaces had a CATKIN_IGNORE marker file. Not sure whether catkin_pkg would thus also ignore entries in the CMAKE_PREFIX_PATH with this file. If so, maybe it should only ignore subfolders of the CPP with that file. Thoughts?

**Comment by dirk-thomas** [comment]
The build folder contains a CATKIN_IGNORE file as it should not be searched for package.xml files. The devel and install spaces must not contain such a file else at runtime no packages would be found.
