### ISSUE TITLE
catkin_make_isolated should set install prefix to installspace

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#344]
currently it is set to develspace, however the same effect can better be achieved by invoking

```
make install DESTDIR="/path/to/devel_isolated"
```

and pointing the CMAKE_INSTALL_PREFIx to install_isolated.

At the same time, if the user calls just make in the isolated build space, this will have no effect on the develspace. Ideally a hint could be placed into the buildspace telling the user what to do to get the code active in the develspace conveniently e.g. by the using command above. That command could go into a make wwrapper shell script in the buildspace, called make_devel.sh or something. Maybe that could even be invoked by catkin_make to make sure it works as it should.

**Comment by dirk-thomas** [comment]
This is not true. catkin_make_isolated always sets the install prefix to install_isolated. I Just confirmed that with the current version.

If you are referring to non-catkin packages (even if you don't mention that in the description) for these install prefix must point to devel space when invoked with installing. Pure CMake packages are installed to develspace when invoked without install and again installed to installspace when invoked with install.

**Comment by tkruse** [comment]
Yes, I am referring to non-catkin packages (I should have said, sorry), and I know those get installed to the develspace. And as I said, using install DESTDIR="/path/to/devel_isolated" has the same efect, but leaves the CMAKE_INSTALL_PREFIX untouched. So for non-catkin packages, there is no need to set CMAKE_INSTALL_PREFIX, as DESTDIR should be sufficient.

**Comment by dirk-thomas** [comment]
Why should be set DESTDIR instead of CMAKE_INSTALL_PREFIX?

**Comment by tkruse** [comment]
So that a user calling "make install" in the build folder gets the least surprising result.
