### ISSUE TITLE
setup.py support should support non-global scripts

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#345]
See: https://groups.google.com/d/topic/ros-sig-buildsystem/hsxeJocnKIQ/discussion

This setup invocation puts script foo into lib/foo/foo, making it rosrunnable in the installspace. It has no effect (other than a warning) in devel space, because currently cmake's setup.py support does not handle the data_files argument.

```
setup(
  version='0.0.1',
  # scripts=['scripts/foo'],
  data_files=[('lib/foo', ['scripts/foo'])],
  package_dir={'': 'src'})
```

The current recommendation for user could be extended:

```
d = generate_distutils_setup(
  packages=['mypkg'],
  scripts=['bin/myscript'],
  package_dir={'': 'src'}
)
```

Either by telling the users to use data_files for scripts (cumbersome for users, but clean), or using a virtual argument (catkin_scripts) that maps to data_files for convenience.

**Comment by dirk-thomas** [comment]
The warning for data_files has been disabled since it is not desired to copy any file from source to devel space. The package must be able to utilize the files from source (similar to rosrun which is able to run scripts from source).

Still data_files can and should be used to install resources.
