### ISSUE TITLE
catkin_make should create package targets

### ISSUE THREAD

**Issue by dornhege** [ros/catkin#346]
It would be nice if one could simply call `catkin_make my_package` to build a package (and its dependencies). cmake currently creates targets for subdirectories, but they don't build the targets defined in the package.

Naming might be an issue if a node is named the same as the package. Maybe "_package" could be appended to the target name.

Related answers.ros.org question:
http://answers.ros.org/question/54215/should-catkin_make-work-for-package-targets/

**Comment by dirk-thomas** [comment]
As far as I know CMake does not provide a mechanism to identify which targets a CMake project defines. So there is no way for catkin to generate/populate a package target.

**Comment by tkruse** [comment]
The custom target way goes like this (using example dependencies):

add_custom_target(foo_package
  DEPENDS foo_node foo_library foo_generate_messages_cpp)

**Comment by dirk-thomas** [comment]
How does that solve the problem?

**Comment by tkruse** [comment]
(Hm, I think a mail to github was lost, at least I don't see it in the web interface)
Users are free to declare a custom target xyz_package and use add_dependencies() to declare what other targets it shall depend on. This could become common or even recomended practice, but will need user maintenance.

This way, a develper can make HIS OWN package like that with one command, and any other package for which the maintainer has also followed that convention.

The catkin_package() macro could already create such a custom target that initially depends on nothing (and does nothing, except maybe raise a warning), that users could use with add_dependencies(), but I don't recommend this approach.

Else a technical way would be to introduce catkin_add_executable() macros and such, which automate this process. I guess this does not fit into the current catkin philosophy, but should be mentioned for completeness sake.

**Comment by dirk-thomas** [comment]
As discussed many times: catkin will not wrap standard commands like add_executable(). Also catkin will not define an empty target as this might conflict with user defined target.

Adding such a custom target to build all targets of a package is totally up the user. We might recommend that it the docs but the user must be aware that he can not rely on a package to behave like that,

**Comment by jbohren** [comment]
@dirk-thomas 

> As far as I know CMake does not provide a mechanism to identify which targets a CMake project defines. So there is no way for catkin to generate/populate a package target.

Why do we need to be able to identify which targets a CMake project defines? Won't each package be put into `ws/build/path/to/package` with the appropriate Makefile in there? Then you can just `cd ws/build/path/to/package && make` right?

**Comment by tkruse** [comment]
@jbohren only catkin-make_isolated does that. Default catkin uses a single buildspace and treats thw whole workspace as a single cmake project.

**Comment by jbohren** [comment]
@dirk-thomas I'm referring to the single buildspace...

**Comment by tkruse** [comment]
sorry, I never noticed, you could be right.

**Comment by jbohren** [comment]
Let me clarify:

If a package is in:

```
~/ws/src/repo_dir/pkg_xyz
```

And I run:

```
cd ~/ws
catkin_make
```

Then the following directory will be created:

```
~/ws/build/repo_dir/pkg_xyz
```

And then if I run:

```
cd ~/ws/build/repo_dir/pkg_xyz
make all
```

Then, it makes all of the targets in that package.

**Comment by dirk-thomas** [comment]
I was referring yo the requested feature "catkin_make should create package targets" which is not solvable because of my arguments.

Of course you could always invoke the specific makefile directly as you mentioned.

**Comment by jbohren** [comment]
@dirk-thomas 

> Of course you could always invoke the specific makefile directly as you mentioned.

Then could we have `catkin_make` invoke said specific makefile if you run `catkin_make pkg <<pkgname>>`?

**Comment by dirk-thomas** [comment]
Not if we also allow targets to be passed to catkin_make since the namespaces will collide.

**Comment by jbohren** [comment]
That's why I'm proposing a subcommand / argument to avoid collisions.

Why not `catkin_make -pkg <<pkgname>>`?

**Comment by jbohren** [comment]
Rather `--pkg`

**Comment by dirk-thomas** [comment]
Sound good - filled a separate issue as this diverges significantly from this issue: #348

**Comment by jbohren** [comment]
@dirk-thomas Cool, thanks!

**Comment by dornhege** [comment]
I like it. Serves the original intention!
