### ISSUE TITLE
catkin_vars to be defined in catkinConfig.cmake

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#347]
According to an answer in http://answers.ros.org/question/54173/install-destination-error-with-my-catkin-package

"catkin_package() defines the variable CATKIN_PACKAGE_BIN_DESTINATION"

Can't this be generated on find_package(catkin)?
I don't see what argument to catkin_package could change this variable.

**Comment by dirk-thomas** [comment]
Because it is valid to call:

```
find_package(catkin)
project(foo)
```

**Comment by tkruse** [comment]
Can we at least do this in catkinConfig.cmake, for all variables defined by catkin_package():

set(CATKIN_PACKAGE_BIN_DESTINATION "E;Error: CATKIN_PACKAGE_BIN_DESTINATION not set, invoke catkin_package(...) first")

The "E;" helps raising an error when using the variable (in the install macro). Error message then looks like this:
CMake Error at foo/CMakeLists.txt:73 (install):
  install PROGRAMS given unknown argument "Error:
  CATKIN_PACKAGE_BIN_DESTINATION not set, invoke catkin_package(...) first".

It is a bit of a hack, but I think this might help users.

**Comment by tkruse** [comment]
maybe within an if block that only sets this value as long as the var is unset.

**Comment by dirk-thomas** [comment]
This hack would fail if the variable is used in other context.

**Comment by tkruse** [comment]
ok
