### ISSUE TITLE
Question about catkin command-line tools

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#350]
Is there a reason why the catkin command-line tools like `catkin_make` and `catkin_make_isolated` (and others [here](https://github.com/ros/catkin/tree/groovy-devel/bin)) aren't built into a single "catkin" command with subcommands?

**Comment by dirk-thomas** [comment]
Because it is easier to maintain them as individual tools and there is not advantage on having a single command with subcommands which are partially doing very different stuff.

**Comment by jbohren** [comment]
Cool, thanks.
