### ISSUE TITLE
Basic .cmake files listed in CFG_EXTRAS arguments of catkin_package not installed in devel space

### ISSUE THREAD

**Issue by smits** [ros/catkin#353]
Hi,

Apparently the plain .cmake files listed in the CFG_EXTRAS arguments are not copied the the devel space (I did not check install space yet, but after looking at the code this looks ok).

I have a patch ready, will send ASAP

Ruben

**Comment by dirk-thomas** [comment]
Could you please describe why you think that should be performed?

In general there is no reason to copy any file from source to devel space. So imho this should not be done automatically.

**Comment by smits** [comment]
On Wed, Feb 6, 2013 at 9:16 PM, Dirk Thomas notifications@github.com wrote:

> Could you please describe why you think that should be performed?
> 
> In general there is no reason to copy any file from source to devel space. So imho this should not be done automatically.

From the documentation of the catkin_package cmake macro:

:param CFG_EXTRAS: a CMake file containing extra stuff that should

# be accessible to users of this package after

# `find_package`\ -ing it.  This file must live in the

# subdirectory `cmake` and must have the additional extension

# `.in` (since it is expanded using CMake's `configure_file()`).

# The template can distinguish between build- and installspace

# using the boolean variables `DEVELSPACE` and `INSTALLSPACE`

# and should be verified to work in both cases.

# :type CFG_EXTRAS: string

We are catkinizing the orocos_toolchain packages. These packages are
plain cmake builds so the process has been pretty easy.
But, ... the RTT package contains some cmake files that define cmake
macros needed packages like OCL that depend on RTT. If we want to
build these depending packages in the same catkin-build we need to get
these cmake macros into the cmake_prefix_path. Since the catkin devel
space is added to the cmake_prefix_path and the catkin_package
documentation describes that the CFG_EXTRAS option provides exactly
the functionality that we need I was really surprised that it would
not copy over plain cmake files.

So briefly, we need the functionality the CFG_EXTRAS parameter of the
CATKIN_PACKAGE cmake macro was designed for, but for plain cmake
files, not only .cmake.in files.

Best regards,

Ruben

**Comment by dirk-thomas** [comment]
The behavior you would like to achieve is already possible and it does not require the file to be copied to devel space. Please take a look to i.e. https://github.com/ros/class_loader how this is done.

I closed the related pull request (without merging it) but will keep this issue open until the documentation has been updated to reflect these different options
