### ISSUE TITLE
catkin_make older validation broken for certain layouts

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#361]
to reproduce, in any folder (using catkin 0.5.63):

```
$  catkin_make --source .
$ catkin_make --source .
The specified base path "/tmp/catkin_ws" contains a CMakeLists.txt but "catkin_make" must be invoked in the root of workspace.
```

This may be solved by the new marker-file design anyway. 

Also note that with that design, catkin is prone to find packages in the installspace.

There should at least be a warning if the user decides to put the installspace anywhere under the sourcespace (unless a CATKIN_IGNORE file protects installed packages from being found, e.g. by having catkin_ws/builds/CATKIN_IGNORE and catkin_ws/builds/installspace).

**Comment by tkruse** [comment]
based on http://answers.ros.org/question/55080/catkin_make-failing-with-custom-source-directory/#55109

**Comment by dirk-thomas** [comment]
Adding a CATKIN_IGNORE file in install space is not an option. Than tools like catkin_pkg would not find any packages anymore.

Instead catkin_make(_isolated) should exclude the install space from the search for packages.

**Comment by tkruse** [comment]
What I said was not putting CATKIN_IGNORE in the install space, but above the install space, yet under the sourcespace.

**Comment by dirk-thomas** [comment]
How should that look like when source space is in the root of the workspace and install space in a subfolder `install`?

**Comment by tkruse** [comment]
In that case it would not work, obviously. Ignoring the installspace is okay when there is just one installspace, but fails when a user has more than one installspace. Which is why users should be encouraged to use a location for installspaces that is safe from being found under the sourcespace, such as by having an intermediate folder with CATKIN_IGNORE. I like the ignoring as a solution for now, though.

**Comment by dirk-thomas** [comment]
We should not recommend to use intermediate folders and place CATKIN_IGNORE files in there. These tools are intended to simplify the commands for beginners. They should work out-of-the-box and make life easier when the user follows the default layout.

The latest patch lets cm and cmi ignore any subspace under source.
