### ISSUE TITLE
./src/catkin/bin/catkin_make does not work

### ISSUE THREAD

**Issue by kalectro** [ros/catkin#363]
This is the error I get when I try to execute catkin using the prebuilt bin

```
./src/catkin/bin/catkin_make --install
Base path: /home/frk1pal/temp
Source space: /home/frk1pal/temp/src
Build space: /home/frk1pal/temp/build
Devel space: /home/frk1pal/temp/devel
Install space: /home/frk1pal/temp/install
Creating symlink "/home/frk1pal/temp/src/CMakeLists.txt" pointing to "catkin/cmake/toplevel.cmake"
find_packages() got an unexpected keyword argument 'exclude_subspaces'
```

Building it with a previously installed source catkin
    catkin_make install
works, but if I source the new install folder and try to rebuild it, I get the same error

Kai

**Comment by dirk-thomas** [comment]
If you are using the latest version of catkin from source you must also use the latest version of catkin_pkg from source.
