### ISSUE TITLE
bond_core error while executing rosdep install

### ISSUE THREAD

**Issue by jfdupuis** [ros/catkin#364]
On OSX Lion running: rosdep install --from-paths src --ignore-src --rosdistro groovy -y

Result in: 
executing command [brew install ros/groovy/bond_core]
Error: No available formula for bond_core 
Please tap it and then try again: brew tap ros/groovy
ERROR: the following rosdeps failed to install
  homebrew: command [brew install ros/groovy/bond_core] failed

**Comment by wjwwood** [comment]
What version of ROS are you using?

**Comment by jfdupuis** [comment]
Groovy

**Comment by wjwwood** [comment]
So this occurs when `bond_core` is depended on by some package in your `src` directory, but `bond_core` is not in your `src` directory.  Because `bond_core` is not in your `src` folder, `rosdep` is trying to resolve it using Homebrew, but we do not have Homebrew formulae for ROS packages (yet).

The solution to this problem is to ensure that `bond_core` is in your workspace's `src` folder, perhaps it failed to fetch it when you were setting up the workspace? Did you use `wstool` to setup your workspace?  If so, what url did you use?

**Comment by jfdupuis** [comment]
I have been following the steps described here: http://ros.org/wiki/groovy/Installation/OSX/Homebrew/Source and used the wstool for a "Desktop Install" on a fresh install of OSX.

**Comment by wjwwood** [comment]
Looking at the output of `http://packages.ros.org/web/rosinstall/generate/raw/groovy/desktop`, `bond_core` is listed in the packages. Is a folder `bond_core` in your `src` directory?

If not then you might need to make sure your `src` is up-to-date:

```
$ wstool merge -t src http://packages.ros.org/web/rosinstall/generate/raw/groovy/desktop
$ wstool up -t src
```

**Comment by jfdupuis** [comment]
In src, there is a bond_core directory with only a package.xml file and nothing else. After executing the two suggested commands, the process went through. Not too sure what happened.

**Comment by wjwwood** [comment]
Ok, well that sounds right.

Can you make sure your `catkin_pkg` is up-to-date?

```
$ sudo pip install -U catkin_pkg
```

Then try it again.  I have not been able to reproduce this...

**Comment by jfdupuis** [comment]
This returned:
"Requirement already up-to-date: catkin-pkg in /Library/Python/2.7/site-packages"

The dependencies seems to be all resolved. Now, I run into compiling issue with pcl and turtlesim that I probably should address in their respective repositories.

**Comment by wjwwood** [comment]
Yeah, sounds like rerunning `wstool` solved it.

For pcl:

http://ros.org/wiki/groovy/Installation/OSX/Homebrew/Source#pcl_build_problems

For turtlesim:

https://github.com/ros/ros_tutorials/pull/6
