### ISSUE TITLE
[cmi] use templates for env.sh/setup.*sh from catkin

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#371]
Currently `catkin_make_isolated` generates a custom env.sh file for third party packages for the purpose of chaining environments. It should instead use catkin's templates so that the env.sh files are semantically and functionally the same.

The biggest problem with implementing this is that he env.sh template is currently setup as a CMake template, so generating it from pure python is possible but not convenient.

**Comment by dirk-thomas** [comment]
The configure_file expansion is simple to implement in Python:

```
from __future__ import print_function
import re
if __name__ == '__main__':
  with open('env.sh.in', 'r') as f:
    content = f.read()
    print(content)
    data = {
      'SETUP_DIR': 'setup_dir',
      'SETUP_FILENAME': 'setup_filename'
    }
    def repl(match):
      var = match.group(0)[1:-1]
      return data[var]
    output = re.sub('\@[a-zA-Z0-9_]+\@', repl, content)
    print(output)
```
