### ISSUE TITLE
Absolute paths in generated artefacts break when workspace moves

### ISSUE THREAD

**Issue by mjog** [ros/catkin#372]
It seems catkin writes absolute paths into generated artefacts in several places, notably in:
- `{/build/catkin_generated/installspace,devel}/.catkin`
- `{build,devel}/setup.{sh,bash,zsh}`

This breaks the build when moving or renaming the workspace directory, and is confusing to recover from since all subsequent invocations of any catkin_\* command fails.

**Comment by dirk-thomas** [comment]
A CMake build folder is never relocatable - this is a design choice of CMake. Therefore a catkin workspace containing the build folder can also not support this.
