### ISSUE TITLE
Enable catkin_make to use cmake's -C arg

### ISSUE THREAD

**Issue by stonier** [ros/catkin#376]
We use 'cmake -C <initial-cache>' to preload the cmake cache quite frequently when cross compiling (usually to load up platform specific variables). I'm sure others also have or will have cause to occasionally use cmake's -C arg.

catkin_make however overrides this arg ('-C' '--directory'). Could this short option tag be changed and have catkin_make drop -D, -G and -C options into the cmake_args?

**Comment by dirk-thomas** [comment]
Since cmake and make both have a `-C` option it would be very confusion if catkin_make would pass it to only one of the tools. But we can add options which get passed to CMake - either specifically `--cmake-C` or generically everything behind `--cmake`?

**Comment by stonier** [comment]
I like the latter option - everything behind `--cmake`.
