### ISSUE TITLE
Don't set NO_CMAKE_FIND_ROOT_PATH in find_xxx

### ISSUE THREAD

**Issue by herbrechtsmeier** [ros/catkin#379]
Don't set NO_CMAKE_FIND_ROOT_PATH in find_xxx functions to enable the cross compiler to set the system roots to the target system root and host system root. Additionally don't assume that the CMAKE_PREFIX_PATH contains absolute paths  (IS_DIRECTORY) as they are relative to a system root.

**Comment by herbrechtsmeier** [comment]
At the moment you have to set CMAKE_PREFIX_PATH to the absolute path (/path/to/machine/sysroot/path/to/ros;/path/to/native/sysroot/path/to/ros) but normally it should only contain the local prefix (/path/to/ros) and the system root paths (/path/to/machine/sysroot; /path/to/native/sysroot) are passed via CMAKE_FIND_ROOT_PATH. This allows the cross compiler framework to install cross compiled libraries and headers into the machine system root and binaries and scripts into the native system root. Additionally the cross compiler framework installs the CMake files into the correspondent system root.

**Comment by tfoote** [comment]
Can you point to docs that we can read more about the best practices?

**Comment by herbrechtsmeier** [comment]
At first you could take a look at the http://www.vtk.org/Wiki/CMake_Cross_Compiling but OpenEmbedded (Yocto) have simplify the usage of executables in the build process. They first build all buildtool_depends as native version and install them into a native sysroot. As next they cross compile all depends and install all header, libraries and CMake files into the cross sysroot. The native sysroot is append to the cross sysroot in the `CMAKE_FIND_ROOT_PATH` and `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` is set to `ONLY`. This allows the find_program function to find the native programs in the native sysroot. I will try to find a documentation about the OpenEmbedded internals.

**Comment by herbrechtsmeier** [comment]
@tfoote This is the common cmake configuration of yocto: http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/cmake.bbclass

**Comment by herbrechtsmeier** [comment]
All paths in the CMake files should be generated by the find_xxx macro and don't set NO_CMAKE_FIND_ROOT_PATH outside of the develspace. This allows the CMake files to work with different DESTDIR (sysroots) for programs and libraries.

pkgConfig.cmake.in:

```
if(@DEVELSPACE@)
  set(CATKIN_FIND_ROOT_PATH_MODE NO_CMAKE_FIND_ROOT_PATH)
else()
  set(CATKIN_FIND_ROOT_PATH_MODE "")
endif()
```

Example (genpy-extras.cmake.em):

```
-set(GENMSG_PY_BIN ${GENPY_BIN_DIR}/genmsg_py.py)
+find_program(GENMSG_PY_BIN genmsg_py.py PATHS ${GENPY_BIN_DIR} NO_DEFAULT_PATH @(CATKIN_FIND_ROOT_PATH_MODE))
```

**Comment by dirk-thomas** [comment]
Most other packages in ROS (e.g. genmsg, gencpp, etc.) explicitly don't use `find_*` but expose the known paths of their files using variables defined in their CMake extra files. That seems to me much more stable and addresses all the use cases defined so far.

By now _catkin_ generates output which should be completely relocatable and supports using DESTDIR during (isolated) compilation. Is there any other specific use case which currently does not work?

**Comment by dirk-thomas** [comment]
Without any specific feedback this can not be acted on. I will close it for now and mark it "wontfix". Please feel free to provide further information and the ticket might be reopened.
