### ISSUE TITLE
There is no way to suppress generation of environment setup files for catkin

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#395]
See line:

https://github.com/ros/catkin/blob/groovy-devel/cmake/all.cmake#L181

This came up when someone was trying to package catkin for Fedora and they do not allow a package to put files in the root of the prefix like that.

It should definitely be an option that catkin should support.

This will require us to introduce a new option that will include catkin, or make the current option include catkin and handle catkin as a special case in our release process by not passing this option to catkin specifically.

**Comment by dirk-thomas** [comment]
The GBP repo has been patched to not pass CATKIN_BUILD_BINARY_PACKAGE to catkin anymore.
