### ISSUE TITLE
Please provide license text with package

### ISSUE THREAD

**Issue by richmattes** [ros/catkin#398]
I'd like to request that you provide a copy of the full license text in a LICENSE or COPYING file.  It came up as part of a Fedora package review, we ask that upstreams provide a copy of the full license text that can be carried along with the binary package.

**Comment by dirk-thomas** [comment]
Do you mean for the catkin package or for all packages which use catkin?

**Comment by richmattes** [comment]
I just mean this package, to add a LICENSE file to the source tree in parallel with README, etc.  Fedora's packaging guidelines encourage us to work with upstream projects to provide the proper license text (as per http://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text)

**Comment by dirk-thomas** [comment]
Ok, will be done before the next version is released.
