### ISSUE TITLE
catkin make error with "run_dependend"-only packages

### ISSUE THREAD

**Issue by bit-pirate** [ros/catkin#401]
I have a package which holds no source code, but among others lots of launchers.
Since nothing is built, I assumed so far that I can list the launch file dependencies as `run_depend`.

Unfortunately this doesn't work nicely. Something seems to be going wrong with the creation of the cmake config files. When I make a fresh build (no build, devel etc. folders exist) I always get an error, that a "run-dependent" package can't be found:

```
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing packages in topological order:
-- ~~  - robosem (metapackage)
-- ~~  - robosem_meta
-- ~~  - robosem_potentiometers
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ skipping metapackage: 'robosem'
-- +++ processing catkin package: 'robosem_meta'
-- ==> add_subdirectory(robosem/robosem_meta)
CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:71 (find_package):
  Could not find a configuration file for package robosem_potentiometers.

  Set robosem_potentiometers_DIR to the directory containing a CMake
  configuration file for robosem_potentiometers.  The file will have one of
  the following names:

    robosem_potentiometersConfig.cmake
    robosem_potentiometers-config.cmake

Call Stack (most recent call first):
  robosem/robosem_meta/CMakeLists.txt:7 (find_package)


-- +++ processing catkin package: 'robosem_potentiometers'
```

When I run catkin_make again, it works.

I guess, the problem is, that robosem_meta, which "run-depends" on robosem_potentiometers, is built/parsed _before_ robosem_potentiometers and hence no cmake config files have been produced yet.

One workaround I found is, making robosem_potentiometers also a build dependency of robosem_meta. In that case the packages are rearranged, robosem_potentiometers is parsed/built before robosem_meta and no errors occur.

So, my questions are:
- Is my understanding of `run_depend` wrong?
  - If yes, it seems kind of useless, since everything seems to be a build_depend anyway.
  - If no, can we make run_depend rearrange the build order as build_depend does?

**Comment by dirk-thomas** [comment]
Please provide a link to your repository or more code snippets. From the description alone it is not possible to see what part is wrong in your xml / cmake.

build_depends are all dependencies which are required at build time (cmake / make time).
run_depend have no affect on the build order - they define the dependencies necessary at runtime and are therefore used for the dependencies of the generated Debian package.

**Comment by bit-pirate** [comment]
Sure. Here are the two CMakeLists from both robosem_meta (only launchers & config files) and robosem_potentiometers (only python scripts):

```
cmake_minimum_required(VERSION 2.8.3)
project(robosem_meta)

find_package(catkin REQUIRED COMPONENTS robosem_potentiometers
                                        goo
                                        ycs_mechanism_model
                                        robot_state_publisher)

catkin_package()
```

```
cmake_minimum_required(VERSION 2.8.3)
project(robosem_potentiometers)

find_package(catkin REQUIRED COMPONENTS roslib rospy goo_msgs)

catkin_python_setup()

catkin_package()

install(PROGRAMS
        scripts/robosem_potentiometers
        DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

**Comment by tfoote** [comment]
If you put it inside the find_package call inside robosem_meta it's required at build time.  Just remove it from there and everything will work. You only want to list things in the find_package for which you want catkin to be able to get your compile flags etc.  I added a note about that here: http://www.ros.org/wiki/catkin/CMakeLists.txt

**Comment by bit-pirate** [comment]
Thanks for the help! This solved my problem.
