### ISSUE TITLE
provide task-oriented how-to documentation for catkin users

### ISSUE THREAD

**Issue by jack-oquin** [ros/catkin#410]
I consider this the biggest gap in the catkin user documentation.

There is a lot of information already, but it's not very user-oriented. Answers to specific questions are hard to find. Some pages assume a much deeper understanding of CMake than a lot of people have, including me. Other places assume an understanding of the overall catkin design, which is quite complex and very different from rosbuild.

I am working on a task-oriented how-to section in my [jack-oquin/catkin](https://github.com/jack-oquin/catkin) fork. I will periodically post formatted versions here: http://farnsworth.csres.utexas.edu/docs/catkin/html/howto/howto.html.

So far there is only an outline and part of one section. I'll make a note here when more text is available. 

Please provide suggestions, feedback and corrections.

**Comment by jack-oquin** [comment]
A couple more sections written, outline expanded. Done for today.

http://farnsworth.csres.utexas.edu/docs/catkin/html/howto/howto.html

**Comment by tfoote** [comment]
That looks great Jack!

**Comment by jack-oquin** [comment]
Thanks!

It's coming along, slowly. Lots left to do.

I renamed the top-level howto page. It's here now: 
- http://farnsworth.csres.utexas.edu/docs/catkin/html/howto/index.html

**Comment by jack-oquin** [comment]
There is now has a fairly complete first draft, missing only the Python and unit test pages. 
- http://farnsworth.csres.utexas.edu/docs/catkin/html/howto/index.html

**Comment by jack-oquin** [comment]
First draft complete, except for the unit tests. I'd like some feedback on what is there now:
- http://farnsworth.csres.utexas.edu/docs/catkin/html/howto/index.html

**Comment by dirk-thomas** [comment]
catkin_overview: CMakeLists.txt: Todo:
There is no specific order required between test and install invocations.

**Comment by jack-oquin** [comment]
Noted. Thanks, Dirk!

**Comment by dirk-thomas** [comment]
catkin_library_dependencies: package.xml:
"If all the C++ code is defined in header files and no shared object libraries are provided, the <run_depend> is not needed and should be omitted."

This is not correct. The condition when to declare a run_depend is if another package is required for executing this package. This is the case the the other package contains a shared library which is used (not for static libraries since they are included at build time). Another case is if the headers of the other package are "visible" to downstream packages - usually that is the case when the headers of this package transitively include headers of the other package. If the headers of the other package are only included in cpp files a run_depend is not required.

**Comment by jack-oquin** [comment]
Ahh! Good point.

While trying to fix this, I discovered that I am still confused.

If a package A header includes a package B header, I can see that packages depending on A will have an indirect build_depend on B. But, I do not understand them having a run_depend on it.

**Comment by dirk-thomas** [comment]
catkin_library_dependencies: CMakeLists.txt:
"CMake does not know about package.xml dependencies."

Actually does know about the dependencies in package.xml. If you find_package(catkin COMPONENTS foo) it ensures that you have a build_depend on foo. And if you catkin_package(CATKIN_DEPENDS bar) it ensures that you have a run_depend on bar.

**Comment by dirk-thomas** [comment]
cpp_msg_dependencies:
Again, if the headers from the messages are visible to downstream packages (e.g. if they are included in header files) a run_depend and catkin_package(CATKIN_DEPENDS) is necessary.

**Comment by jack-oquin** [comment]
It's **catkin** that knows about package.xml dependencies, not **CMake**, right?

**Comment by dirk-thomas** [comment]
Sure.

**Comment by dirk-thomas** [comment]
building_executables: Installing:
I would suggest leaving "COMPONENT main" out of that example or why do you think is it necessary to use that?

**Comment by dirk-thomas** [comment]
building_msgs:

```
add_dependencies(your_program ${your_package_EXPORTED_TARGETS})
```

That also applies to packages (compiling C++ code)  which use message from other packages. So this should also be mentioned on the page "cpp_msg_dependencies".

**Comment by dirk-thomas** [comment]
`catkin_package()` is only mentioned on the page "building_libraries". I think it should also be described on the "Resolving dependencies" pages which mention run_depends. Commonly most of them must be passed to `catkin_package()` either as `CATKIN_DEPENDS` or `DEPENDS`.

**Comment by jack-oquin** [comment]
On Wed, May 1, 2013 at 3:20 PM, Dirk Thomas notifications@github.comwrote:

> building_executables: Installing:
> I would suggest leaving "COMPONENT main" out of that example or why do you
> think is it necessary to use that?

I have no idea what it means.

## The examples I saw did it that way, so I copied them.

 joq

**Comment by dirk-thomas** [comment]
For dynamic reconfigure anything compiling against the generated code also requires:

```
add_dependencies(your_program ${package_containing_dyn_reconf_EXPORTED_TARGETS})
```

**Comment by dirk-thomas** [comment]
Sorry, for all these tiny comments - I just filled them one by one while going through the docs. The information is great and will help users a lot - thank you for taking all the time!

**Comment by jack-oquin** [comment]
Your comments are very welcome, Dirk, in any form you find convenient.

I made some updates as we went along, but will likely have some follow-up questions. I'll get back to you with them.

**Comment by stonier** [comment]
Really nice job Jack.

One comment. In `building_libraries.html`, installing a library should cover all three target destinations. Currently:

```
install(TARGETS your_library
        LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})
```

should look like (use roscpp as a reference):

```
install(TARGETS your_library
  RUNTIME DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION}      # Windows dll location
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}    # Static library location
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})   # Shared library location
```

**Comment by jack-oquin** [comment]
On Wed, May 1, 2013 at 6:19 PM, Daniel Stonier notifications@github.comwrote:

> Really nice job Jack.
> 
> One comment. In building_libraries.html, installing a library should
> cover all three target destinations. Currently:
> 
> install(TARGETS your_library
>         LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})
> 
> should look like (use roscpp as a reference):
> 
> install(TARGETS your_library
>   RUNTIME DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION}      # Windows dll location
>   ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}    # Static library location
>   LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})   # Shared library location
> 
> Thanks Daniel.

I was willing to ignore static libraries as a special case, only used by
those who understand what needs to be done.

I had no idea Windows libraries need to be installed differently. Is there
any way to redirect `${CATKIN_PACKAGE_LIB_DESTINATION}` to the correct

## place for Windows builds?

 joq

**Comment by dirk-thomas** [comment]
No, that why for `RUNTIME DESTINATION` the variable `${CATKIN_GLOBAL_BIN_DESTINATION}` must be used.

**Comment by ahendrix** [comment]
When linking it should be ${Boost_LIBRARIES} and not ${Boost_LIBRARY}

**Comment by jack-oquin** [comment]
@ahendrix:

Are you sure? 

We've had problems with using the `_LIBRARIES` suffix. I can't remember exactly what, something to do with wanting full path names rather than `-L` parameters.

**Comment by dirk-thomas** [comment]
It is definitely `${BOOST_LIBRARIES}`. You will find that in mostly all of the ROS core packages.

The singular variant would result in a not defined variable hence an empty string.

**Comment by jack-oquin** [comment]
OK. Thanks to everyone for the correction.

It's hard to get this stuff exactly right.

**Comment by jack-oquin** [comment]
I found and fixed `${BOOST_LIBRARIES}` in two places.

Is there a problem with the `${GSTREAMER_LIBRARY}` example?

**Comment by tfoote** [comment]
That's quite possible.  Unfortunately CMake does not have strict
requirements about what variables are created.  And doesn't even have
written recommendations so any package can make it's own variables.  This
is the reason we can't do more helpful things for 3rdparty libaries between
rosdep and cmake/catkin.

**Comment by ahendrix** [comment]
I'm using and linking against gstreamer like this: https://github.com/ros-drivers/audio_common/blob/hydro-devel/audio_capture/CMakeLists.txt

YMMV.

**Comment by jack-oquin** [comment]
Thanks! I'll copy that, so we have something that's been tested.

**Comment by stonier** [comment]
On 25 May 2013 08:36, Tully Foote notifications@github.com wrote:

> That's quite possible. Unfortunately CMake does not have strict
> requirements about what variables are created. And doesn't even have
> written recommendations so any package can make it's own variables. This
> is the reason we can't do more helpful things for 3rdparty libaries between
> rosdep and cmake/catkin.

Actually, it does have an official recommendation which you can usually
find installed alongside the official cmake modules in a readme. The git
(latest) version of the readme is at:

http://cmake.org/gitweb?p=cmake.git;a=blob;f=Modules/readme.txt

with the wiki page for (new) module maintainers having a bit more detail
and also pointing at this file.

http://www.cmake.org/Wiki/CMake:Module_Maintainers

Most people follow these recommendations, and I'm pretty sure all official
ones do, but there's always a little bit of variation here and there
because it can't be enforced and sometimes modules want to expose more. One
convention that seems to have emerged that I've always found useful is to
read the comments at the start of the module itself - authors typically put
everything there.

Daniel.

**Comment by piyushk** [comment]
@jack-oquin A couple of minor points:
1. Apologies for the xx_LIBRARY vs xx_LIBRARIES issue. I pulled a fast one there. The catkin documentation [here](http://ros.org/wiki/catkin/CMakeLists.txt#Include_Paths_and_Library_Paths) suggests that you should not use `link_directories` in the CMakeLists.txt file. To work around this, I created an xx_LIBRARY variable using `find_library` to get the absolute path without using `link_directories`. I am not sure if there is a cleaner solution. Still learning CMake. I have documented this on the relevant page. Maybe it has a place in the new documentation as well?
2. I have blocked all crawlers on farnsworth.csres.utexas.edu. I haven't looked at the documentation there, but let me know if this causes any problems.
