### ISSUE TITLE
chained workspaces and include search path

### ISSUE THREAD

**Issue by stonier** [ros/catkin#428]
Ran across some search path problems for includes if you have chained source workspaces sitting on top of released debs.
- Old `ecl` in debs residing in `/opt/ros/groovy`.
- New source workspace for ecl with some changes in `/opt/ecl`.
- Chained workspace for kobuki on top of compiled ecl on top of installed groovy.

I source `/opt/ecl/devel/setup.bash` and proceed to `catkin_make` the `/opt/kobuki` workspace. I got some wierd errors, but just to test clearly, I removed some files that were included in the `/opt/ros/groovy/ecl/sigslots.hpp` (the one that kobuki calls) so that it would throw an error if it was using `/opt/ros/groovy` headers before `/opt/ecl/src/ecl_core/ecl_sigslots/include` headers. 

```
/usr/bin/c++   -Dkobuki_EXPORTS -DROS_BUILD_SHARED_LIBS=1 -fPIC -isystem /opt/ecl/devel/include -isystem /opt/ecl/src/ecl_navigation/ecl_mobile_robot/include -isystem /opt/ecl/src/ecl_lite/ecl_errors/include -isystem /opt/ecl/src/ecl_core/ecl_geometry/include -isystem /opt/ecl/src/ecl_lite/ecl_config/include -isystem /opt/ecl/src/ecl_core/ecl_type_traits/include -isystem /opt/ecl/src/ecl_core/ecl_mpl/include -isystem /opt/ecl/src/ecl_core/ecl_containers/include -isystem /opt/ecl/src/ecl_core/ecl_exceptions/include -isystem /opt/ecl/src/ecl_core/ecl_formatters/include -isystem /opt/ecl/src/ecl_core/ecl_converters/include -isystem /opt/ecl/src/ecl_core/ecl_concepts/include -isystem /opt/ecl/src/ecl_core/ecl_utilities/include -isystem /opt/ecl/src/ecl_core/ecl_linear_algebra/include -isystem /opt/ecl/src/ecl_core/ecl_math/include -isystem /opt/ecl/src/ecl_core/ecl_devices/include -isystem /opt/ecl/src/ecl_core/ecl_threads/include -isystem /opt/ecl/src/ecl_core/ecl_time/include -isystem /opt/ecl/src/ecl_lite/ecl_time_lite/include -isystem /opt/ecl/src/ecl_core/ecl_sigslots/include -isystem /opt/ecl/src/ecl_core/ecl_command_line/include -isystem /usr/include/eigen3 -I/opt/kobuki/src/kobuki/kobuki_driver/include    -o CMakeFiles/kobuki.dir/packet_finder.cpp.o -c /opt/kobuki/src/kobuki/kobuki_driver/src/driver/packet_finder.cpp
In file included from /opt/kobuki/src/kobuki/kobuki_driver/src/driver/../../include/kobuki_driver/packet_handler/packet_finder.hpp:27:0,
                 from /opt/kobuki/src/kobuki/kobuki_driver/src/driver/packet_finder.cpp:15:
/opt/ros/groovy/include/ecl/sigslots.hpp:28:31: fatal error: sigslots/signal.hpp: No such file or directory
```

Bam, it's trying to get stuff from `/opt/ros/groovy`. Now, why? There is no -I or -isystem for `/opt/ros/groovy/include` above. That comes from the environment variable configured by `/opt/ecl/devel/setup.bash`:

```
CPATH=/opt/ecl/devel/include:/opt/ros/groovy/include
```

`CPATH > -isystem`, so the higher priority headers in `/opt/ecl` are not found before `/opt/ros/groovy`. Is this a break in the logic for chained workspaces?

**Comment by dirk-thomas** [comment]
First it is weird that the build fails because it does not find the header - even if you have deleted it in one workspace it should always fall back to the same file in the underlay.

The CPATH is not really relevant at all since all necessary include directories should be provided by variables provided by find_package() calls.

In order to investigate please provide a reproducible example. This could be e.g. rosinstall/vcstool files which contain the repos of your workspaces and a description how they are supposed to overlay each other.

**Comment by dirk-thomas** [comment]
Sorry, for the close/reopen - clicked the wrong button...

**Comment by stonier** [comment]
1) I didn't delete the header, just some of it's dependent includes, so it would throw up an error. I was just trying to track down which header was getting included - could have just added an #error macro in the header to just as good effect.

2) the include directories are getting provided by find_package() calls, but they are getting added as -isystem flags, CPATH overrides these and so `/opt/ros/groovy/include` becomes king.

3) will do.

**Comment by stonier** [comment]
Ran into another oddity chasing this up with a simple example.

I thought catkin was assigning directories as `-isystem` in the output above. Turns out it was some of us doing the following:

```
include_directories(SYSTEM include ${catkin_INCLUDE_DIRS})
```

which we'd copied from some somewhere else when learning catkin. This fails _sometimes_ when working with chained workspaces as it will put the chained installspace include dir specified by CPATH (e.g. /opt/ros/groovy/include) before the individual package search paths.

So a solution for us is to remove all the SYSTEM calls to cmake. I'm curious though - why CPATH's behaviour is vague with regards to this. It sometimes puts them before the -isystem search paths, and sometimes after. Using CPLUS_INCLUDE_PATH is consistently after the -isystem calls. Note that the [gcc documentation](http://gcc.gnu.org/onlinedocs/gcc-4.4.3/gcc/Environment-Variables.html#Environment-Variables) for these variables is vague about CPATH, but not the others.

If this is indeed undefined behaviour, should we move to setting C_INCLUDE_PATH and CPLUS_INCLUDE_PATH?

**Comment by dirk-thomas** [comment]
`include_directories(SYSTEM ...)` is definitely not a good idea and should not be done. If you find any reference doing that please point it out. After changing this do you still have the original issue? If yes, can you provide more info?

**Comment by stonier** [comment]
Aye, it's fixed, so I'll close it for now. Was just wondering if people actually have a need to use SYSTEM at all, and if they do, this tiny corner case with overlays might come up. Probably not worth worrying about it till it does though.

Can't remember where I copied it from initially, but I'll send patches if I discover any instances.

**Comment by Emmanuel-Messulam** [comment]
> Aye, it's fixed, so I'll close it for now. Was just wondering if people actually have a need to use SYSTEM at all, and if they do, this tiny corner case with overlays might come up. Probably not worth worrying about it till it does though.

I've had issues where warnings were being tracked across headers to the library. The recommendation was to add SYSTEM to the `include_directories` to fix them.
