### ISSUE TITLE
Can the license tag also be given a url attribute?

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#432]
This would be useful for 3rd-party or non-standard licenses.

**Comment by tfoote** [comment]
This should be filed against catkin_pkg. https://github.com/ros-infrastructure/catkin_pkg/issues/new Probably the best thing to do is bring it up on the buildsystem mailing list so we can discuss it there.  It sounds reasonable though.

**Comment by dirk-thomas** [comment]
As specified in REP 127 (http://ros.org/reps/rep-0127.html#license-multiple-but-at-least-one) the license tag has currently no values. If you want to include the license text I would recommend placing a LICENSE file into the package root (and potentially install it in CMake). If you would like to propose to update the REP with something like a url attribute you can either post that proposal to the mailing list or fill a ticket against the rep repo (https://github.com/ros-infrastructure/rep/).
