### ISSUE TITLE
rospack finds catkin package in rosbuild build folders

### ISSUE THREAD

**Issue by meyerj** [ros/catkin#436]
I am not sure if the following is really an issue with catkin, if it should be reported in the [ros](https://github.com/ros/ros) repository instead or if it is an issue at all.

Every dry package compiled from source has a `build/` folder which contains a copy of catkin's `package.xml` in `build/catkin_generated/stamps/<package-name>/package.xml`. In some cases `rospack find catkin` will return this path instead of `/opt/ros/groovy/share/catkin` (or whereever catkin is installed). I assume rospack would not search for packages in any subdirectory if a `manifest.xml` file had been found, but there might be dangling build folders without the corresponding `manifest.xml` file within the ROS_PACKAGE_PATH, e.g. if a package has been deleted from the repo and the working copy has not been cleaned up yet.

I don't know if the wrong catkin package path found by rospack is really a problem, but I guess it would be safe to generate a `rospack_nosubdirs` file in rosbuild's build folders in analogy to `CATKIN_IGNORE` or to rename the `package.xml` file in `catkin_generated/stamps` to `package.xml.stamp` or whatever.

**Comment by dirk-thomas** [comment]
The upcoming version of catkin (0.5.66) will solve this issue by appending `.stamp` to all stamp files (see e168f0fcd2db690f221544636f4ab955ea442d6e).
