### ISSUE TITLE
message generation currently broken

### ISSUE THREAD

**Issue by kwc** [ros/catkin#44]
In a brand new build, it appears the **init**.py creation is going in the wrong projects.  When I do the first "cmake ../src", I see directories with **init**.py thunks in gen/py for projects like catkin and ros_comm, which have no messages, but I don't see any directories for projects like std_msgs, which do.  When I run "make", the messages for std_msgs get created, but there is no **init**.py, so "import std_msgs.msg" does not work.  This is currently blocking integration.

**Comment by mkjaergaard** [comment]
Fix added to genpy
