### ISSUE TITLE
Avoid generating empty -I directives in Cflags of .pc files

### ISSUE THREAD

**Issue by tho-** [ros/catkin#445]
Many groovy .pc files have empty -I directives.
This is harmful since an empty -I followed by another flag may be wrongly interpreted by compilers.

For instance, I have 87 such .pc files:
% cd /opt/ros/groovy/lib/pkgconfig/
% grep -- '-I$' *.pc | wc -l
87

Here is a small patch fixing this:

```
--- cmake/em/pkg.pc.em~ 2013-06-18 23:56:13.000000000 +0200
+++ cmake/em/pkg.pc.em  2013-06-23 17:42:07.000000000 +0200
@@ -1,6 +1,6 @@
 Name: @(CATKIN_PACKAGE_PREFIX + PROJECT_NAME)
 Description: Description of @PROJECT_NAME
 Version: @PROJECT_VERSION
-Cflags: @(' '.join(['-I%s' % include for include in PROJECT_ABSOLUTE_INCLUDE_DIRS.split(';')]))
+Cflags: @(' '.join(['-I%s' % include for include in PROJECT_ABSOLUTE_INCLUDE_DIRS.split(';') if include]))
 Libs: -L@PROJECT_SPACE_DIR/lib @(' '.join([lib for lib in PKG_CONFIG_LIBRARIES_WITH_PREFIX.split(';')]))
 Requires: @(PROJECT_CATKIN_DEPENDS.replace(';', ' '))
'''
```

**Comment by dirk-thomas** [comment]
Can you please mention at least one package for which this is the case? That makes it easier to verify the patch.

Update: python_qt_binding is one example

**Comment by tho-** [comment]
Or catkin.pc :)
