### ISSUE TITLE
default -j in catkin_make

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#446]
Right now, in catkin/builder.py, the number of default jobs is inferred from the architecture.
In my case, I have an i7 laptop with 4G of RAM. 8 jobs at 500M totally froze my machine. I know the workarounds (e.g. ROS_PARALLEL_JOBS or whatver the doc says), it's just that the first time you try catkin_make, you might be bitten by that, especially if you're new to ROS.
How about defaulting to one job, and whoever wants to go faster will simply --help it. Or you could go with half the number of jobs by default. Thx

**Comment by dirk-thomas** [comment]
That is a known trade-off. The alternative would be that the majority of the users will compile with only one job at a time since they have no idea of that option. We are convinced that the current default is better suited that a default value of 1 (or N / 2 or something else).
