### ISSUE TITLE
catkin_prepare_release: needs more flexible tag naming option

### ISSUE THREAD

**Issue by jack-oquin** [ros/catkin#447]
I would like to use this tool, but most of my packages use the `package_name-:{version}` rule for release tags.

Since `catkin_prepare_release` creates a tag with just the new version number, I have to delete that tag and create the correct one manually. So, I find myself doing the whole thing by hand, rather than take advantage of this useful tool.

Adding an appropriate option looks straightforward. I will submit a patch when I get the chance, but will not be able to work on it for at least a couple of weeks. Anyone else is welcome to fix it before then.

**Comment by jack-oquin** [comment]
With this patch, I can do this and have the tags generated correctly:

```
$ catkin_prepare_release -t package_name-
```

**Comment by dirk-thomas** [comment]
Just out of curiousity: do you have more than one package in a repo or why do you prefer the additional prefix?

**Comment by jack-oquin** [comment]
More than one package: yes. But, it's really the repo name that is used as a tag prefix.

As to why: it's mostly a matter of longstanding habit. I believe rosrelease did it that way. Bloom supports that style, but catkin_prepare_release does not.

**Comment by jack-oquin** [comment]
With SVN repositories, which do contain multiple collections of packages, it is probably necessary.

**Comment by dirk-thomas** [comment]
For SVN there no real difference regarding tagging:
- if it uses the structure `package / trunk|branches|tags` it is fine to just tag with the version number.
- if it uses the structure `trunk|branches|tags / package` it would require a prefix but would also tag _too much_ since the tag will include everything.

**Comment by jack-oquin** [comment]
Maybe it's not _necessary_, but there still exist older repositories from pre-catkin days using that tag syntax. The rosrelease tool created them.

Why are you so reluctant to support it?

**Comment by dirk-thomas** [comment]
I wrote:

```
Just out of curiousity
```

I am not reluctant to support it at all. As soon as the PR is ready it will be merged immediately. I asked these questions only to understand why people want to do that in order to understand their use case better.

**Comment by jack-oquin** [comment]
I see. 

The main reason is that old repositories used a certain tag style, and it's convenient not to have to change it.

**Comment by wjwwood** [comment]
Can this not be closed?
