### ISSUE TITLE
catkin_prepare_release is fragile if multiple remotes setup

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#450]
I have two remotes setup and it seems to be doing poorly with that.  Hopefully it could at least catch that and degrade gracefully, letting me do the push, and just changing the package.xml for me. 

```
tfoote@BigFoote:~/work/geometry_experimental/src/geometry_experimental$ catkin_prepare_release --bump minor
Repository type: git
Found packages: tf2_geometry_msgs, tf2_bullet, geometry_experimental, tf2_tools, tf2_py, test_tf2, tf2_ros, tf2, tf2_msgs, tf2_kdl
<string>:136: (ERROR/3) Unknown target name: "cache_time".
Warning: the following packages do not have a changelog file or entry for the to be released version: tf2_py
Continue without changelogs [y/N]?y
fatal: 'origin
tfoote' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
Failed to push to repository: Command '['/usr/bin/git', 'push', 'origin\ntfoote', 'finish_catkinzing']' returned non-zero exit status 128
```

**Comment by dirk-thomas** [comment]
Please provide an example repo or describe your repository in detail to be able to reproduce it.

**Comment by tfoote** [comment]
origin  git@github.com:ros/geometry_experimental.git (fetch)
origin  git@github.com:ros/geometry_experimental.git (push)
tfoote  git@github.com:tfoote/geometry_experimental.git (fetch)
tfoote  git@github.com:tfoote/geometry_experimental.git (push)

I'm on a feature branch
tfoote/finish_catkinizing which is being pushed to origin/hydro-devel

**Comment by tfoote** [comment]
```
$git remote show
origin
tfoote
```

```
$ git rev-parse --abbrev-ref HEAD
finish_catkinzing
```
