### ISSUE TITLE
New CMake warning in catkin with version 2.8.7 (latest on ubuntu 12.04)

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#452]
```
CMake Warning (dev) at /home/jbohren/ws/groovy/davinci/devel/share/ros_control_gazebo_plugin/cmake/ros_control_gazebo_pluginConfig.cmake:61 (if):
  given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package)
  intuitive_research_kit/irk_gazebo_plugins/CMakeLists.txt:4 (find_package)
```

Happens when building this package, and others: https://github.com/jhu-lcsr/ros_control_gazebo

**Comment by dirk-thomas** [comment]
According to you command line you are using groovy. I tried checking out the groovy-devel branch of ros_control_gazebo but when building it doesn't find the dependency gazebo_ros. As far as I can see that is not a package in groovy (only in hydro).

Can you please provide a rosinstall file of a workspace to reproduce the issue?

**Comment by dirk-thomas** [comment]
The packages for which this policy error is printed are likely using a too old minimum required version for CMake. catkin recommends to use (at least) `cmake_minimum_required(VERSION 2.8.3)` (see http://ros.org/wiki/catkin/CMakeLists.txt#CMake_Version).
