### ISSUE TITLE
wiki) Review newly added changelog section in bloom tutorial

### ISSUE THREAD

**Issue by 130s** [ros/catkin#456]
http://www.ros.org/wiki/bloom/Tutorials/ReleaseCatkinPackage?action=diff&rev2=15&rev1=10

Because I haven't found yet any user document about add/update `changelog` upon releasing, I added a section in bloom's tutorial. Please review, and correct / move it to somewhere more appropriate if necessary.

**Comment by dirk-thomas** [comment]
@wjwwood Can you please take a look to the changes of the bloom tutorial.

**Comment by wjwwood** [comment]
With bloom 0.4.3 it will no longer fail on the farm. Otherwise it looks fine? It has very little to do with bloom, @dirk-thomas should probably review it to make sure the `catkin_*` commands are being used/described correctly.

**Comment by tfoote** [comment]
It looks pretty good.  I reordered it so that people could simply follow it top to bottom.  And I added a bold statement to review the changelogs before committing them.
