### ISSUE TITLE
Suggestion message is not clear when gtest is not found

### ISSUE THREAD

**Issue by 130s** [ros/catkin#458]
When failed to find `gtest`, `catkin` ends with the following message:

```
$ cd catkin_ws && mkdir build && cd build
$ cmake ../src
 :
CMake Warning at catkin/cmake/test/gtest.cmake:99 (message):
  gtest not found, C++ tests can not be built.  You can run 'svn checkout
  http://googletest.googlecode.com/svn/tags/release-1.6.0 gtest' in the root
  of your workspace
```

Placing `gtest` folder at the root of workspace as suggested (in the case above at `catkin_ws`) fails with the same message. [cmake/test/gtest.cmake](https://github.com/ros/catkin/blob/groovy-devel/cmake/test/gtest.cmake#L73) looks trying to search under `src`.

So putting it in `src` works as a workaround. Or change search path up to root directory should work too? Although placing non-catkin module under catkin's workspace makes me a bit uneasy, I assume this is a result of working around the issue discussed [here](https://github.com/ros/catkin/issues/157). I just wanted to point out that the message isn't clear.

`catkin` 0.5.67

**Comment by tfoote** [comment]
It should probably state SOURCE_SPACE [rep 128](http://ros.org/reps/rep-0128.html)
