### ISSUE TITLE
Services are not generated into correct 'srv' subdirectory and clobber 'msg' generation

### ISSUE THREAD

**Issue by kwc** [ros/catkin#46]
Services being generated into 'msg' submodule instead:

> $ ls std_srvs/
> **init**.py  msg

test_rospy has both msg and srv generation, and the srv generation is clobbering out the msg files (note 'Srv'' in class names):

> $ ls test_rospy/msg/
> _ArrayVal.py            _HeaderHeaderVal.py     _TestConstants.py
> _ConstantsMultiplex.py  _HeaderVal.py           _TestFixedArray.py
> _EmbedTest.py           __init__.py             _TransitiveImport.py
> _EmptyReqSrv.py         _ListReturn.py          _TransitiveMsg1.py
> _EmptyRespSrv.py        _MultipleAddTwoInts.py  _TransitiveMsg2.py
> _EmptySrv.py            _PythonKeyword.py       _TransitiveSrv.py
> _Floats.py              _StringString.py        _Val.py

**Comment by kwc** [comment]
The following change in genpy appears to help, but there are some other references to the 'msg' dir in genpy I am not sure about:

set(GEN_OUTPUT_DIR "${ARG_GEN_OUTPUT_DIR}/srv")

**Comment by mkjaergaard** [comment]
genpy was only generating **init**.py for messages.

Fixed by https://github.com/ros/genpy/commit/3805f8460dede1d40a462d5f070c2731d48c237d

**Comment by kwc** [comment]
thanks, looks fixed
