### ISSUE TITLE
catkin_create_pkg should not create empty required folders -> incompatible with git

### ISSUE THREAD

**Issue by HWiese1980** [ros/catkin#469]
_catkin_create_pkg_ should not leave empty folders in package directories, that is it should at least create an empty dummy file. Some folders (like the include folder) seem to be required by _catkin_make_ but don't get added to a git repository since _git_ doesn't know how to handle empty folders. If you intend to manage revisions of a catkin workspace through git you end up having to create the missing folders by hand. 

Alternatively there should be a command or something to re-create the missing folders in a cloned catkin workspace.

**Comment by dirk-thomas** [comment]
Moved to the repo which provides `catkin_create_pkg`.
