### ISSUE TITLE
catkin_prepare_release should warn and not push if there are local changes

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#471]
I know of several times when people run the changelog scripts then catkin_prepare_release which changes the package.xmls and commits them and creates tags, but doesn't touch the uncommitted changelogs. 

It would be really great if it would error if there are local changes, possibly even untracked files.  And have an option to override that check if you are doing something odd intentionally.

**Comment by dirk-thomas** [comment]
It should error out if there are local modifications to changelog files and/or package.xml files.

It should warn if other files have modifications or if there are untracked files.

**Comment by dirk-thomas** [comment]
@tfoote @wjwwood Please try the latest version of `catkin_prepare_release`. If there are no issues or feedback I would like to release _catkin_ to use the weekend for the rebuild cycle.

**Comment by wjwwood** [comment]
The last quote in this line is still blue:

```
Bump version of all packages from '0.1.3' to '0.1.4'
                                                   ^ put a `@|` here
```

**Comment by wjwwood** [comment]
It's not exactly how I would format the output, but this looks fine to me.

At some point we should come up with some output formatting and color theme guidelines, so that all the tools can be consistent looking.
