### ISSUE TITLE
setting CMAKE_BUILD_TYPE for builds on top of debs causes strange crashes.

### ISSUE THREAD

**Issue by ahendrix** [ros/catkin#479]
I've been playing with CMAKE_BUILD_TYPE while building some of my controllers, and I've discovered that setting CMAKE_BUILD_TYPE=Release or CMAKE_BUILD_TYPE=MinSizeRel while building on top of debs causes strange crashes at runtime, usually when multiple threads are involved.

The Release and MinSizeRel both set optimization flags; -O3 and -Os respectively, along with a no-debug flag -DNDEBUG.

Compiling with CMAKE_C_FLAGS=-O3 and CMAKE_CXX_FLAGS=-O3 does not crash, so I suspect the problem here is the -DNDEBUG flag.

I am linking against libraries from debs that were built on the farm; any ideas on how this is interacting with those libraries to produce the problems I'm seeing?

A sample gdb backtrace of the problems I've been having:
CMAKE_BUILD_TYPE=MinSizeRel:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffecdba700 (LWP 24514)]
0x0000000000416664 in void ros::serialization::serialize<std::string, ros::serialization::OStream>(ros::serialization::OStream&, std::string const&) ()
(gdb) bt
#0  0x0000000000416664 in void ros::serialization::serialize<std::string, ros::serialization::OStream>(ros::serialization::OStream&, std::string const&) ()
#1  0x0000000000416852 in ros::SerializedMessage ros::serialization::serializeMessage<diagnostic_msgs::DiagnosticArray_<std::allocator<void> > >(diagnostic_msgs::DiagnosticArray_<std::allocator<void> > const&) ()
#2  0x000000000041285d in boost::detail::function::function_obj_invoker0<boost::_bi::bind_t<ros::SerializedMessage, ros::SerializedMessage (*)(diagnostic_msgs::DiagnosticArray_<std::allocator<void> > const&), boost::_bi::list1<boost::reference_wrapper<diagnostic_msgs::DiagnosticArray_<std::allocator<void> > const> > >, ros::SerializedMessage>::invoke(boost::detail::function::function_buffer&) ()
#3  0x00007ffff791cf36 in ros::TopicManager::publish(std::string const&, boost::function<ros::SerializedMessage ()> const&, ros::SerializedMessage&) ()
   from /opt/ros/hydro/lib/libroscpp.so
#4  0x00007ffff790f3ac in ros::Publisher::publish(boost::function<ros::SerializedMessage ()> const&, ros::SerializedMessage&) const ()
   from /opt/ros/hydro/lib/libroscpp.so
#5  0x000000000041599e in void ros::Publisher::publish<diagnostic_msgs::DiagnosticArray_<std::allocator<void> > >(diagnostic_msgs::DiagnosticArray_<std::allocator<void> > const&) const ()
#6  0x0000000000415af7 in realtime_tools::RealtimePublisher<diagnostic_msgs::DiagnosticArray_<std::allocator<void> > >::publishingLoop() ()
#7  0x00007ffff6e24ce9 in thread_proxy ()
   from /usr/lib/libboost_thread.so.1.46.1
#8  0x00007ffff7667e9a in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff53d1ccd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000000 in ?? ()
```

CMAKE_BUILD_TYPE=Release causes a std::bad_alloc elsewhere, when trying to allocate a new std::string.

**Comment by dirk-thomas** [comment]
This is a fundamental problem with C++. It is considered bad practice to mix debug and release versions of libraries (see http://stackoverflow.com/questions/11658915/mixing-debug-and-release-library-binary-bad-practice).

Each package would need to provide a debug and release version of its libraries to support your use case cleanly. Since this is not likely to happen the alternative is that you build the lower level packages also from source to avoid that kind of issues.

Since I assume that catkin can not do anything about it I will mark this ticket as closed for now. Please feel free to comment and the ticket might be reopened.
