### ISSUE TITLE
add_executable places targets in build space if called before catkin_package

### ISSUE THREAD

**Issue by piyushk** [ros/catkin#480]
This is a bit strange, since `add_library` works correctly. I am not sure if this is a bug or not, but it would be nice for the two calls to be order independent. 

[ros-sig-buildsystem thread](https://groups.google.com/forum/#!topic/ros-sig-buildsystem/ugshkzdPT0Y)
Downstream issue: https://github.com/ros-infrastructure/catkinize/issues/18

**Comment by dirk-thomas** [comment]
It is not possible to make the commands order independent since `catkin_package()` defines where executables generated by `add_executable()` are placed.

**Comment by jbohren** [comment]
More discussion here: https://groups.google.com/forum/#!topic/ros-sig-buildsystem/sIWPA2A85Ks
