### ISSUE TITLE
Override CMAKE_TOOLCHAIN_FILE in package

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#484]
Hi,

I'm attempting to use [arduino-cmake](https://github.com/queezythegreat/arduino-cmake) to build some rosserial firmware images, as was once possible in rosbuild.

Using arduino-cmake is pretty simple:

```
set(CMAKE_TOOLCHAIN_FILE arduino-cmake/cmake/ArduinoToolchain.cmake)
project(my_firmware)
generate_arduino_firmware( ... )
```

I've tried this in the package's CMakeLists, and also moved it all into a special "firmware" dir and used add_subdirectory(), but the macro doesn't seem to get set up properly in either case.

What's the best path forward here? Obviously I can just build this separately from catkin, but that would be an unfortunate step to have to take.

**Comment by tfoote** [comment]
Usually you set it on the command line at compile time.  

There's an example of setting it here for android: https://github.com/osrf/rba_scripts/blob/master/build_rosbag.sh

Are you trying to do this for just one package in a workspace. I'm not sure that will work.

**Comment by mikepurvis** [comment]
Yes, this package is generating firmware for an AVR microcontroller, so I want a separate toolchain for just the package.

If there's no provision in CMake for cross-compiling a portion of a project, I should be able to use custom_command/custom_target to wrap a cmake call which builds the firmware.

**Comment by dirk-thomas** [comment]
I am not sure if it is a good idea to even try building individual parts of a CMake invocation with different toolchains. But I am pretty certain that catkin will not provide any support doing that.

I would suggest building that specific package with its own CMake invocation. Even if it is possible to nest this invocation as a custom command in another CMake file I am not sure if that is a good idea.
