### ISSUE TITLE
catkin_prepare_release: not updating change log correctly

### ISSUE THREAD

**Issue by jack-oquin** [ros/catkin#489]
Preparing a package currently at 0.3.0 for a 0.4.0 release. There _is_ a CHANGELOG.rst with a **0.4.0 (forthcoming)** entry:

```
$ ~/git/catkin/bin/catkin_prepare_release -t velodyne_height_map- --bump minor
Prepare the source repository for a release.
Repository type: git
Found packages: velodyne_height_map
Prepare release of version '0.4.0' [Y/n]?
Warning: the following packages do not have a changelog file or entry for version '0.4.0': velodyne_height_map
Continue without changelogs [y/N]?n
Aborted release, populate the changelog with 'catkin_generate_changelog' and/or 'catkin_tag_changelog' (or manually).
```

Running `catkin_tag_changelog` works, however:

```
$ catkin_tag_changelog --bump minor
Found packages: velodyne_height_map
Tag version 0.4.0
Renaming section '0.4.0 (forthcoming)' to '0.4.0 (2013-07-24)' in package 'velodyne_height_map'...
Writing updated changelog files...
$ git diff
diff --git a/CHANGELOG.rst b/CHANGELOG.rst
index 1e5bb67..1e13f5d 100644
--- a/CHANGELOG.rst
+++ b/CHANGELOG.rst
@@ -1,8 +1,8 @@
 Change history
 ==============

-0.4.0 (forthcoming)
--------------------
+0.4.0 (2013-07-24)
+------------------

  * ROS Hydro.
  * Convert to catkin build system.
```

**Comment by dirk-thomas** [comment]
`catkin_prepare_release` is not supposed to touch the changelog files and only verifies that the source repo is in releasable state.

`catkin_generate_changelog` and `catkin_tag_changelog` are the right tools to use for that.

What behavior do you expect?

**Comment by jack-oquin** [comment]
I expected it to fill in the date, just like `catkin_tag_changelog` did.

**Comment by dirk-thomas** [comment]
I would rather not change the behavior of `catkin_prepare_release`. It already warns the user and tells explicitly which commands to run for dealing with changelogs. I think implicitly doing a `catkin_tag_changelog` or even a `catkin_generate_changelog` is not a good idea.

@tfoote @wjwwood What is your opinion on this?

**Comment by jack-oquin** [comment]
If this is _intended_ not to work the way users will expect, then it's not a bug, but rather an enhancement request.

**Comment by dirk-thomas** [comment]
The idea is that `catkin_prepare_release` _automates_ the task necessary to perform a release of a source repo.

But _changelogs_ should not be generated automatically without manual review of the maintainer. Therefore it was intentional that they are handled by a _different_ tool which is executed _beforehand_.

Depending on the feedback we can either maintain the separation or drop the extra step of manually reviewing the changelog and automate it.

**Comment by tfoote** [comment]
There is a strong parallel between catkin_prepare_release and catkin_tag_changelog, both step through the packages and change the version number.  

I agree that we should keep encouraging updating the changelogs independently and shouldn't automate the changelog generation.  So a good compromise might be to have prepare release do the tagging for both package.xml and changelogs, but error/require override if the changelog does not have a forthcoming section.  

This basically that before you run prepare_release all changes should be staged, and it's just going to help you do the version number tagging.
