### ISSUE TITLE
make installed code relocatable

### ISSUE THREAD

**Issue by dirk-thomas** [ros/catkin#490]
Installed code should not (or as few as possible) contain absolute path information. Currently a lot of code contains the `CMAKE_INSTALL_PREFIX`.

One goal would be to compile a workspace with `DESTDIR=/tmp/destdir catkin_make_isolated --install` and be able to build another workspace on top of that.
At best it should be possible to run everything from the installed workspace and run the tests of workspaces built on top.

The following things need to be updated to not use absolute paths:
- [x] env.sh references setup.sh, 9cfba6ff417b561e2454ed1c8fca819643ec4892
- [x] setup.SHELL references setup.sh, 9cfba6ff417b561e2454ed1c8fca819643ec4892
- [x] setup.sh references _setup_util.py,
  sourced shell scripts can not determine their own path therefore enable the user to override the default path via an environment variable, using `CATKIN_SETUP_DIR`, 9cfba6ff417b561e2454ed1c8fca819643ec4892
- [x] _setup_util.sh contains abs. path to prefix CPP,
  should be passed in from setup.sh, 9cfba6ff417b561e2454ed1c8fca819643ec4892
- [x] generated CMake config files, e.g. include directories, 74af67d80936a1a4c565c25979687002dc0a99fa
- [x] environment hooks,
  require context about their workspace from the outside, setup.sh need to provide that individually for each environment hook, using the environemt variable `CATKIN_ENV_HOOK_WORKSPACE` for that 44b3234dbaa36f3210184ebea93c82d7a5ce3de4
- [x] catkin_make_isolated must set the environment variable to override the base path when building with `DESTDIR`, 7282a4bb832610e16d1a63c8336be41d781cb0e6

Changes required in other packages:
- [x] CMake extra files,
  should utilize `${@(PROJECT_NAME)_DIR}/../../..` to achieve the same as `@(CMAKE_INSTALL_PREFIX)`, ros/gencpp@e5acaf690d6276d427f6b0ecaab67b52f55bbe8a, ros/genlisp@42458c1d0a4ca1d3e78b8b1b2cac5e8fb2169a60, ros/genpy@1bc78ac23e465c1b3ef040d11c53d89cdc00b8ae, ros/ros@3681bd0ebd5d19f26421d8af844009e9970e9b58, ros/ros_comm@e0366e14128ed0083e9450bbe9f98fd9b2806454,
  ros/roslisp@58657c8827c70c3302c8755019500be2c2cdd95b
- [x] environment hooks, ros/ros@3681bd0ebd5d19f26421d8af844009e9970e9b58

Message Generation:
- [x] the generated CMake files contain absolute paths to message/service files, ros/genmsg@cb45b131576a898ced69e3e5e9758173365dc5cf

All patches are committed to the `relocatable` branch of the respective repos. A file to checkout the modified repos using https://github.com/dirk-thomas/vcstool can be found here: https://gist.github.com/dirk-thomas/6092081

**Comment by herbrechtsmeier** [comment]
@dirk-thomas Please correct the `dynamic_reconfigure_BASE_DIR` in [extras.cmake.em](/ros/dynamic_reconfigure/blob/master/cmake/extras.cmake.em) of dynamic_reconfigure also.

**Comment by herbrechtsmeier** [comment]
@dirk-thomas I have test the patches and they work. Nevertheless I would proposed to replace `${@PROJECT_NAME@_DIR}/../../../@(CATKIN_PACKAGE_BIN_DESTINATION)` with a new global catkin variable `${@PROJECT_NAME@_BIN_DIR}` which could be overwrite (passed) by the build environment to point to the native system root. Otherwise we get problems when somebody use the path for binaries instead of python scripts.

**Comment by dirk-thomas** [comment]
I am glad to hear that it works for your use case.

Regarding the variable: this variable should not be overwritten - not even for cross compilation. If a package requires compiled binaries to build itself / downstream stuff it needs to reference that using a separate variable pointing to a different directory. E.g. in the case where a package uses both (a Python script as well as a compiled binary) to build downstream stuff it will not have both of the executables in the same directory anyway.

Each package should consciously deal with this in its CMake extra file. catkin should not try to populate any package-specific variables. For the source/devel space catkin would not even be able to set a reasonable directory since it just does not know where the binaries in the package are.

**Comment by herbrechtsmeier** [comment]
In that case the binaries need to use the find_binary function to get the real path of the binary.

As the long time goal it would be nice if catkin and the CMake extra files always use the find_binary function to get the real path of all executed scripts and binaries. This enables the cross build environment to use all binaries and as well scripts from the native system root if it doesn't install any binaries and scripts into the cross system root.

**Comment by dirk-thomas** [comment]
For packages which do not generate compiled binaries it can stay the way as it is with these patches. I don't see a reason to change that even in the long term.

For compiled binaries we should indeed use the find_\* CMake functions. But that should handled by the first package which actually requires that. Currently no (wet) package requires compiled binaries during the build (as far as I know) and that was an important goal of the new buildsystem.

I will go ahead and merge all above mentioned patches. Releases for the separate packages will follow when ever each package has "enough" changes accumulated.

**Comment by herbrechtsmeier** [comment]
As long as the build machine (native system root) and cross compiled machine (cross system root) use the same python version it doesn't matter which python script is used and its a design decision.

@dirk-thomas thanks for your work. We will update our recipes in meta-ros after you have apply the different patches.

**Comment by dirk-thomas** [comment]
All repos listed in this ticket has been updated to be relocatable - therefore closing this ticket.

In case other repos use `CMAKE_INSTALL_PREFIX` in the CMake extra files please fill further tickets against these repos directly.
