### ISSUE TITLE
migrate eigen-config.cmake to the new cmake_modules package

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#492]
Also we should convert it to a `FindEigen.cmake` module.

This will involve finding and fixing anyone who uses the existing catkin provided CMake config for Eigen.

**Comment by wjwwood** [comment]
https://github.com/ros/cmake_modules

**Comment by wjwwood** [comment]
One of the issues with doing this is that people currently use it via catkin so moving it would break things. We can do this for Indigo, but for Hydro and Groovy we can only add it to `cmake_modules`.

**Comment by dirk-thomas** [comment]
Ticket filled for `cmake_modules` to readd the same functionality there: https://github.com/ros/cmake_modules/issues/10

**Comment by dirk-thomas** [comment]
Closed by a94d0415d7b7168eb0f49e490decb6835719aa94
