### ISSUE TITLE
documentation: add how-to example of using add_rostest_gtest()

### ISSUE THREAD

**Issue by jack-oquin** [ros/catkin#495]
See: ros/ros_comm#258

**Comment by dirk-thomas** [comment]
This should not be put into the catkin doc since it is not related to catkin at all. That should also be the case for other stuff (#493). Instead the how-to should reference package specific documentation.

**Comment by dirk-thomas** [comment]
Closing this was to fast. While rostest provides docs about the usage the how-to doc of catkin should point to that.
