### ISSUE TITLE
Error in C++ message auto generation in ROS groovy

### ISSUE THREAD

**Issue by drdas** [ros/catkin#501]
If a comment description line in a .msg file (starting with #) ends in a a special character such as ( ), 
extra newlines are added in the generated header file which gives compiler errors when included.

**Comment by tfoote** [comment]
Please file this against gencpp https://github.com/ros/gencpp/issues/new

And please include an example message file with the error.  And also the generated file where you think there's a problem.  As well as the compiler warnings.
