### ISSUE TITLE
Failed to process package 'qt_gui_cpp

### ISSUE THREAD

**Issue by ftifpt** [ros/catkin#502]
When i run command in osx: ./src/catkin/bin/catkin_make_isolated --install: i have a problem:

make[3]: **\* [siplibqt_gui_cpp_sipqt_gui_cppRosPluginlibPluginProvider_ForPlugins.o] Error 1
make[3]: **\* Waiting for unfinished jobs....
make[3]: **\* [siplibqt_gui_cpp_sipqt_gui_cppRosPluginlibPluginProvider_ForPluginProviders.o] Error 1
make[2]: **\* [/ros_catkin_ws/devel_isolated/qt_gui_cpp/lib/python2.7/site-packages/qt_gui_cpp/libqt_gui_cpp_sip.dylib] Error 2
make[1]: **\* [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'qt_gui_cpp': 
  Command '/ros_catkin_ws/install_isolated/env.sh make -j2 -l2' returned non-zero exit status 2

Please help me

**Comment by tfoote** [comment]
Please ask for help on http://answers.ros.org 

PS you only copied the summary errors, the real errors are likely above what you copied and pasted.

**Comment by ftifpt** [comment]
thanks
