### ISSUE TITLE
Problems with german vowel mutations like äöü

### ISSUE THREAD

**Issue by dreuter** [ros/catkin#503]
When a author/maintainer has a name with a vowel mutation catkin won't build, but throw an exception like:
'ascii' codec can't encode character u'\xf6' in position 60: ordinal not in range(128)

I'm not saying that using vowel mutations in a name would be a good idea, but I think the error thrown should be more informative e.g. the encoded string should be printed and give an error message which says that those characters should not be used.

Why is it encoded to ascii anyway, wouldn't UTF-8 or Unicode be a better solution?

**Comment by dreuter** [comment]
This problem does also occur with vowel mutations in descriptions.

**Comment by dirk-thomas** [comment]
Moved to catkin_pkg which is responsible of parsing the package.xml files: ros-infrastructure/catkin_pkg#63
