### ISSUE TITLE
Support multiple package names with catkin_make --pkg

### ISSUE THREAD

**Issue by meyerj** [ros/catkin#504]
Would it be easily possible to extend the `catkin_make --pkg` command to support building multiple packages at once?

I am using a rosbuild workspace that overlays a catkin devel-space. In the meantime, there are quite a number of packages in the catkin workspace. I would like to be able to run something like

```
cd $MY_CATKIN_WORKSPACE &&
  catkin_make --pkg `rospack depends my_rosbuild_package`
```

just to get the idea. Of course in this simple use case `catkin_make` would have to ignore package names that are not part of the catkin workspace.

**Comment by wjwwood** [comment]
Not to invalidate this suggestion, but you should consider breaking up your workspaces if you find yourself needing to cherry pick packages to build in order to save time.

I'm not sure what technical road blocks there are, if any, for this feature, @dirk-thomas can likely comment to that.
