### ISSUE TITLE
Add option to use symlinks for packages' python export paths

### ISSUE THREAD

**Issue by eacousineau** [ros/catkin#509]
While the `__init__py` `extend_path(...)` technique is cross-platform, it prevents IDEs such as PyDev or Spyderlib from easily parsing the packages to provide auto-completion. A non-cross-platform solution for this on Linux is to symlink direclty to the `src/` folder.
It would be nice to have some simple option to cause catkin to create symlinks, something equivalent to

```
cd ${CATKIN_DEVEL_PREFIX}/lib/python2.7/dist-packages
for dir in ${export_dirs}
do
    ln -s $(find ${PROJECT_SOURCE_DIR}/${dir} -mindepth 1 -maxdepth 1 -type d) .
    # Or all files: ln -s ${PROJECT_SOURCE_DIR}/${dir}/* .
done
```

Perhaps the optional environment variable could be something like `CATKIN_DEVEL_PYTHON_USE_SYMlINK`, store it in `~/.config`, or as a flag (less preferrable).

This would cause problems if (a) there are package name conflicts at the top-level, or (b) if someone switches on / off this flag and does not re-build the workspace, but for (a) that's just a design issue, and (b) could be fixed by checking the variable and seeing if the target already exists and should be a symlink.

I would be willing to implement this in the next few weeks if others find it useful.

**Comment by dirk-thomas** [comment]
Since generated Python files are also dropped into the devel space (e.g. for messages) I don't see how that would work with symlinks.

**Comment by wjwwood** [comment]
You would have to generate all of the files to devel space, then fill in around them using symlinks.

**Comment by wjwwood** [comment]
It might also affect how the PYTHONPATH is setup.

**Comment by wjwwood** [comment]
No probably not, since it currently points to devel space anyways.

**Comment by wjwwood** [comment]
I think this would be a useful feature, we have also had trouble with autodoc systems not playing nice with this setup, and I think the symlinks would help here.

**Comment by eacousineau** [comment]
Ah, I did not think about how hard it would be to get things going with the '.msg' generated setup, @dirk-thomas.

We could create symlinks to individual files as @wjwwood mentioned. The only thing here is that during development, if you change the directory structure, you will have to re-run CMake every time, which reinvokes CMake for all packages in the workspace (at least,that's the behavior I've seen so far). That seems kind of hefty.
Another option could be to make a script in `lib/${PROJECT_NAME}` called `_python_link_update.py`, or maybe a CMake-less make target in the the whole devel-space, which will go through and update the symlinks in dist-packages when in devel-space. However, that is still pretty manual.

Is there a way, aside from the extending `sys.path` and symlinks, to make 'partial' packages so that you could have the `${PROJECT_NAME}.msg` module in directory and `${PROJCT_NAME}` in the original source directory?

(I did look a little at `aufs` and `unionfs`, but those would definitely complicate the issue haha)

**Comment by wjwwood** [comment]
I think given the draw backs you mentioned above, it would be a nice feature to have (as long as the user understands that cmake needs to be run each time the folder structure updates), but should be off by default and optionally turned on.

**Comment by eacousineau** [comment]
That sounds good. Can I ask what problems y'all had with autodoc?

**Comment by wjwwood** [comment]
@eacousineau basically the autodoc would extract information from the `__init__.py` from the source space, but would put the `__init__.py` from the devel space in as the "source code" when you clicked on "view source" for a function.

**Comment by dirk-thomas** [comment]
The doc job operates on the install space only now. Especially to contain all Python code - static as well as generated but not those relaying **init**.py files.

**Comment by dirk-thomas** [comment]
Since it is not likely that feature will ever be implemented I will close this ticket and mark it as "wontfix".
