### ISSUE TITLE
Putting CATKIN_BLACKLIST_PACKAGES in environment variable?

### ISSUE THREAD

**Issue by eacousineau** [ros/catkin#510]
I am interested in having CATKIN_BLACKLIST_PACKAGES default to the environment's value. If anyone would find this useful, I could submit a patch for this.

Otherwise, would it be simpler to make a wrapper for catkin_make, named something like `catkin_make_env`, that would pass this value (and possibly others) via command line?

**Comment by dirk-thomas** [comment]
Imo passing such arguments via the command line interface is much cleaner and much more visible to the user than using environment variables. The user can easily invoke `catkin_make/cmake -DCATKIN_BLACKLIST_PACKAGES=$CATKIN_BLACKLIST_PACKAGES` if he has the names stored in an environment variable and wants to pass it along.

Especially in this case you might really consider to change your workspace layout if you see yourself in the need to use CATKIN_BLACKLIST_PACKAGES often.

**Comment by dirk-thomas** [comment]
Closing this ticket since passing the flag via the command line is the working recommended way and an environment variable is not considered to be a good alternative.
