### ISSUE TITLE
rostest output file name determined by sub folder in package

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#512]
rostest, via rosunit, generates the output file name based on the test name, but if the test file is in a subdirectory of the package, say `/path/to/package/build/test_file.xml`, then it also prepends the relative path to the name, separating with underscores. So a generated file that is normally called `rostest-test_rostest_foo.xml` will be called `rostest-build_test_rostest_foo.xml` if the catkin package is built in source in a folder called `build`. This is likely done by rosunit to work with some rosbuild constraint, so it seems unlikely that we could change the behavior of rosunit here.

This is only a problem when building a catkin package **in source**. A workaround is to build out of source.

Instead I think catkin should be aware of this. In my package I get this:

```
% make run_tests                                                                                                                                                               ±
Built target clean_test_results
Built target tests
-- run_tests.py: execute commands
  /Users/william/hydro/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/Users/william/devel/capabilities --package=capabilities --results-filename test_rostest_demo.xml /Users/william/devel/capabilities/test/rostest/demo.test
... logging to /Users/william/.ros/log/rostest-dosa-19226.log
[ROSUNIT] Outputting test results to /Users/william/devel/capabilities/build/test_results/capabilities/rostest-build_test_rostest_demo.xml
[WARN] [WallTime: 1379627833.998186] No default provider given for capability interface 'minimal_pkg/Minimal'.
[WARN] [WallTime: 1379627833.998621] 'minimal_pkg/Minimal' has only one provider, 'minimal_pkg/minimal', using that as the default.
testdemo ... ok

[ROSTEST]-----------------------------------------------------------------------

[capabilities.rosunit-demo/test_demo][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /Users/william/.ros/log/rostest-dosa-19226.log
-- run_tests.py: verify result "/Users/william/devel/capabilities/build/test_results/capabilities/rostest-test_rostest_demo.xml"
Cannot find results, writing failure results to "/Users/william/devel/capabilities/build/test_results/capabilities/MISSING-rostest-test_rostest_demo.xml"
Built target _run_tests_capabilities_rostest_test_rostest_demo.test
Built target _run_tests_capabilities_rostest
-- run_tests.py: execute commands
  /usr/local/Cellar/cmake/2.8.11.2/bin/cmake -E make_directory /Users/william/devel/capabilities/build/test_results/capabilities
  /usr/local/bin/nosetests -P --process-timeout=60 --where=/Users/william/devel/capabilities/test --with-xunit --xunit-file=/Users/william/devel/capabilities/build/test_results/capabilities/nosetests-test.xml
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.295s

OK
-- run_tests.py: verify result "/Users/william/devel/capabilities/build/test_results/capabilities/nosetests-test.xml"
Built target _run_tests_capabilities_nosetests_test
Built target _run_tests_capabilities_nosetests
Built target _run_tests_capabilities
Built target run_tests
```

The important lines are:

```
[ROSUNIT] Outputting test results to /Users/william/devel/capabilities/build/test_results/capabilities/rostest-build_test_rostest_demo.xml
```

and 

```
-- run_tests.py: verify result "/Users/william/devel/capabilities/build/test_results/capabilities/rostest-test_rostest_demo.xml"
```

`run_tests.py` (in catkin) is expecting the file to be called `rostest-test_rostest_demo.xml`, but rosunit is creating `rostest-build_test_rostest_demo.xml`. I think the right way to fix this is to have `run_tests.py` expect a different name if the build space is a subfolder of the source space. I'm not sure it has all of the information needed to get the same name as rosunit is producing, but the only other option would be to change rosunit's behavior and I think that would be more difficult to verify.

**Comment by wjwwood** [comment]
Something else to consider, it may ultimately be a bug in rostest, see:

```
-- run_tests.py: execute commands
  /Users/william/hydro/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/Users/william/devel/capabilities --package=capabilities --results-filename test_rostest_demo.xml /Users/william/devel/capabilities/test/rostest/demo.test
```

`run_tests.py` is explicitly passing `--results-filename test_rostest_demo.xml`, yet the output file name is different from that.

**Comment by dirk-thomas** [comment]
I could not reproduce it with the following scenario:
- git clone capabilities repo
- create build folder inside the repo folder
- cmake .. && make && make run_tests

Can you please provide more information to reproduce the issue?

**Comment by wjwwood** [comment]
Try this branch:

https://github.com/osrf/capabilities/tree/rostest_bug
