### ISSUE TITLE
catkin_prepare_release) Handle package paths beneath trunk in svn repository

### ISSUE THREAD

**Issue by 130s** [ros/catkin#513]
Same as asked [here](http://answers.ros.org/question/70054/catkin_prepare_release-fails-with-svn-upstream/), our team stores multiple packages in a single `svn` repository, by placing them BENEATH `/trunk` folder, which current `catkin_prepare_release` returns error with.

What about adding an option (eg. `--pkg`) to accept those packages under `/trunk`?

**Usecase-1**: releasing a package directly beneath /trunk

```
URL of the package: `https://foo.googlecode.com/svn/trunk/bar`
Version current: 1.0.0
```

then:

```
$ catkin_prepare_release --pkg bar
```

yields:

```
tag: `https://foo.googlecode.com/svn/tag/bar-1.0.1`
version 1.0.1
```

(Apparently this can utilize the same logic with `--tag-prefix` option internally)

**Usecase-2**: releasing a package at deeper level

```
URL of the package: `https://foo.googlecode.com/svn/trunk/bar/baz`
Version current: 1.0.0
```

then:

```
$ catkin_prepare_release --pkg baz
```

yields:

```
tag: `https://foo.googlecode.com/svn/tag/baz-1.0.1`
version 1.0.1
```

---

There maybe insufficiency in the usecases but hope you get the basic idea of this suggestion. 

What I am also not clear about `catkin_prepare_release` is what other situations need considered; for example, `trunk` isn't the only suffix that's inspected [in tag_repository](https://github.com/ros/catkin/blob/1b2366e1cee733e6ffab842202098025d11189fe/bin/catkin_prepare_release#L121) but do we need same mechanism that I suggested above for `branch`, `tag`?

If this is good and we get to consensus I can try making a patch (if it doesn't get too complicated).

Again I honestly don't know if this is a valid enhancement with respect to svn convention. However, it'll be very helpful in our release workflow (at JSK lab). Also I just guess that there could be developers who might not strictly follow rules in detail.

...gets so long. Thanks for finishing until the end!

**Comment by dirk-thomas** [comment]
You might consider restructuring your SVN repository so that each unit of release resides in its own trunk/brnaches/tags subfolder. The layout you currently use is not well supported by any of the tools in the chain and requires additional manual intervention which is otherwise not necessary. Just simply because it is not automatically possible to determine what the users layout is and what he wants.

If you want to provide a patch to extend the SVN support of catkin_prepare_release that is fine but all options which are SVN specific should be clearly labeled accordingly.

**Comment by 130s** [comment]
Thanks for reviewing the plan. Then I'll start making a patch.

> all options which are SVN specific should be clearly labeled accordingly.

Good point. I got it.

I've taken a look at some of the existing `svn` repositories in ROS and these seem to have the same structure (ie. storing packages under `/trunk`). Putting aside the question if it's good or not, this new feature might be of use for those existing users.

https://code.ros.org/svn/ros/stacks/multimaster_experimental/trunk/
https://svn.code.sf.net/p/cmu-ros-pkg/code/trunk/
http://alufr-ros-pkg.googlecode.com/svn/trunk

**Comment by 130s** [comment]
I've tested https://github.com/ros/catkin/pull/527 that implements the feature discussed here. Thanks all!
