### ISSUE TITLE
Catkin installs setup files in bad locations

### ISSUE THREAD

**Issue by nkoenig** [ros/catkin#514]
Running `cmake ../; make; make install` installs setup files (setup.bash, setup.sh, setup.zsh, etc) in `/usr` or `/usr/local`.

In order to correct this behavior one has to use the `-DCATKIN_BUILD_PACKAGE="1"`. 

The standard method of building software from source should probably not install files directly into `/usr`.

**Comment by dirk-thomas** [comment]
`/usr/local` is the default install prefix for CMake (see http://www.cmake.org/cmake/help/v2.8.11/cmake.html#variable:CMAKE_INSTALL_PREFIX).

The option `CATKIN_BUILD_PACKAGE` has nothing to do with the install prefix - it just decides if catkin should generate setup files. Even with this option set the installed files of your CMake project will go into the install prefix.

You can either set a custom install prefix using `-DCMAKE_INSTALL_PREFIX=/my/path` or use `catkin_make(_isolated)` which will set a workspace relative install prefix by default.

**Comment by dirk-thomas** [comment]
Duplicate of #380.
