### ISSUE TITLE
Documentation for Environment Files Incomplete?

### ISSUE THREAD

**Issue by eacousineau** [ros/catkin#516]
I was looking at the docs for catkin here: http://docs.ros.org/api/catkin/html/user_guide/environment.html

At the end it says:

```
**NOTE**: These environment hooks are only for variable settings. Shell aliases and functions
```

Can't really tell if it implies that we should or shouldn't put aliases / functions in there. (Kind of a cliff-hanger haha)

**Comment by dirk-thomas** [comment]
I clarified the docs. Yes, you can use the environment hooks for variables, shell aliases, auto complete functions etc.
