### ISSUE TITLE
catkin should depend on make (on Linux, anyway)

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#517]
From a bare bones install of ros-hydro-ros-base, I get creepy errors when I try to build a new empty workspace:

```
$ mkdir -p ws/src
$ cd ws
$ catkin_init_workspace src
$ catkin_make
Base path: /home/administrator/ws
Source space: /home/administrator/ws/src
Build space: /home/administrator/ws/build
Devel space: /home/administrator/ws/devel
Install space: /home/administrator/ws/install
####
#### Running command: "cmake /home/administrator/ws/src -DCATKIN_DEVEL_PREFIX=/home/administrator/ws/devel -DCMAKE_INSTALL_PREFIX=/home/administrator/ws/install" in "/home/administrator/ws/build"
####
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file:/home/administrator/ws/build/CMakeFiles/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file:/home/administrator/ws/build/CMakeFiles/CMakeCXXCompiler.cmake
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

Yikes! Turns out that a minimal Ubuntu install doesn't have `make` by default. Once I installed it with apt, things were peachy. I guess "make" is not a cross-platform dependency, but almost certainly should be installed with the Ubuntu ros-hydro-catkin package. How can this be accomplished?

**Comment by wjwwood** [comment]
When building anything from source it recommended to install the `build-essentials` deb:

http://wiki.ros.org/hydro/Installation/Source

Some of the most basic dependencies are expected to be resolved before building anything from source, including `cmake`, `c/c++ compiler`, `make`, and `Python`. One thing we could do is add a `build-essentials` rosdep rule which resolves on Ubuntu/debian, but on other systems where this doesn't apply (OS X) it will just resolve to nothing.

**Comment by wjwwood** [comment]
In fact the only reason `catkin` is installed with `ros-base` is to ensure that the `setup.*sh` files are in place. catkin is not required for the runtime of any of our packages, there was actually a point where we considered having a 'setup files deb' which got installed for things like `ros-base` so that we didn't have to install catkin for runtime only situations.

**Comment by dirk-thomas** [comment]
I think it would make sense if there would be a catkin and a catkin-dev package. Then the catkin-dev package could depend on somthing like build-essentials. But generally catkin should not have a run dependency on them since those are not required to run anything installed from Debian packages.

**Comment by mikepurvis** [comment]
A `catkin-dev` package to me implies that it's about hacking on catkin itself, or building things which need to somehow link against catkin. Is catkin not a build system, analogous to Make, CMake, Ant, etc? IMO, the baseline `catkin` package should install everything required to _use_ catkin for its intended purpose (building things) on a given platform. So: Python, Make, all of it.

If the objective is to avoid installing build tools for a runtime-only deployment of ROS, then I feel that `catkin` should be excluded from ros-base. If necessary, go the other direction from `catkin-dev` and create a `catkin-runtime` package which contains the workspace management facilities with none of the build stuff.

**Comment by dirk-thomas** [comment]
`catkin-dev` does not imply hacking on catkin - the same way as `boost-dev` does not imply hacking on boost.

`catkin-dev` would allow developing against catkin like it is for `boost-dev`.

`catkin` as a runtime dependency would only contain the parts of catkin which are necessary to run dependent stuff. E.g. that includes the setup.\* file under /opt/ros/DISTRO. Therefore `catkin` can not be removed from `ros-base` but must be there for any ROS packages to be functional.

**Comment by wjwwood** [comment]
I would point out that `CMake` doesn't install `make`.

**Comment by mikepurvis** [comment]
Okay, makes sense. It's a fairly academic, in any case. Adding `build-essentials` to our Hydro robot PC preseed is not a problem.

**Comment by DLu** [comment]
FWIW, I just ran into this issue. I would think that any package that installs catkin should depend on build-essential.

**Comment by dirk-thomas** [comment]
Beside the already mentioned reasons above I can describe more cases why `catkin` should neither depend on a compiler nor make:

First you can have a package which does not require a compiler, e.g. any package with only Python code or messages.

Second you don't have to use `make` - you can use `ninja` instead and that decision is up to the developer performing the build.
