### ISSUE TITLE
Should catkin warn about naming conventions in isolated / pure-cmake builds?

### ISSUE THREAD

**Issue by jbohren** [ros/catkin#529]
Currently, if a package is named like "orocos-kdl" instead of "orocos_kdl" it generates a warning when using catkin. Should this happen for isolated builds where we can't enforce naming conventions on 3rd party packages?

**Comment by dirk-thomas** [comment]
The warning is coming from `catkin_pkg` and not from `catkin` itself. `catkin_pkg` does currently not provide any mechanism to change the output of these warnings so `catkin` can not suppress it.

Could you fill a feature request against catkin_pkg to support that use case?
