### ISSUE TITLE
Isolated build of plain cmake package has problem with setup scripts

### ISSUE THREAD

**Issue by scpeters** [ros/catkin#530]
Several files are missing from the devel_isolated folder after building a plain cmake package on OSX. Build sdformat for example:

```
mkdir -p ~/ws/src
cd ~/ws/src
git clone https://github.com/ros/catkin.git
hg clone https://bitbucket.org/osrf/sdformat -u package_xml
cd ~/ws
./src/catkin/bin/catkin_make_isolated
```

Then the catkin package will have some setup files that sdformat does not:

```
$ ls ~/ws/devel_isolated/catkin
_setup_util.py env.sh         lib            setup.sh       share
bin            etc            setup.bash     setup.zsh
```

```
$ ls ~/ws/devel_isolated/sdformat
env.sh   include  lib      setup.sh share
```

The missing files are a problem because `devel_isolated/setup.bash` tries to reference them:

```
$ cat devel_isolated/setup.bash 
#!/usr/bin/env bash
# generated from catkin.builder module

. "~/ws/devel_isolated/sdformat/setup.bash"
$
```

It won't work properly if I source `devel_isolated/setup.bash`; I have to source `devel/setup.sh` instead.

I also tested building a single catkin package (genmsg) and it did not have this problem.

**Comment by wjwwood** [comment]
Did you change branches on sdformat, the default branch there isn't a catkin package nor does it have a package.xml.

**Comment by scpeters** [comment]
Sorry package_xml branch for sdformat.

**Comment by dirk-thomas** [comment]
I guess your are still using catkin 0.5.74? I think the issue you refer to has been fixed in 973f767fcc639776f9aaa22e615800f017fa439e. Please try a newer catkin version (likely currently only available from shadow-fixed).

**Comment by scpeters** [comment]
Actually I am using a source build b9f71f1da58c7c6c320dc0f138e8f48e2cd322a7.

As I look again, the problem appears to be with the `devel_isolated/setup.bash`:

```
$ cat devel_isolated/setup.bash 
#!/usr/bin/env bash
# generated from catkin.builder module

. "~/ws/devel_isolated/sdformat/setup.bash"
$
```

Since `~/ws/devel_isolated/sdformat/setup.bash` does not exist.

Also it's not just an osx problem. I hadn't noticed it on linux since I was using the hydro version of catkin.

**Comment by dirk-thomas** [comment]
The specific issue here is that the plain cmake package is the last one to process in the workspace. In that case the toplevel setup.\* scripts can't find there counterpart in the packages devel folder. I will come up with a fix for that...
