### ISSUE TITLE
use 'builtin' command in setup.bash

### ISSUE THREAD

**Issue by baxelrod-bdai** [ros/catkin#542]
The setup.bash script should use "builtin cd" instead of just "cd".  This fixes a bug for people who have created a function called "cd" to perform extra functionality in addition to changing directories, (for example doing an "ls" upon entering the new directory).  The new line should be:

```
_CATKIN_SETUP_DIR=$(builtin cd "`dirname "${BASH_SOURCE[0]}"`" && pwd)
```

This will not change any behavior for those people who have not changed the functionality of the "cd" command.

I understand that the person who overrode "cd" should have the onus on them to fix any side-effects caused by their customization.  However, the error you get is very non-intuitive and can take a long time to figure out why that command is not working.

**Comment by dirk-thomas** [comment]
Besides the setup.bash I would assume that it would also be impossible to build anything with that kind of customized `cd` command since the since the same code is also in `env.sh` (which can not use `builtin`). Have you tried that or can you give it a try and report back if that is an issue too?

**Comment by baxelrod-bdai** [comment]
I can compile fine with both rosbuild and catkin.  (with custom cd command).  Is this what you wanted me to test?

**Comment by dirk-thomas** [comment]
Can you please post your custom `cd` function?

**Comment by baxelrod-bdai** [comment]
It used to be pretty straightforward like this:

```
function cd {
    builtin cd $@
    ls
}
```

But has now grown to this:

```
export BACK_HISTORY=""
export FORWARD_HISTORY=""

function cd {

    GOPATH=$1
    DOTS=0

    # loop through entire path
    for (( i=0; i<${#1}; i++ ))
    do
        # count dots
        if [[ "${GOPATH:$i:1}" == "." ]]
        then
            let "DOTS+=1"
        else
            break
        fi
    done

    if [[ $DOTS -gt 2 ]]
    then
        # cut off old dots
        GOPATH=${GOPATH:$DOTS}

        # maybe cut off slash that will be duplicated
        if [[ "${GOPATH:0:1}" == "/" ]]
        then
            GOPATH=${GOPATH:1}
        fi

        # add real up paths: "../"
        for (( i=0; i<$DOTS-1; i++ ))
        do
           GOPATH="../"$GOPATH
        done
    fi

    # for some reason, the above code breaks cd with no parameters
    # going to the home directory, so put it back in
    if [[ ${#GOPATH} -eq 0 ]]
    then
        GOPATH="$HOME"
    fi

    # mimic browser forward and back buttons 
    BACK_HISTORY=$PWD:$BACK_HISTORY
    FORWARD_HISTORY=""

    builtin cd "$GOPATH"
    ls
}

# mimic browser forward and back buttons 
function back {
    DIR=${BACK_HISTORY%%:*}
    if [[ -d "$DIR" ]]
    then
        BACK_HISTORY=${BACK_HISTORY#*:}
        FORWARD_HISTORY=$PWD:$FORWARD_HISTORY
        builtin cd "$DIR"
        ls
    fi
}

# mimic browser forward and back buttons 
function forward {
    DIR=${FORWARD_HISTORY%%:*}
    if [[ -d "$DIR" ]]
    then
        FORWARD_HISTORY=${FORWARD_HISTORY#*:}
        BACK_HISTORY=$PWD:$BACK_HISTORY
        builtin cd "$DIR"
        ls
    fi
}
```

**Comment by dirk-thomas** [comment]
Thanks for pointing it out. I fixed it for bash and zsh.

**Comment by baxelrod-bdai** [comment]
Great! Thanks!
