### ISSUE TITLE
catkin_create_pkg could hint at _EXPORTED_TARGETS

### ISSUE THREAD

**Issue by tkruse** [ros/catkin#548]
The CmakeLists.txt created by catkin_create_pkg contains a lot of help and templates to guide users into writing clean catkin packages.

I suggest adding a small block to encourage users to use the ${catkin_EXPORTED_TARGETS} variable in add_dependencies when using e.g. messages/dynamic_reconfigure from other packages. The help text should IMO explicitly mention message generation and dynamic_reconfigure. possibly it could mention build performance effects, though I am not in favor of that.

**Comment by dirk-thomas** [comment]
Please consider providing a pull request with the information you find suitable and helpful for the users. This might speed up the realization of this ticket.

**Comment by dirk-thomas** [comment]
Moved to ros-infrastructure/catkin_pkg#79.
