### ISSUE TITLE
sbcl dependency not found

### ISSUE THREAD

**Issue by JetForMe** [ros/catkin#549]
I was trying to build ROS from source on Ubuntu 13.04, on BeagleBone Black. Things seemed to be going well until sudo apt-get install -y sbcl, at which point I got:

Package sbcl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  sbcl-source sbcl-doc

I'm not sure how to proceed at this point.

This was during the "rosdep install --from-paths src --ignore-src --rosdistro hydro -y" step of the build instructions. I chose to build the "robot" variant.

Not sure if this is the right place to ask. Hope someone can help. Thanks!

**Comment by tfoote** [comment]
please ask questions on answers.ros.org

**Comment by JetForMe** [comment]
Thanks! I lost track of where I should post. I found an answer there that a simple google search failed to turn up.
