### ISSUE TITLE
broken nose tests

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#554]
catkin currently fails several of its tests. The build farm even shows so but does not show the package as unstable, weird:
http://jenkins.ros.org/job/ros-hydro-catkin_binarydeb_raring_i386/49/consoleFull

**Comment by dirk-thomas** [comment]
The Jenkins job you refer to is for the last release. Since then several changes have been made to the codebase. Before the next release it will be made sure that all unit tests pass.

**Comment by vrabaud** [comment]
promises ...... I'll keep that bug open until then :p (tests also fail in trunk btw).
But that bug report also has one for the farm: the package was not marked as unstable: failing tests should mark a package as unstable on the farm no ?

**Comment by dirk-thomas** [comment]
The job you are referring to is not a _devel_ job. Only those mark the build as _unstable_ and send notification emails. The _binarydeb_ are not supposed to do this in the first place.

**Comment by tfoote** [comment]
We would like to turn on tests for debbuilds. Right now we ignore all test results.  If we ever get to a maturity level we will change it such that debs do not get generated if the tests fail.
