### ISSUE TITLE
add bin/* to the scripts in setup.py

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#555]
Just not sure whether it was a decision to not include those (if not, that means they do not belong to the pip install then ?)

**Comment by dirk-thomas** [comment]
Until now  all scripts under bin are being handled by https://github.com/ros/catkin/blob/groovy-devel/bin/CMakeLists.txt.

Changing the scripts to be installed via the setup.py file is simple but only makes sense when the package can be pip-installed. But I am pretty sure that would not be the only files missing from a pip-based installation. I don't think that a pip-based installation is actually feasible (without significant extra effort).

**Comment by vrabaud** [comment]
Right, all the cmake folders would have to be copied too in some place understandable by CMAKE_PREFIX_PATH. Somehow I thought catkin was still pip-installable. Closing then.
