### ISSUE TITLE
move eigen CMake files to package cmake_modules

### ISSUE THREAD

**Issue by vrabaud** [ros/catkin#557]
Not sure if it's normal they have not been moved to:
https://github.com/ros/cmake_modules/

**Comment by wjwwood** [comment]
Duplicate: https://github.com/ros/catkin/issues/492 :smile:

**Comment by vrabaud** [comment]
dammit, it was too old for me to look that far down :) Sorry

**Comment by wjwwood** [comment]
No problem.
