### ISSUE TITLE
catkinConfig.cmake should strip out 'debug' and 'optimized' attributes from catkin_LIBRARIES

### ISSUE THREAD

**Issue by vpradeep07** [ros/catkin#565]
I'm have a catkin package `A` which adds `debug;bar.so;optimized;bar.so` to the cmake variable `${A_LIBRARIES}`, and thus also adds to `${catkin_LIBRARIES}`:

I also have package `B` that has a build depends on `A`.  When `BConfig.cmake` is generated, the `debug` and `optimized` attributes are stipped out of `${B_LIBRARIES}`. This is done is [catkin/cmake/catkin_package.cmake:249-264](https://github.com/ros/catkin/blob/0.5.77/cmake/catkin_package.cmake#L249).

Suppose I add a catkin package `C` which depends on `A` and `B`, in that order.  In catkinConfig.cmake, `A_LIBRARIES` will be added to `catkin_LIBRARIES` with `list_append_deduplicate` at [line 84](https://github.com/ros/catkin/blob/0.5.77/cmake/catkin_config.cmake#L84), and then `B_LIBRARIES` will be added to `catkin_LIBRARIES` with `list_append_deduplicate`.  How the dedeuplicate call will strip out `bar.so` , leaving the words `debug` and `optimized` in `catkin_LIBRARIES`.

Thus, we get:
`catkin_LIBRARIES=debug;optimized;bar.so`

I'm assuming that the solution is for `catkinConfig.cmake` to do something similar to the debug/optimize stripping that's done in `catkin_package.cmake`.

**This is seen on catkin version 0.5.77**

**Comment by wjwwood** [comment]
@vpradeep07 Thanks for the detailed report, can you see if this commit resolves your problem?

https://github.com/ros/catkin/commit/e480140cafcb200402340a0ec125c77379c74ace

I ran into a related problem recently and I think @dirk-thomas fixed the issue you describe here with that commit as well.

Related:

https://github.com/ros/catkin/issues/558
https://github.com/ros/catkin/pull/562

**Comment by dirk-thomas** [comment]
@vpradeep07 Can you please verify that it works for you when checking out catkin from source into your workspace?

**Comment by vpradeep07** [comment]
Hey guys, thanks for looking into this issue.
@dirk-thomas All of the tests that I've been running have been using catkin from source.
@wjwwood As requested, I switched to using catkin [`e480140`](https://github.com/ros/catkin/commit/e480140cafcb200402340a0ec125c77379c74ace), and this does not seem to fix the issue.

As mentioned in the original post, [`catkin_package.cmake,L249-269`](https://github.com/ros/catkin/blob/e480140cafcb200402340a0ec125c77379c74ace/cmake/catkin_package.cmake#L249) is doing special filtering based on the presence of the `debug` and `optimized` flags.  The new changes in [`e480140`](https://github.com/ros/catkin/commit/e480140cafcb200402340a0ec125c77379c74ace) remove duplicates libraries, but will remove all the `debug` flags except one, which is not the intended behavior.  Instead, similar `debug` and `optimize` filtering from `catkin_package.cmake` should be added to [`catkinConfig.cmake.in`](https://github.com/ros/catkin/blob/e480140cafcb200402340a0ec125c77379c74ace/cmake/catkinConfig.cmake.in#L84), before they are added to `catkin_LIBRARIES`.

As an alternative, all `debug` and `optimized` filtering could be removed from everywhere in catkin, and catkin could state that it does not support these types of flags.  There really isn't much gain from half supporting them as it does in it's current state.

**Comment by dirk-thomas** [comment]
Conceptionally catkin should currently do the following:

When ever you build a catkin package it generates a CMake config file as well as a pkg-config file for that package and these only contain the libraries (listed in the package or in any of the dependencies) which equates to the used CMAKE_BUILD_TYPE. The generated files should never include the `debug` / `optimized` flags since they are supposed to be filtered out in `catkin_package()`.

On the other hand the catkin CMake config file only finds all catkin dependencies as components and concatenates their `name_LIBRARIES` variables (while avoiding duplication). Since those variables never contain `debug` / `optimized` flags they don't need to be handled explicitly in the `catkinConfig.cmake` file.

Can you please post a link to your example packages A, B and C and a short description what commands you execute and what the actual and expected result is? May be that will help to understand what exactly fails for you / where catkin does not handle those library types correctly.

**Comment by vpradeep07** [comment]
> When ever you build a catkin package it generates a CMake config file as well as a pkg-config file for that package and these only contain the libraries (listed in the package or in any of the dependencies) which equates to the used CMAKE_BUILD_TYPE. The generated files should never include the debug / optimized flags since they are supposed to be filtered out in catkin_package().

I totally agree. I observe this to be true as well

> On the other hand the catkin CMake config file only finds all catkin dependencies as components and concatenates their name_LIBRARIES variables (while avoiding duplication). Since those variables never contain debug / optimized flags they don't need to be handled explicitly in the catkinConfig.cmake file.

It looks like this is where the misunderstanding is.  For my package `foo`, we are including a cmake extras file with something like the following:

```
cs_export( CFG_EXTRAS foo-extras.cmake  )
```

`foo-extras.cmake` is then manually appending to `foo_LIBRARIES`, and when doing so, also including `debug`/`optimized` flags.

@dirk-thomas From what you've mentioned in the previous post, it sounds like what we are doing is an invalid usage of catkin, since catkin expects `foo_LIBRARIES` to never have `debug`/`optimized` flags in it.  And, moving forward, we should update `foo-extras.cmake` to do the `debug`/`optimized` filtering itself.

As a minor enhancement, it might be nice for catkin to throw a warning or error if it encounters `debug` or `optimized` flags in `name_LIBRARIES`.

> Can you please post a link to your example packages A, B and C 

Unfortunately, I don't have a minimal example on hand at the moment.  I believe we've just addressed the crux of the issue, but if an example will still be useful, I can put one together.

Thank you for your help.

**Comment by dirk-thomas** [comment]
Yes, extending the libraries variable in your CMake extra file is not (yet) supported by catkin. I thought about how the current handling of libraries could be changed to support your use case. The following should fit the described example and be more robust in general:

First the `catkinConfig.cmake` should take the libraries variable of each component and merge them into the `catkin_LIBRARIES` variable - even when they contain build configuration keywords. This can be done by:
- process each components library variable by merging the keyword and the folllowing library name into a single list item
- then appending all items to the `catkin_LIBRARIES` variable using `list_append_deduplicate()`
- undo the merging operation on the final `catkin_LIBRARIES` variable

Some libraries might appear with and without a build configuration keyword (which would technically be a duplicate but is not addressed here).

Second the `catkin_package()` function will perform the same sequence to deduplicate passed in libraries (merge keywords, append with deduplication, undo keyword merge). It will then write the list of libaries (potentially including build configuration keywords) to the generated CMake config file of the package. When generating the `.pc` files it must filter out the build configuration keywords since they do not support that CMake specific concept.

@vpradeep07 I created a pull request (#572) with these changes. It would be great if you could run your previous use case with that branch (_libraries_with_build_configuration_keywords_) of catkin to see if it is now handled correctly (without needing to work around in your extra file but just adding libraries including build configuration keywords as you did it before) and comment with your feedback here.

**Comment by vpradeep07** [comment]
@dirk-thomas I checked out [#575](https://github.com/ros/catkin/pull/572) - 8ec3803, and it fixes the issue in our codebase as well

Thanks for looking into this issue!

**Comment by dirk-thomas** [comment]
Great, thank you for trying and confirming it.

**Comment by bricerebsamen** [comment]
Today, after updating ros-hydro-catkin to 0.5.79-0precise-20140109-2249-+0000, I ran into some build issues with one of my packages. When I use set(CMAKE_BUILD_TYPE Debug) I get CMake warnings:

```
Link library type specifier "optimized" is followed by specifier
  "optimized" instead of a library name.  The first specifier will be
  ignored.
```

followed by undefined symbols linker erros

If I remove the set(CMAKE_BUILD_TYPE Debug) line then it compiles fine.

I also tried with the latest version of catkin from github (it seems to be the same version anyway).

Is it related to this bug?

**Comment by dirk-thomas** [comment]
Can you please describe which packages/repos your have checked out in your workspace in order to reproduce the issue?

**Comment by bricerebsamen** [comment]
it's my own packages and they are not public. Basically, all my packages are built without setting CMAKE_BUILD_TYPE, except for the last one, which depends on all of the others, and which has the CMAKE_BUILD_TYPE set to debug.

I tried to reproduce it in small scale, with a clean workspace with 3 packages A, B, C, where A and B both generate a library, and C would link to those libraries with CMAKE_BUILD_TYPE set to debug. But it did not reproduce my problem...

**Comment by dirk-thomas** [comment]
It will very likely be related to your dependencies. On what other packages do your packages depend on?

**Comment by wjwwood** [comment]
More specifically do you depend on PCL?

Also, could you privately send the output of `${catkin_LIBRARIES}`? You could even anonymize the names of the libraries, it's really the ordering and position of the keywords which matter.

**Comment by bricerebsamen** [comment]
Yes, my package (tmcoloring) does depend on PCL. This is what I get from 'message(${catkin_LIBRARIES})' in tmcoloring's CMakeLists (when set(CMAKE_BUILD_TYPE Debug) is commented out)

```
debug
debug
debug
/opt/ros/hydro/lib/libopencv_core.so
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
debug
optimized
optimized
optimized
/opt/ros/hydro/lib/libopencv_core.so
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
optimized
ladybug_proc
/usr/lib/x86_64-linux-gnu/libdc1394.so
/opt/ros/hydro/lib/libcamera_info_manager.so
/opt/ros/hydro/lib/libtf_conversions.so
/opt/ros/hydro/lib/libkdl_conversions.so
/opt/ros/hydro/lib/libcv_bridge.so
/opt/ros/hydro/lib/libopencv_calib3d.so
/opt/ros/hydro/lib/libopencv_contrib.so
/opt/ros/hydro/lib/libopencv_features2d.so
/opt/ros/hydro/lib/libopencv_flann.so
/opt/ros/hydro/lib/libopencv_gpu.so
/opt/ros/hydro/lib/libopencv_highgui.so
/opt/ros/hydro/lib/libopencv_imgproc.so
/opt/ros/hydro/lib/libopencv_legacy.so
/opt/ros/hydro/lib/libopencv_ml.so
/opt/ros/hydro/lib/libopencv_nonfree.so
/opt/ros/hydro/lib/libopencv_objdetect.so
/opt/ros/hydro/lib/libopencv_photo.so
/opt/ros/hydro/lib/libopencv_stitching.so
/opt/ros/hydro/lib/libopencv_superres.so
/opt/ros/hydro/lib/libopencv_video.so
/opt/ros/hydro/lib/libopencv_videostab.so
/opt/ros/hydro/lib/libopencv_calib3d.so
/opt/ros/hydro/lib/libopencv_contrib.so
/opt/ros/hydro/lib/libopencv_features2d.so
/opt/ros/hydro/lib/libopencv_flann.so
/opt/ros/hydro/lib/libopencv_gpu.so
/opt/ros/hydro/lib/libopencv_highgui.so
/opt/ros/hydro/lib/libopencv_imgproc.so
/opt/ros/hydro/lib/libopencv_legacy.so
/opt/ros/hydro/lib/libopencv_ml.so
/opt/ros/hydro/lib/libopencv_nonfree.so
/opt/ros/hydro/lib/libopencv_objdetect.so
/opt/ros/hydro/lib/libopencv_photo.so
/opt/ros/hydro/lib/libopencv_stitching.so
/opt/ros/hydro/lib/libopencv_superres.so
/opt/ros/hydro/lib/libopencv_video.so
/opt/ros/hydro/lib/libopencv_videostab.so
fastjpeg
/usr/lib/x86_64-linux-gnu/libjpeg.so
log_and_playback
localize
velodyne
/opt/ros/hydro/lib/libvelodyne_rawdata.so
/opt/ros/hydro/lib/libpcl_ros_filters.so
/opt/ros/hydro/lib/libpcl_ros_io.so
/opt/ros/hydro/lib/libpcl_ros_tf.so
/usr/lib/libpcl_sample_consensus.so
/usr/lib/libpcl_sample_consensus.so
/usr/lib/libpcl_filters.so
/usr/lib/libpcl_filters.so
/usr/lib/libpcl_outofcore.so
/usr/lib/libpcl_outofcore.so
/usr/lib/libpcl_features.so
/usr/lib/libpcl_features.so
/usr/lib/libpcl_segmentation.so
/usr/lib/libpcl_segmentation.so
/usr/lib/libpcl_people.so
/usr/lib/libpcl_people.so
/usr/lib/libpcl_registration.so
/usr/lib/libpcl_registration.so
/usr/lib/libpcl_recognition.so
/usr/lib/libpcl_recognition.so
/usr/lib/libpcl_keypoints.so
/usr/lib/libpcl_keypoints.so
/usr/lib/libpcl_surface.so
/usr/lib/libpcl_surface.so
/usr/lib/libpcl_tracking.so
/usr/lib/libpcl_tracking.so
/usr/lib/libpcl_apps.so
/usr/lib/libpcl_apps.so
/usr/lib/libqhull.so
/usr/lib/libqhull.so
/opt/ros/hydro/lib/libdynamic_reconfigure_config_init_mutex.so
/opt/ros/hydro/lib/librosbag.so
/opt/ros/hydro/lib/librosbag_storage.so
/opt/ros/hydro/lib/libtopic_tools.so
/opt/ros/hydro/lib/libvelodyne_input.so
ladybug_playback
/opt/ros/hydro/lib/libnodeletlib.so
/opt/ros/hydro/lib/libbondcpp.so
/usr/lib/x86_64-linux-gnu/libuuid.so
/opt/ros/hydro/lib/libimage_transport.so
/usr/lib/libtinyxml.so
/opt/ros/hydro/lib/libclass_loader.so
/usr/lib/libPocoFoundation.so
/usr/lib/x86_64-linux-gnu/libdl.so
/opt/ros/hydro/lib/libroslib.so
blftrack_tools
/usr/lib/libpcl_common.so
/usr/lib/libpcl_common.so
/usr/lib/libpcl_octree.so
/usr/lib/libpcl_octree.so
/usr/lib/libpcl_io.so
/usr/lib/libpcl_io.so
/usr/lib/libpcl_kdtree.so
/usr/lib/libpcl_kdtree.so
/usr/lib/libpcl_search.so
/usr/lib/libpcl_search.so
/usr/lib/libpcl_visualization.so
/usr/lib/libpcl_visualization.so
/usr/lib/libboost_program_options-mt.so
/usr/lib/libboost_serialization-mt.so
/usr/lib/libOpenNI.so
/usr/lib/libflann_cpp_s.a/usr/lib/libflann_cpp_s.astdr_common/opt/ros/hydro/lib/libtf.so
/opt/ros/hydro/lib/libtf2_ros.so
/opt/ros/hydro/lib/libactionlib.so
/opt/ros/hydro/lib/libmessage_filters.so
/opt/ros/hydro/lib/libtf2.so
eigen_extensions
/usr/lib/libboost_iostreams-mt.so
bag_of_tricksdebug
/opt/ros/hydro/lib/libopencv_core.so
optimized
/opt/ros/hydro/lib/libopencv_core.so
serializable
yaml_cpp
global_coords
/opt/ros/hydro/lib/libroscpp.so
/usr/lib/libboost_signals-mt.so
/usr/lib/libboost_filesystem-mt.so
/opt/ros/hydro/lib/librosconsole.so
/opt/ros/hydro/lib/librosconsole_log4cxx.so
/opt/ros/hydro/lib/librosconsole_backend_interface.so
/usr/lib/liblog4cxx.so
/usr/lib/libboost_regex-mt.so
/opt/ros/hydro/lib/libroscpp_serialization.so
/opt/ros/hydro/lib/librostime.so
/usr/lib/libboost_date_time-mt.so
/usr/lib/libboost_system-mt.so
/usr/lib/libboost_thread-mt.so
/usr/lib/x86_64-linux-gnu/libpthread.so
/opt/ros/hydro/lib/libxmlrpcpp.so
/opt/ros/hydro/lib/libcpp_common.so
/opt/ros/hydro/lib/libconsole_bridge.so
```

**Comment by dirk-thomas** [comment]
I just tried a simple package which uses `pcl_ros` and the content of the `catkin_LIBRARIES` variable looked ok. Have you tried a clean build (remove build/devel folders before invoking catkin_make)? Please provide a minimal example to reproduce the problem.

**Comment by bricerebsamen** [comment]
well I can't reproduce it with a simple set of packages.

However, when I build with catkin at tag 0.5.77 (which was what I had on my system until yesterday), the problem disappears.

here is the catkin_LIBRARIES then (in debug mode)

```
/opt/ros/hydro/lib/libcv_bridge.sodebug/opt/ros/hydro/lib/libopencv_calib3d.so/opt/ros/hydro/lib/libopencv_contrib.so/opt/ros/hydro/lib/libopencv_core.so/opt/ros/hydro/lib/libopencv_features2d.so/opt/ros/hydro/lib/libopencv_flann.so/opt/ros/hydro/lib/libopencv_gpu.so/opt/ros/hydro/lib/libopencv_highgui.so/opt/ros/hydro/lib/libopencv_imgproc.so/opt/ros/hydro/lib/libopencv_legacy.so/opt/ros/hydro/lib/libopencv_ml.so/opt/ros/hydro/lib/libopencv_nonfree.so/opt/ros/hydro/lib/libopencv_objdetect.so/opt/ros/hydro/lib/libopencv_photo.so/opt/ros/hydro/lib/libopencv_stitching.so/opt/ros/hydro/lib/libopencv_superres.so/opt/ros/hydro/lib/libopencv_video.so/opt/ros/hydro/lib/libopencv_videostab.sooptimized/opt/ros/hydro/lib/librosconsole.so/opt/ros/hydro/lib/librosconsole_log4cxx.so/opt/ros/hydro/lib/librosconsole_backend_interface.so/usr/lib/liblog4cxx.so/usr/lib/libboost_regex-mt.so/opt/ros/hydro/lib/libroscpp_serialization.so/opt/ros/hydro/lib/librostime.so/usr/lib/libboost_date_time-mt.so/usr/lib/libboost_system-mt.so/usr/lib/libboost_thread-mt.so/usr/lib/x86_64-linux-gnu/libpthread.so/opt/ros/hydro/lib/libcpp_common.so/opt/ros/hydro/lib/libconsole_bridge.soladybug_proc/usr/lib/x86_64-linux-gnu/libdc1394.so/opt/ros/hydro/lib/libroscpp.so/usr/lib/libboost_signals-mt.so/usr/lib/libboost_filesystem-mt.so/opt/ros/hydro/lib/libxmlrpcpp.so/opt/ros/hydro/lib/libdynamic_reconfigure_config_init_mutex.so/opt/ros/hydro/lib/libnodeletlib.so/opt/ros/hydro/lib/libbondcpp.so/usr/lib/x86_64-linux-gnu/libuuid.so/usr/lib/libtinyxml.so/opt/ros/hydro/lib/libclass_loader.so/usr/lib/libPocoFoundation.so/usr/lib/x86_64-linux-gnu/libdl.so/opt/ros/hydro/lib/libroslib.so/opt/ros/hydro/lib/libcamera_info_manager.so/opt/ros/hydro/lib/libimage_transport.so/opt/ros/hydro/lib/libmessage_filters.so/opt/ros/hydro/lib/libtf.so/opt/ros/hydro/lib/libtf2_ros.so/opt/ros/hydro/lib/libactionlib.so/opt/ros/hydro/lib/libtf2.so/opt/ros/hydro/lib/libtf_conversions.so/opt/ros/hydro/lib/libkdl_conversions.sostdr_commoneigen_extensions/usr/lib/libboost_iostreams-mt.sobag_of_tricksserializableyaml_cppfastjpeg/usr/lib/x86_64-linux-gnu/libjpeg.sovelodyne/usr/lib/libboost_serialization-mt.so/usr/lib/libpcl_common.so/opt/ros/hydro/lib/libvelodyne_rawdata.so/opt/ros/hydro/lib/libpcl_ros_filters.so/opt/ros/hydro/lib/libpcl_ros_io.so/opt/ros/hydro/lib/libpcl_ros_tf.so/usr/lib/libpcl_kdtree.so/usr/lib/libpcl_octree.so/usr/lib/libpcl_search.so/usr/lib/libpcl_io.so/usr/lib/libpcl_sample_consensus.so/usr/lib/libpcl_filters.so/usr/lib/libpcl_visualization.so/usr/lib/libpcl_outofcore.so/usr/lib/libpcl_features.so/usr/lib/libpcl_segmentation.so/usr/lib/libpcl_people.so/usr/lib/libpcl_registration.so/usr/lib/libpcl_recognition.so/usr/lib/libpcl_keypoints.so/usr/lib/libpcl_surface.so/usr/lib/libpcl_tracking.so/usr/lib/libpcl_apps.so/usr/lib/libqhull.so/usr/lib/libOpenNI.so/usr/lib/libflann_cpp_s.a/opt/ros/hydro/lib/librosbag.so/opt/ros/hydro/lib/librosbag_storage.so/usr/lib/libboost_program_options-mt.so/opt/ros/hydro/lib/libtopic_tools.so/opt/ros/hydro/lib/libvelodyne_input.solog_and_playbacklocalizeglobal_coordsladybug_playbackblftrack_tools
```

using git bisect on catkin, I found that commit a71dfdb9a52dfcbe1dada6b10019404e2235bb7c contained the problem

**Comment by dirk-thomas** [comment]
Without an example I am not able to track down the problem since it does not happen for any other package in desktop-full in Hydro. Please consider stripping down your package into a form which can be shared.

**Comment by vpradeep07** [comment]
@bricerebsamen Looking at your output from `message(${catkin_LIBRARIES})`, it looks like something is going wrong with how opencv is being added in your CMakeLists.txt.

As a shot in the dark, by any chance are you calling `find_package(OpenCV)` somewhere and then manually adding it to `${catkin_LIBRARIES}`?  Or, maybe are you adding the results of `find_package(OpenCV)` into catkin some other?  Maybe some non-standard usage is somehow short circuiting the build configuration logic?  (This is all pure guesswork on my part, and may be way off base, but it's hard to know without looking at the offending CMake files)

To reiterate the previous comment from @dirk-thomas, it might be worth trying a clean build.  Commit a71dfdb modifies some of the generated cmake files, and thus clearing these might result in different behavior.

**Comment by dirk-thomas** [comment]
It would already help if you would provide your CMakeLists.txt file(s) (and optionally CMake extra files if you have some). If you don't want to share even those publically you might consider sending them by email to me.

**Comment by bricerebsamen** [comment]
Dirk: I sent you some files. I sent it to your willowgarage address, 
hope it's still valid.

I checked where would the OpenCV libs could come from, here are some 
possibilities
- in packages that build a library that need OpenCV, I list OpenCV as 
  DEPENDS in catkin_package()
- and I tarket_link_libraries the built library with OpenCV, e.g.:
  target_link_libraries(${PROJECT_NAME} ${catkin_LIBRARIES} 
  ${OpenCV_LIBRARIES})
- some of my packages also depend on some of the image_proc, 
  image_transport, etc. ros packages that also depend on OpenCV....

**Comment by dirk-thomas** [comment]
With your example files I was able to boil it down to a smaller example where the same problem happens.

**Comment by dirk-thomas** [comment]
@bricerebsamen Can you please checkout catkin from the branch `fix_library_deduplication` (pull request #580) into your workspace and verify that it fixes your problem? It worked for my stripped down workspace but I want to make sure that it also fixes the problem in your unchanged workspace.

**Comment by bricerebsamen** [comment]
yes it fixes it. Thanks

**Comment by dirk-thomas** [comment]
Thanks for testing it so promptly. I will go ahead with the merge and like a release very soon.
