### ISSUE TITLE
env.sh files cannot pass --extend to setup.sh with sh

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#567]
`setup.sh` files have an `--extend` option which prepends the `setup.sh`'s space to the environment rather than setting the environment explicitly. `env.sh` files take arguments, source a `setup.sh` file and then `exec` the arguments. In the case of parallel cmi, the `cmi_env.sh` sources multiple `setup.sh` files before executing the arguments which follow. Usually the arguments to `env.sh` files are commands to be run in the environment which they provide, so something like `make -j4 -l4` or `env`.

When arguments are passed to `env.sh` the `$@` variable is set. Then the `env.sh` file does something like this:

``` sh
. /path/to/setup.sh --extend
```

The `setup.sh` file then uses the `$@` variable to call it other scripts, like the `_setup_util.py` script (simplified):

``` sh
python _setup_util.py $@
```

You would expect the `$@` in the `setup.sh` to have the value `--extend`, but with `sh` (`dash` on linux) instead it has `env` or `make -j4 -l4` which were the arguments passed to `env.sh`. If the `setup.sh` shebang is changed to `#!/usr/bin/env bash` then this problem goes away, or if you are on a system in which `sh` resolves to a shell like `bash` (OS X) then this problem is not present.

The effect is that the writer of the `env.sh` file expects the `setup.sh` file to respect the `--extend` option, but it does not. This is because the Python script called by the `setup.sh` will ignore any arguments which are not `--extend`.

The way I see it we need to accomplish three things:
- We need to be able to call `source /path/to/setup.sh --extend` on the command line
- The `env.sh` needs to be able to source the `setup.sh` with the `--extend` option
- The `env.sh` needs to be able to source the `setup.sh` without the `--extend` option AND have arguments which happen to contain `--extend` in them without triggering the extend behavior in the `setup.sh`

I propose this solution:
- The `_setup_util.py` file only accepts the `--extend` option, and errors if anything else is given
- `env.sh` files should set an environment variable like `SETUP_SH_EXTEND=1` before sourcing `setup.sh` files and unset it after wards
- If `SETUP_SH_EXTEND` is set, the `setup.sh` should pass `--extend` explicitly to the `_setup_util.py` script as an argument, otherwise it should pass `$@` to the `_setup_util.py` script

**Comment by dirk-thomas** [comment]
There is another way to pass arguments to sourced files. You can set the arguments explictly:

```
# save original args for later
_ARGS=$@
# remove all passed in args, resetting $@, $*, $#, $n
shift $#
# set the args for the sourced scripts
set $@=--extend
# the script foo will see "--extend" as its passed in arguments
. foo.sh
```

Can you update your `cmi_env.sh` scripts to use this method for passing arguments when sourcing `setup.sh`?

**Comment by wjwwood** [comment]
Yes, I can try that. That seems like the better solution. Will you still make the `_setup_util.py`'s argument parsing more strict?

**Comment by wjwwood** [comment]
I don't have linux handy, @dirk-thomas can you try this commit:

609a950

**Comment by dirk-thomas** [comment]
The `cmi_env.sh` should also not have `--extend` in the source lines since it does nothing but implies do be effective when read.

**Comment by wjwwood** [comment]
86a89b2 Should address it then.

**Comment by dirk-thomas** [comment]
This is problem in sourced shell scripts in general. The workaround is the right way to address this. Therefore closing this ticket.
