### ISSUE TITLE
setup.py imports foreign packages, makes sourcedeb creation difficult

### ISSUE THREAD

**Issue by ethanrublee** [ros/catkin#57]
When building source debs, python setup files may attempt to import things that aren't installed... This is problematic
unless we install build dependencies when creating source debs...

The main trouble maker is the pattern of importing the `__version__` from the package.  for example here might be a typical error::

```
dh  clean
   dh_testdir
   dh_auto_clean
    python setup.py clean -a
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from genpy import __version__
  File "src/genpy/__init__.py", line 36, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "src/genpy/message.py", line 45, in <module>
    import genmsg
```

**Comment by gerkey** [comment]
No real fix.  Pattern to follow is to parse version from stack.yaml.
