### ISSUE TITLE
Incorrect GTEST_INCLUDE_DIRS

### ISSUE THREAD

**Issue by muratsevim** [ros/catkin#585]
I usually checkout gtest into the workspace as suggested by catkin to compile the tests.
Catkin can find gtest:

```
Found gtest sources under '/Users/murat/catkin_ws/src/gtest': gtests will be built
```

The `GTEST_INCLUDE_DIRS` variable is set to `/Users/murat/catkin_ws/src/gtest/include/gtest`. However, it should be `/Users/murat/catkin_ws/src/gtest/include` or both. Otherwise `#include <gtest/gtest.h>` does not work which is how most ros libraries include gtest.

I am using Hydro on OSX 10.9 and gtest 1.7.0.

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem. The issue has been fixed on the _indigo-devel_ branch for now. Since we just released catkin the next release might take a while but then it will be backported for hydro.

**Comment by muratsevim** [comment]
Thanks. Manually applying the fix worked for me.

**Comment by dirk-thomas** [comment]
Thank you for confirming - that is always good to know.
