### ISSUE TITLE
debian creation for rosdistro should take into consideration target debian distros

### ISSUE THREAD

**Issue by ethanrublee** [ros/catkin#59]

**Comment by tfoote** [comment]
I've fixed the script to pull the right versions now.  There's an update where 3rdparty-debuild/target.yaml now holds REP 3 targets.  I'll switch to using that, and some helper scripts for that too.

**Comment by gerkey** [comment]
The sourcedeb-generating scripts have been updated, but all that code should be audited.  If possible, use a common implementation of the .yaml parsing stuff.

**Comment by tfoote** [comment]
@kwc what will it take to expose the ros/rosdistro parsing in rosdep?

**Comment by dirk-thomas** [comment]
Not current anymore.
