### ISSUE TITLE
Catkin should provide a tool for testing if a rosbuild package can be catkinized

### ISSUE THREAD

**Issue by baxelrod-bdai** [ros/catkin#592]
Before catkinizing your package(s), you need to check if all dependencies are catkinized.  For a large stack with many dependencies, this can be lengthy and annoying.  I wrote some small bash script functions to do this for you:

``` bash
# lists packages that this package depends on that are not catkinized.
# you can pass in more than one package.  
# packages in the argument list will not be listed in the output.
function catkin_check_package
{
    for PACK in $@
    do
        DEPACKS=`rospack depends $PACK`
        for DEPACK in $DEPACKS
        do
            CATKIN_PATH=`catkin_find $DEPACK`
            if [ -z "$CATKIN_PATH" ]
            then
                # match word, with either space, or start or end on either side
                REG="(^| )$DEPACK($| )"
                if [[ ! ($@ =~ $REG) ]]
                then
                    echo $DEPACK
                fi
            fi
        done
    done
}

# lists packages that this package stack on that are not catkinized.
function catkin_check_stack
{
    PACKS=`rosstack contents $1`
    echo `catkin_check_package $PACKS`
}
```

**Comment by dirk-thomas** [comment]
Since a bash script is not portable I it not likely to be integrated. Would you consider to write and contribute a Python script with the same functionality?

In Python you would also not call `rospack` / `catkin_find` but use the available API of `rospkg` (and eventually `catkin_pkg`).

**Comment by dirk-thomas** [comment]
I will close this ticket and mark it with "wontfix". If anyone would like to create a tool which provides the requested feature it can be either integrated into `catkin` or even better be packages separately.
