### ISSUE TITLE
Catkin should allow CMake modules to be installed in lib

### ISSUE THREAD

**Issue by thomas-moulard** [ros/catkin#606]
Catkin does not consider CMAKE_MODULE_PATH when it looks for package.

It prevents it from finding CMake modules in `$prefix/lib/$package`.
This is sometimes needed as `share` directory contain architecture independent files only. As `xxxConfig.cmake` is sometimes architecture dependent, it should not be installed there (and should be move to `lib` folder instead).

At `/opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:72` either dropping the NO_MODULE argument or adding the `lib/$package` to the paths should be considered.

**Comment by dirk-thomas** [comment]
The line you referenced is only valid for finding catkin packages. How would the CMake config file of a catkin package ever be in a different location? `catkin` generates the CMake config file automatically for catkin packages and there is no way to override its location. Why should it then look in other locations? Or are you suggesting that the location of the generated CMake config file should be configurable too?

**Comment by thomas-moulard** [comment]
My bad. My mistake was to look for a non-catkin package here. As I got the usual CMake error one gets when the package is not installed I didn't think I was misusing the API.

Closing this one.

**Comment by dirk-thomas** [comment]
No problem. Thanks for closing it.
