### ISSUE TITLE
Advanced bootstrap doc out of date

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#617]
This one: http://docs.ros.org/hydro/api/catkin/html/adv_user_guide/underlay.html

Mostly noticed the web-rosinstall stuff, but in general, this seems like almost total duplication of the [source install instructions](http://wiki.ros.org/hydro/Installation/Source) from the wiki. One of them should probably disappear and reference the other.

**Comment by dirk-thomas** [comment]
Thanks for reporting this.

I just removed the underlay doc (80a9751c1dce1c79905fc83aeaab2f1d3736cabd, 9a5da56c7ecfc456c2cb73124432eaf2fcc482b2) since the content is covered by now by the sibling doc `howto` as well the ROS wiki page for installing from source.
