### ISSUE TITLE
catkin-generate-debians on the eigen repository does not respect --debian_inc option values

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#62]
It just produces 0codename packages.

**Comment by ethanrublee** [comment]
I can't reproduce.

This may be an issue on the hudson workspace side, as in its not correctly pulling the update to tags?

If you run catkin-generate-debian --debian_inc and then cat the debian/changelog you should see the increment.

This command retags, as the granularity of the tags is the upstream version... not the debian incremental numbers.

**Comment by gerkey** [comment]
Appears to be resolved.
