### ISSUE TITLE
Mass bug proposal: architecture_independent tag verification

### ISSUE THREAD

**Issue by cottsay** [ros/catkin#623]
With the addition of `noarch` support in bloom (https://github.com/ros-infrastructure/bloom/pull/270), I found a couple of packages that incorrectly marked `architecture_independent` when they were, in fact, not so. These packages were notified and the appropriate `package.xml`s updated.

I'd like to collect thoughts on whether packages should be notified if they SHOULD mark `architecture_independent` but are currently not.

My experimental buildfarm (http://csc.mcs.sdsmt.edu/jenkins/) has the capability to check this, so I could compile a list of packages that are so.

I know the current debian buildfarm is unable to leverage this tag, but this would be a great first step in adding it, and my buildfarm can do so.

Looking for thoughts.

Thanks!

**Comment by dirk-thomas** [comment]
Since the exported tag was not used anywhere until now nobody cared to actually add the tags where appropriate. I think it is perfectly reasonable to fill tickets / PR against packages which should have that tag.

**Comment by cottsay** [comment]
Okay, I'll keep looking into this, then. I'm not sure I have the manpower to open all of the tickets that will be necessary, but I might be able to send some automated E-mails. I'll keep this thread updated.

**Comment by dirk-thomas** [comment]
For similar future tickets please open them under ros/rosdistro. We usually track distro wide tickets there.

**Comment by cottsay** [comment]
Reopened in rosdistro as suggested: https://github.com/ros/rosdistro/issues/4037
