### ISSUE TITLE
Document how to disable "ros-fuerte" prefix for binaries.

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#64]
We now have backports of eigen and protobuf which are prefixed with ros-fuerte because we don't know how to turn this off.  Even though they are intended as pure backport system installations.

**Comment by ethanrublee** [comment]
if backports are built from unmodified source debs, these should be built using a dput of those sources, and not through the gbp repos.

The prefix for ros is currently not optional for generate debian. This can be worked on.

**Comment by tfoote** [comment]
So Brian and I hacked on this today and you can now set the key "Package" in the stack.yaml and that will override the default "ros-ROSDISTRO-CATKIN-PACKAGE-NAME" pattern.  d3ef535f0e13fccf261c69937fc130044470eec5 and equivalent changes in catkin-debs https://github.com/willowgarage/catkin-debs/commit/5f8f8ea381f8816f088dda535900702e0a18b9d6
