### ISSUE TITLE
catkin-generate-debian added a lot of build artifacts to my gbp project

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#65]
https://github.com/wg-debs/gazebo/commit/34bb19ea63b0d9299328c9ddd9643b566d567bcd

I know I didn't clean, but this seems like it should prompt or warn or something.  And possibly work outside the git workspace to avoid this problem.

**Comment by ethanrublee** [comment]
ok... this should be addressed. I'll work on it.

**Comment by dirk-thomas** [comment]
This is not up-to-date anymore since the functionality has been heavily refactored into bloom.
