### ISSUE TITLE
fix quoting of error messages in catkin/cmake/em/order_packages.cmake.em

### ISSUE THREAD

**Issue by rhaschke** [ros/catkin#667]
I get the following order_packages.cmake:
`# generated from catkin/cmake/em/order_packages.cmake.em
message(FATAL_ERROR "Invalid package manifest "/homes/rhaschke/src/ros/rtt/install_isolated/lib/ruby/1.9.1/x86_64-linux/orogen/templates/typekit/package.xml": The manifest contains invalid XML:
not well-formed (invalid token): line 2, column 9")
`

which triggers the cmake error:

`Argument not separated from preceding token by whitespace.`

**Comment by tfoote** [comment]
Note i believe this is an orogen package.xml which is different from a ros one.

**Comment by rhaschke** [comment]
I know, that the package.xml is wrong. However, catkin should better 
deal with catkin-generated exception that contains double-quotes.
These shouldn't be written literally into the order_packages.cmake file.

**Comment by dirk-thomas** [comment]
Could it be that the message you are referring to ("Argument not separated from preceding token by whitespace.") is only a CMake warning and that you are using CMake 2.8.12 (where this warning has been introduced)?

Can you please provide more information to reproduce the problem? What exactly is in your workspace and what command are you invoking?

**Comment by rhaschke** [comment]
Indeed, I'm using cmake 2.8.12.2 on Ubuntu Trusty. The message is only a 
warning - but annoying. It originates from a non-ROS package.xml (attached).
I'm suggesting to fix the error handling routine in catkin, that finally 
generated the error message indicating the malformed package.xml.

Kind regards, Robert

On 29.06.2014 02:43, Dirk Thomas wrote:

> Could it be that the message you are referring to ("Argument not 
> separated from preceding token by whitespace.") is only a CMake 
> warning and that you are using CMake 2.8.12 (where this warning has 
> been introduced)?
> 
> Can you please provide more information to reproduce the problem? What 
> exactly is in your workspace and what command are you invoking?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ros/catkin/issues/667#issuecomment-47442615.

## 

Robert Haschke

---

Dr. Robert Haschke
Faculty of Technology, Neuroinformatics Group, CITEC-3.309
Bielefeld University, 33615 Bielefeld, Germany
phone:  +49-521-106 12122
fax:    +49-521-106 6011
mobile: +49-157-817 365 13
WWW:    www.neuroinformatik.de

**Comment by dirk-thomas** [comment]
You can not attach files when replying to the GitHub issue emails. The quoting has already been addressed in the referenced PR #668.

Please verify if the problem has been fixed with an up-to-date checkout of catkin in your workspace and post your results. If the issue is still there please post the content of the package.xml in question.

**Comment by rhaschke** [comment]
Thanks, the patch fixed the issue.
