### ISSUE TITLE
Documentation: Tutorials on ROS wiki outdated

### ISSUE THREAD

**Issue by NikolausDemmel** [ros/catkin#677]
Something that has come up here: http://answers.ros.org/question/187191/cmakeliststxt-install-python/?answer=187475#post-id-187475

At the least the python section of the tutorials (http://wiki.ros.org/catkin/CMakeLists.txt#Installing_Python_Executable_Scripts) is outdated compared to the doc (http://docs.ros.org/api/catkin/html/howto/format2/installing_python.html).

cc @jack-oquin

**Comment by dirk-thomas** [comment]
Please consider editing the wiki page (if you feel confident enough to do so) and post the diff here for others to check and potentially provide feedback.

**Comment by jack-oquin** [comment]
I edited the wiki entry. Please close if it looks correct to you.

**Comment by dirk-thomas** [comment]
The change in question: http://wiki.ros.org/action/diff/catkin/CMakeLists.txt?action=diff&rev1=69&rev2=70

LGTM +1, Thanks @jack-oquin for editing it.

@NikolausDemmel is that what you expected?

**Comment by NikolausDemmel** [comment]
Thanks @jack-oquin. I added a link to the docs from the wiki page, since they are more thorough and include info on installing modules.
