### ISSUE TITLE
Ros Python Talker.py - "queue size error"

### ISSUE THREAD

**Issue by soulslicer** [ros/catkin#679]
Got the following error:

```
pub = rospy.Publisher('chatter', String, queue_size=10)
TypeError: __init__() got an unexpected keyword argument 'queue_size'
```

I installed Groovy as per the instructions without a hitch, and followed the python tutorial. It seems there is some error with the tutorial, or there is some newer API that works with groovy ?

**Comment by jbohren** [comment]
First, this is the wrong place to ask these questions. Catkin is the buildtool used by ros and does not contain the ROS python implementation. Second, questions like this should be asked on http://answers.ros.org

**Comment by dirk-thomas** [comment]
@soulslicer When you post your question an answers.ros.org please make sure to include more information. E.g. a link to the exact tutorial you followed.
