### ISSUE TITLE
library order from catkin_package() is not preserved

### ISSUE THREAD

**Issue by trainman419** [ros/catkin#683]
In my online_learning package, I call catkin_package with two libraries. online_learning_core depends on online_learning_pcd_serializer, so I list it first:

```
catkin_package(
  INCLUDE_DIRS include
  LIBRARIES ${PROJECT_NAME}_core online_learning_pcd_serializer
)
```

When linking against this package from another package, the library order is swapped for some reason:

The `online_learning_LIBRARIES` variable appears to be set correctly: `online_learning_core;online_learning_pcd_serializer`

But the libraries are passed to the linker in the wrong order:

```
/usr/bin/c++     -Wno-deprecated -O2 -g     CMakeFiles/find_large_objects.dir/src/program/find_large_objects.cpp.o  -o /home/hendrix/hydro/junior/devel/lib/classification/find_large_objects -rdynamic /home/hendrix/hydro/junior/devel/lib/libonline_learning_pcd_serializer.so /home/hendrix/hydro/junior/devel/lib/libonline_learning_core.so
```

I suspect this is related to https://github.com/ros/catkin/pull/546

(some output pruned for clarity and to protect the innocent)

**Comment by dirk-thomas** [comment]
Please provide a link to a repo / workspace configuration which allows to easily reproduce the problem.

**Comment by wjwwood** [comment]
It seems to me that if this is related to #546, then #546 should have fixed it too. There is nothing that I can see in `list_append_deduplicate` which would cause the order to change. Maybe we are still using `list_append_unique` in some place where it causes the same issue as described in #546.

**Comment by trainman419** [comment]
I'm working on a private repository, so I'm not allowed to provide the full source code.

I was linking online_learning_pcd_serializer against online_learning_core:

```
target_link_libraries(online_learning_pcd_serializer ${PROJECT_NAME}_core)
```

I think this was causing cmake to assume that the library dependency was in the opposite order, so it was trying to list the targets in the appropriate order.

Removing this linking fixed my problem. (it turned out that it wasn't necessary).
