### ISSUE TITLE
setup.sh requires writable /tmp

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#685]
The scenario is when running a script as part of a udev `PROGRAM=""`, for example as directed here:

http://wiki.ros.org/hokuyo_node#Using_udev_to_Give_Hokuyos_Consistent_Device_Names

udev can execute this in advance of `/tmp` being writable, which causes setup.sh to fail. See: http://stackoverflow.com/questions/7163935/udev-device-connected-at-boot-time

Possible resolution could be to fall back on `/run/shm` when writing to `/tmp` fails.

Alternatively, eliminate the path from the `mktemp` call and let it [do the right thing](http://unixhelp.ed.ac.uk/CGI/man-cgi?mktemp), or be overridden by a user setting the TMPDIR env var.

**Comment by dirk-thomas** [comment]
Am I right to assume that you have this error message in your log files then (https://github.com/ros/catkin/blob/01dc3c37b2cd7a79c53407c86e1be55c8ade4d3d/cmake/templates/setup.sh.in#L49):

```
Could not create temporary file: /tmp/setup.sh.XXXXXXXXXX
```

If that is the case we could easily try multiple fallbacks in that conditional block. Can you please try the following patch and confirm that it solves the problem for you: 7e40af5db0b979004d6ded22fbd4bea288e48e21

Which ROS distro do you expect the improvement for: is _Indigo_ sufficient or do you need this for _Hydro_ too?

**Comment by mikepurvis** [comment]
Thanks Dirk, will give that a try. Hydro would be great, but not strictly necessary— we can patch around it by putting a `udevadm trigger` in `/etc/rc.local`.

We're moving our production robots to Indigo in the next month or two anyway.

**Comment by mikepurvis** [comment]
Okay, yes, this fix works for us on Ubuntu 12.04. Thanks!

EDIT: Hmm... seems to still be intermittent, wondering if there's a race condition here. Now investigating further...

**Comment by mikepurvis** [comment]
Okay, I've been looking into this, and there's still some kind of a shell race condition— we're going to abandon naming the devices by serial number for the moment, as I'm unable to commit any more time to it.

Someone else is welcome to pick this up in the future.
