### ISSUE TITLE
sh emulation in setup.zsh breaks my zsh config

### ISSUE THREAD

**Issue by de-vri-es** [ros/catkin#686]
The `emulate sh` in setup.zsh breaks something in my zsh config.  I think it's something in my prompt since I get an error message at every prompt. I haven't pinpointed the problem though because I have a rather large configuration, and removing the `emulate sh` fixed the problem for me.

Is there a reason for the `emulate sh`? If there is I can dig and find out what exactly is conflicting, but it seems likely than most sh code will work without modification in zsh, without having zsh emulate sh.

**Comment by dirk-thomas** [comment]
`emulate sh` is currently required since otherwise the called `sh` code will not work correctly in `zsh`. E.g. `zsh` does not honor the `IFS` which is used in _for_ loops.

Since it reset the emulate mode afterwards (a30121998599424367fd19a591e17c904691b903) I don't see how that would conflict with your zsh configuration. It might be worth to track down what exactly conflicts for you since it can't be changed in `catkin` easily.

**Comment by de-vri-es** [comment]
Alright, I will dig to find the exact problem and try to provide a minimal broken zshrc.

**Comment by de-vri-es** [comment]
I found the problem. Either `emulate sh` or `emulate zsh` enables the nomatch option which I specifically disabled in my zshrc. Although I can plate around this specific issue, it is not nice to change options someone set in their zshrc or to require that setup.zsh is sourced before you set your own options.

`emulate -L sh` inside a function is truly temporary and doesn't affect global options. So this would be much nicer:

```
_catkin_source_setup() {
    emulate -L sh
    source "$_CATKIN_SETUP_DIR/setup.sh"
}
_catkin_source_setup
```

**Comment by dirk-thomas** [comment]
It looks like we were depending on `emulate sh` before but as of a0d699a08f10424adad38eee25673c9a66120ec4 we are not using the `IFS` anymore. So removing the emulate lines should work fine.

I created a new PR for it: #692
@de-vri-es Thank you for your effort - you were right in the first place - just removing the emulate lines still works.

**Comment by de-vri-es** [comment]
Awesome, thanks.

**Comment by Ram-Z** [comment]
This breaks it for my setup. I have the zsh option `noclobber` set which doesn't allow truncating a file when redirecting to it.

```
/opt/ros/indigo/setup.sh:52: file exists: /tmp/setup.sh.ksO4Uv1fen
Failed to run '"/opt/ros/indigo/_setup_util.py" ': return code 1
```

PR following.
