### ISSUE TITLE
removing a previously released version

### ISSUE THREAD

**Issue by isucan** [ros/catkin#69]
It should be possible to somehow remove a previously released version. For example, if I am trying to release ompl 0.9.6 a second time, after the first attempt included erroneous content (which was actually not corresponding to version 0.9.6, but an earlier one), the build system complains that the source code is different. This makes sense, but I should be able to somehow delete the .orig.tar.gz file.

{{{
File "pool/main/r/ros-fuerte-ompl/ros-fuerte-ompl_0.9.6.orig.tar.gz" is already registered with different checksums!
md5 expected: eff4acd0bc368bf327d0704cb32a7bea, got: cfdd6a3196b6bb785adbe37c6229920b
sha1 expected: 1bfe5ecaf527266ddd80fc2d0816d3c63c5ce5f5, got: d8c0c78cd2cf205119f00c98c681185031fcdff7
sha256 expected: 04c19cc2ad0c1484c7164830120c141d6cb353319cc21490bd8a864f7783712f, got: 44f12eecaf415786997c8d042d2fc0d139ebc5446234d2d727faef510387ed8b
size expected: 2659233, got: 2659595
}}}

**Comment by tfoote** [comment]
Although it's possible to delete past versions, this whole apt toolchain will not correctly update if you change files out in place.  

If you want to release again you need to use the --debian_inc option to rev the build number.

**Comment by isucan** [comment]
That is fine, except that seems to be insufficient. The orig.tar.gz file md5 sum seems to be generated only per version, not per version+build number, which means that if I make a mistake and release revision X from upstream as version 0.2.5, then I can't release revision Y as version 0.2.5, even though revision Y is in fact version 0.2.5, but I messed up the first time. It seems I then have to release version 0.2.5 (which corresponds to revision Y) as 0.2.6, thus artificially increasing the revision number. Does this make sense?
