### ISSUE TITLE
catkin_make_isolated fails if environment variables contain unicode characters (in Hydro)

### ISSUE THREAD

**Issue by bobsomers** [ros/catkin#695]
I discovered this because my PS1 has some unicode characters in it. When `make -pn` is invoked the environment is dumped and captured, which is why my PS1 caused `catkin_make_isolated` to fail.

**Comment by jbohren** [comment]
Is this also an issue with `catkin build` ( http://catkin-tools.readthedocs.org/ )?

**Comment by dirk-thomas** [comment]
I assume you had the problem when you actually invoked `catkin_make_isolated --install`?

Can you please provide more information: which version of catkin are you using and what is the exact value of your environment variable responsible for the problem? Your current locale might also be relevant: `LANG`, `LANGUAGE`, `*LANG*`...

**Comment by bobsomers** [comment]
Yes, I was installing Hydro from source, via [these instructions](http://wiki.ros.org/hydro/Installation/Source).

I ran into this error specifically on step 2.1.3. My language settings are nothing unusual (en_US.UTF-8).

This is the exact error message when running the command:

```
==> Processing catkin package: 'catkin'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/bsomers/ros_catkin_ws/build_isolated/catkin'
==> make -j8 -l8 in '/home/bsomers/ros_catkin_ws/build_isolated/catkin'
Unhandled exception of type 'UnicodeEncodeError':
Traceback (most recent call last):
  File "./src/catkin/bin/../python/catkin/builder.py", line 847, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "./src/catkin/bin/../python/catkin/builder.py", line 599, in build_package
    destdir=destdir
  File "./src/catkin/bin/../python/catkin/builder.py", line 389, in build_catkin_package
    if has_make_target(build_dir, 'install'):
  File "./src/catkin/bin/../python/catkin/builder.py", line 400, in has_make_target
    output = run_command(['make', '-pn'], path, quiet=True)
  File "./src/catkin/bin/../python/catkin/builder.py", line 219, in run_command
    out.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u23a7' in position 18: ordinal not in range(128)
<== Failed to process package 'catkin': 
  'ascii' codec can't encode character u'\u23a7' in position 18: ordinal not in range(128)
Command failed, exiting.
```

I inserted some debug prints into `src/catkin/python/catkin/builder.py` and discovered that it was my PS1 variable that was the culprit. It's set as follows:

```
export PS1='\[\e[1;37m\]⎧ \[\e[1;33m\]\@ \[\e[1;35m\]\h \[\e[1;32m\]\w\n\[\e[1;37m\]⎩ \[\e[1;36m\]\u \[\e[1;37m\]\$ \[\e[0m\]'
```

Specifically the ⎧ character is where it died.

**Comment by wjwwood** [comment]
Relevant code: https://github.com/ros/catkin/blob/groovy-devel/python/catkin/builder.py#L203-219

**Comment by wjwwood** [comment]
I wonder if that character is outside of `utf8`? We seem to be doing some checking related to unicode.

Comparing it with a random other `utf8` character, they seem to have different lengths:

```
>>> a = '⎧'
>>> a
'\xe2\x8e\xa7'
>>> print a
⎧
>>> a.decode('utf-8')
u'\u23a7'
>>> b = 'ß'
>>> b
'\xc3\x9f'
>>> b.decode('utf-8')
u'\xdf'
```

I find these unicode issues to be very frustrating...

**Comment by bobsomers** [comment]
I wouldn't necessarily expect their lengths to match, as UTF-8 is a variable width encoding.

It _should_ be within UTF-8... otherwise I don't know how else my terminal would display it. (My .bashrc is UTF-8 is so is the terminal.)

**Comment by wjwwood** [comment]
@bobsomers you're right, it is utf-8, I'm not sure why this has suddenly become a problem. I'm pretty certain the line that it is failing on was put there to try and address utf-8 problems in the past. I'm not sure what the correct solution is.

**Comment by trainman419** [comment]
It looks like the utf-8 conversion is OK, and the StringIO object is rejecting the unicode characters; probably related to http://stackoverflow.com/questions/1817695/python-how-to-get-stringio-writelines-to-accept-unicode-string

**Comment by dirk-thomas** [comment]
@bobsomers Can you please try it with the latest `catkin` version from the `indigo-devel` branch? The unicode handling has been changed since Hydro and might already fix your problem.

**Comment by bobsomers** [comment]
@dirk-thomas It looks like the problem is fixed in Indigo.

**Comment by dirk-thomas** [comment]
Thank you for confirming that it works with the `indigo-devel` branch.

Since the patch is based on changes made for Python 3 compatibility it is not likely that the necessary changes will be backported to Hydro (since the Python 3 related changes won't be backported for sure). 

Please either remove the unicode characters from your environment before invoking `catkin_make_isolated --install` or use the `indigo-devel` branch. (The second option might not be compatible with all ROS packages built on-top though.) Sorry for the inconvenience.

**Comment by bobsomers** [comment]
No worries, the workaround is simple enough. Just check for any unicode characters in your environment variables (`export`) and remove them prior to running `catkin_make_isolated`.
