### ISSUE TITLE
CMake Error: The source directory "/opt" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by CIOMP-leon** [ros/catkin#696]
This error appears When I enter 'mkdir build && cmake ../ && make && sudo make install'. I search the all the directories in /opt but there isn't any cmake files. Did I miss something ?

**Comment by dirk-thomas** [comment]
We never recommend to build directly in `/opt`. But your post does not contain enough information to give you any feedback.

Anyway you should ask questions with more information what exactly you are trying to do on http://answers.ros.org as recommended in the http://wiki.ros.org/Support guidelines.
