### ISSUE TITLE
location of stack.yaml 

### ISSUE THREAD

**Issue by isucan** [ros/catkin#70]
By default the git-catkin-import-upstream script loads stack.yaml from upstream. For 3rdparty packages, there is no need for that stack.yaml to be upstream; it can instead live next to catkin.conf, in the catkin branch. All that takes is to modify  git-catkin-import-upstream to look for the stack.yaml in the secondary location, if it is not found upstream:

begin diff:

41,52c41
< if [ -e $UPSTREAM_CLONE/stack.yaml ]
< then
<     read_stack_yaml $UPSTREAM_CLONE/stack.yaml
< else
<     if [ -e stack.yaml ]
<     then
<   read_stack_yaml stack.yaml
<     else
<   status "stack.yaml not found"
<     fi
< fi
## < 

> read_stack_yaml $UPSTREAM_CLONE/stack.yaml

end diff

**Comment by michaelsdixon** [comment]
I also ran into this issue while trying to release the latest PCL into ROS.  PCL doesn't have an upstream stack.yaml, so we keep its stack.yaml (and other patches) in the ROS-specific github repository.  Unfortunately, this means we can't use "catkin-import-upstream" to merge upstream changes, which is going to make it harder for us to maintain PCL in ROS.  Is this something that might get fixed for Fuerte?

**Comment by dirk-thomas** [comment]
This feature request has been moved to ros/bloom#26
