### ISSUE TITLE
Typical workaround for catkin releases

### ISSUE THREAD

**Issue by cottsay** [ros/catkin#702]
It looks like with the release of Jade, you're now generating RPMs specs. Yay!

Unfortunately, the same workaround [1] that is needed in Ubuntu is needed in Fedora, as well.

Please do the same thing in the `rpm/ros-foo-catkin.spec` files in the following branches:
- `rpm/indigo/catkin`
- `rpm/jade/catkin`

...and then do a release. I'm thrilled that we can do this once and I don't need to keep doing it in the workaround repos for every release!

Thanks,

--scott

[1] https://github.com/ros-gbp/catkin-release/commit/0eb03f03a7098feda6cc6520185a2b97fb5658bd

**Comment by dirk-thomas** [comment]
Can you please point me to the exact files? I only find the template in the `rpm` folder on that branch: https://github.com/ros-gbp/catkin-release/tree/rpm/jade/catkin/rpm

**Comment by cottsay** [comment]
I'm sorry, I should have been more specific. The two changes should be at:
- https://github.com/ros-gbp/catkin-release/blob/rpm/indigo/catkin/rpm/template.spec.em#L32
- https://github.com/ros-gbp/catkin-release/blob/rpm/jade/catkin/rpm/template.spec.em#L32

Thanks, @dirk-thomas!

--scott

**Comment by dirk-thomas** [comment]
Patched:
- https://github.com/ros-gbp/catkin-release/commit/9b35d998c0f2d9a7ad31476874535b7457f4a69c
- https://github.com/ros-gbp/catkin-release/commit/191c5bb0ebe026d177b0f90a100e5636a719038f

I only released a debinc of catkin for Jade (https://github.com/ros/rosdistro/pull/6683). For Indigo that would require a full rebuild (which we just completed) so it will be available for the next release of catkin in Indigo (which might be a month or so ahead).

**Comment by cottsay** [comment]
Thanks much, @dirk-thomas!
