### ISSUE TITLE
add setup-file key to .rosinstall file

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#71]
update the auto generated .rosinstall file to add the key "setup-file: ../setup.sh"

**Comment by tfoote** [comment]
I did it already with  18e2d3bd839f6aa825f1e620671bcfb0cc0eeb26 and 471d1d29ec8c74eed316bdc8f543d56d0cc0e638

we're going to update the usage in the future to use setup-file at the top level.

**Comment by tfoote** [comment]
Released in 0.3.20
