### ISSUE TITLE
setup.sh hardcodes /tmp, should honor $TMPDIR

### ISSUE THREAD

**Issue by martinpitt** [ros/catkin#710]
Hello,

in our environment (Ubuntu Snappy), packaged apps cannot currently access `/tmp/`, but the environment sets `$TMPDIR` (and `$TEMPDIR`) to an appropriate place, see https://en.wikipedia.org/wiki/TMPDIR. But catkin's setup.sh.in doesn't honor that, but does

```
 _SETUP_TMP=`mktemp /tmp/setup.sh.XXXXXXXXXX`
```

It should call `mktemp --tmpdir setup.sh.XXXXXXXXXX` instead to honor those.

This is at https://github.com/ros/catkin/blob/indigo-devel/cmake/templates/setup.sh.in#L47 at the time of this writing.

**Comment by wjwwood** [comment]
@martinpitt Thanks for the bug report, but I think we aren't currently using that because that isn't an option on all systems with mkdir, for example on OS X:

```
% mktemp --tmpdir setup.sh.XXXXXXXXXX
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

However, `TMPDIR` is set:

```
% export | grep TMPDIR
TMPDIR=/var/folders/40/ldgcl5kd1msgg5p_hcxbthzr0000gn/T/
```

Perhaps something else might be more cross-platform compatible.
