### ISSUE TITLE
nosetest docs say "unittest" package is needed, package does not exist

### ISSUE THREAD

**Issue by mikeferguson** [ros/catkin#735]
In the catkin noes tests documentation, it is stated that the package.xml must depend on unittest -- but this is neither a ROS package nor a rosdep key (http://docs.ros.org/indigo/api/catkin/html/howto/format1/python_nose_configuration.html) 

Should this be actually be "rosunit"? Or is there no additional depend needed (on my local machine, rosunit was not installed and my tests were running fine)

**Comment by dirk-thomas** [comment]
It seems `unittest` refers to the Python unittest`package which is included in Python by default. Therefore I think the dependency should just be removed. For a plain test`nosetest`is sufficient and provided with`catkin`.

Of course your test might use `rosunit` and then need to also `test_depend` on that. But that is not a requirement for every test.

I removed the mentioned test dependency from the docs in 537e81d290bbd70a4aded9ba5fb8fe4cfb0628fc Thanks for the report.

**Comment by mikeferguson** [comment]
@dirk-thomas thanks for taking a look at it -- I wasn't quite sure what was going on

**Comment by dirk-thomas** [comment]
Filling the ticket was good point. Clearly `unittest` was not a valid dependency.
