### ISSUE TITLE
Detect when already a "catkin build" workspace

### ISSUE THREAD

**Issue by mikepurvis** [ros/catkin#742]
It's a nuisance if you run a long `catkin build`, and then accidentally run `catkin_make`, it destroys the workspace, and catkin build needs to be run from scratch again. I know I could just permanently alias `catkin_make` to something else, but it would be great to have these tools able to detect and not stomp each other.

Suggested behaviour:

```
$ catkin_make
The specified workspace has already been built using catkin build. If you're sure you
want to switch to using catkin_make, first clean the workspace, and then try again:

    rm -rf .catkin_tools .catkin_workspace devel build
    catkin_make
```

**Comment by dirk-thomas** [comment]
That sounds reasonable.

@jbohren @wjwwood Can you please look into this and propose a patch to coexist nicely with `catkin_tools`.

**Comment by wjwwood** [comment]
I opened three pull requests as a first stab at this:

https://github.com/ros-infrastructure/catkin_pkg/pull/122
https://github.com/catkin/catkin_tools/pull/214
https://github.com/ros/catkin/pull/743

@jbohren you'll need to make sure you big pr on catkin_tools continues to respect this patch.

**Comment by jbohren** [comment]
> @jbohren you'll need to make sure you big pr on catkin_tools continues to respect this patch.

Yep. https://github.com/jbohren-forks/catkin_tools/issues/14

**Comment by dirk-thomas** [comment]
The `catkin` and `catkin_pkg` part is done. Only waiting for `catkin_tools` to implement this.

Therefore I will close this ticket. To see if `catkin_tools` supports this please check catkin/catkin_tools#214.
