### ISSUE TITLE
catkin build error: Linking libdefault_plugin.so failed

### ISSUE THREAD

**Issue by jacknlliu** [ros/catkin#744]
I built catkin with the following command:
# ./src/catkin/bin/catkin_make_isolated    --install    -DCMAKE_BUILD_TYPE=Release    --install-space=/opt/ros/jade

but I got the folling error:
Linking CXX shared library /home/usrname/ros_catkin_ws/devel_isolated/rviz/lib/libdefault_plugin.so
[ 98%] Built target default_plugin
Makefile:126: recipe for target 'all' failed
make: **\* [all] Error 2
<== Failed to process package 'rviz': 
  Command '['/opt/ros/jade/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/username/ros_catkin_ws/build_isolated/rviz && /opt/ros/jade/env.sh make -j4 -l4

Any help, please!
Thanks!

**Comment by wjwwood** [comment]
Please post questions like this on answers.ros.org and see wiki.ros.org/Support for guidelines on how to get help. 

You error output doesn't actually include the error, just messages saying there is an error. When you open a question on answers.ros.org you should include more of the error output, what version of ROS you're using, what tutorial you're using if any, and steps to reproduce the error. 

You can comment here with a link to your answers.ros.org question once you open it. 

Thanks.
