### ISSUE TITLE
THREADS_LIBRARY is not provided automatically for test/gtest.cmake

### ISSUE THREAD

**Issue by HannesSommer** [ros/catkin#745]
As https://github.com/ros/catkin/search?utf8=%E2%9C%93&q=THREADS_LIBRARY shows, `tools/threads.cmake` is/was meant to provide `THREADS_LIBRARY`. But it is commented out in `all.cmake` (see https://github.com/ros/catkin/blob/9822bf7894ba85aa392622c1ef83c10c3916846f/cmake/all.cmake#L145).

Currently not including it causes `catkin_add_gtest` to fail to properly link the gtest executable in case threading is enabled for gtest (i.e. `-lpthread` is missing from the linker flags). 

Obvious workarounds in a project's CMakeLists.txt are:

To do

``` cmake
find_package(Threads REQUIRED)
SET(THREADS_LIBRARY ${CMAKE_THREAD_LIBS_INIT})
```

before any catkin_add_gtest 
or

``` cmake
find_package(Threads REQUIRED)
```

and 

``` cmake
target_link_libraries(${TEST_EXECUTABLE} ${CMAKE_THREAD_LIBS_INIT})
```

But reactivating the inclusion of `tools/threads` in `all.cmake` also works (for me) out of the box (tested on Ubuntu 14.04). 

Why is `tools/threads` currently deactivated?
What is the intended way to link gtest executables? 
Is there a different way to include `tools/threads` (on a project basis)?

**Comment by wjwwood** [comment]
`git blame` isn't too useful here, but it was commented in this rather large commit:

https://github.com/ros/catkin/commit/4c7ee4b83642929d26433df88c6ab272a1ca5ccd

I don't know why it was excluded.

**Comment by HannesSommer** [comment]
Hm, yes apparently with this commit some tools got disabled and reactivated over time later. So the question could be rephrased to : what is `tools/threads` reactivation waiting for?

**Comment by dirk-thomas** [comment]
Not every `gtest` uses `Threads`. Therefore `catkin` does not link against it by default.

If your test executable need it please use the CMake commands mentioned above (`find_package` and `target_link_libraries` in order to not rely on the internal usage of `THREADS_LIBRARY`) to ensure to link against it.

**Comment by HannesSommer** [comment]
Thanks for the answer!

To me `gtest` seems to depend itself on `Threads` per default (can only tell for Linux; it can be disabled via cmake variables, though).

But I was facing the problem on a system with precompiled static `gtest`. Sorry for not realizing that unusualness before!

Modern setups are unlikely to run into a problem with `catkin` not taking care of this dependency anymore because the currently recommended way of compiling `gtest` within each project separately (happens very nicely(!) when `test/gtest.cmake` can only find `gtest` source code),  makes `cmake` taking care of this dependency (via `gtest_LIB_DEPENDS`; seems also cleaner to me than being taken care of by `catkin`). 
This renders the approach in `tools/threads.cmake` kind of obsolete for `test/gtest.cmake`.

Additionally that means that not using precompiled statically linked gtest also solves my original problem (that is why I write here so much in detail, for whoever might run into this).

Thanks again, and closed for me.
