### ISSUE TITLE
Invalid package manifest "package.xml"

### ISSUE THREAD

**Issue by nicolasthemmer-aaa** [ros/catkin#748]
Hi!
I found a some entries but none seem to help with my problem. I am currently following the instructions to install turtlebot on this site:
http://wiki.ros.org/turtlebot/Tutorials/indigo/Turtlebot%20Installation
when running following command under point 2.2:
rosdep install --from-paths src -i -y
I get following stack trace:

nicolas@myworkstation:~/rocon$ rosdep install --from-paths src -i -y

ERROR: Rosdep experienced an error: Invalid package manifest "/opt/ros/indigo/share/catkin/package.xml": Error(s) in /opt/ros/indigo/share/catkin/package.xml:
- The manifest must not contain the following tags: depend, build_export_depend, buildtool_export_depend
  Please go to the rosdep page [1] and file a bug report with the stack trace below.
  [1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.2

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 345, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 416, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 87, in find_packages
    package = parse_package(os.path.join(basepath, path))
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 315, in parse_package
    return parse_package_string(f.read(), filename)
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg/package.py", line 448, in parse_package_string
    raise InvalidPackage('Error(s) in %s:%s' % (filename, ''.join(['\n- %s' % e for e in errors])))
InvalidPackage: Invalid package manifest "/opt/ros/indigo/share/catkin/package.xml": Error(s) in /opt/ros/indigo/share/catkin/package.xml:
- The manifest must not contain the following tags: depend, build_export_depend, buildtool_export_depend

There must be a problem with my package.xml file:

```
<?xml version="1.0"?>
<package format="2">
  <name>catkin</name>
  <version>0.6.14</version>
  <description>Low-level build system macros and infrastructure for ROS.</description>
  <maintainer email="dthomas@osrfoundation.org">Dirk Thomas</maintainer>
  <license>BSD</license>

  <url type="website">http://www.ros.org/wiki/catkin</url>
  <url type="bugtracker">https://github.com/ros/catkin/issues</url>
  <url type="repository">https://github.com/ros/catkin</url>

  <author>Troy Straszheim</author>
  <author>Morten Kjaergaard</author>
  <author>Brian Gerkey</author>
  <author>Dirk Thomas</author>

  <buildtool_depend>cmake</buildtool_depend>
  <buildtool_export_depend>cmake</buildtool_export_depend>

  <depend>python-argparse</depend>
  <depend version_gte="0.2.2">python-catkin-pkg</depend>

  <build_depend>python-empy</build_depend>

  <build_export_depend>gtest</build_export_depend>
  <build_export_depend>python-empy</build_export_depend>
  <build_export_depend>python-nose</build_export_depend>

  <test_depend>python-mock</test_depend>
  <test_depend>python-nose</test_depend>

  <export>
    <rosdoc config="rosdoc.yaml"/>
    <architecture_independent/>
  </export>
</package>
```

It seems that the package version 2 might cause the error but I honestly don't know how to fix it. Does anyone have any ideas? 
Thanks in advance!

**Comment by tfoote** [comment]
You appear to be using pip installed packages in /usr/local. Often when people install from pip it gets installed once, but then does not get updated. 

The package.xml of our base dependency is not likely corrupted. Please purge your pip installed ROS tools and use the debian releases.  If that does not work please ask for help on http://answers.ros.org where the community can help you.
