### ISSUE TITLE
catkin_make_isolated: error: unrecognized arguments: --DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by nguillermin** [ros/catkin#750]
Following this tut: http://wiki.ros.org/jade/Installation/OSX/Homebrew/Source

This step `./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release`

results in `catkin_make_isolated: error: unrecognized arguments: --DCMAKE_BUILD_TYPE=Release`

Removing --DCMAKE_BUILD_TYPE allows it to proceed, will update if this breaks anything.

**Comment by dirk-thomas** [comment]
The tutorial only contains a single `-` instead of two as you typed it.
