### ISSUE TITLE
Project-specific clean_test_results targets broken / not created properly

### ISSUE THREAD

**Issue by mathias-luedtke** [ros/catkin#761]
The project-specific clean_test_results targets introduced in 52dbdd500f66a558e9149a33db48e7a75c750473 do not work as expected. As a result cmake throws many "dependency does not exist" errors, (e.g. https://travis-ci.org/ipa320/cob_robots/builds/92377717#L4285).

```
CMake Warning (dev) at /opt/ros/indigo/share/catkin/cmake/test/tests.cmake:148 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
  The dependency target "clean_test_results_cob_bringup" of target
  "_run_tests_cob_bringup_roslaunch-check_robots_cob3-2.xml" does not exist.
Call Stack (most recent call first):
  /opt/ros/indigo/share/roslaunch/cmake/roslaunch-extras.cmake:35 (catkin_run_tests_target)
  cob_robots/cob_bringup/CMakeLists.txt:36 (roslaunch_add_file_check)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

In fact instead of per-project targets a single `clean_test_results_Project` is created.
I guess the target definition (https://github.com/ros/catkin/blob/indigo-devel/cmake/test/tests.cmake#L82) must be moved into the `catkin_run_tests_target` function to get `${PROJECT_NAME}` resolved properly.

**Comment by dirk-thomas** [comment]
Thanks for reporting this. This should be addressed with #762.
