### ISSUE TITLE
find_in_workspace always look in the same place

### ISSUE THREAD

**Issue by asmodehn** [ros/catkin#767]
While diving into how packages are found for this http://answers.ros.org/question/215600/how-can-i-run-roscore-from-python, I stumbled on this : 

``` python
def find_in_workspaces(search_dirs=None, project=None, path=None, _workspaces=get_workspaces(), considered_paths=None, first_matching_workspace_only=False, first_match_only=False, workspace_to_source_spaces=None, source_path_to_packages=None):
    '''
    Find all paths which match the search criteria.
    All workspaces are searched in order.
    Each workspace, each search_in subfolder, the project name and the path are concatenated to define a candidate path.
    If the candidate path exists it is appended to the result list.
    Note: the search might return multiple paths for 'share' from devel- and source-space.

    :param search_dir: The list of subfolders to search in (default contains all valid values: 'bin', 'etc', 'lib', 'libexec', 'share'), ``list``
    :param project: The project name to search for (optional, not possible with the global search_in folders 'bin' and 'lib'), ``str``
    :param path: The path, ``str``
    :param _workspaces: (optional, used for unit tests), the list of workspaces to use.
    :param considered_paths: If not None, function will append all path that were searched
    :param first_matching_workspace_only: if True returns all results found for first workspace with results
    :param first_match_only: if True returns first path found (supercedes first_matching_workspace_only)
    :param workspace_to_source_spaces: the dictionary is populated with mappings from workspaces to source paths, pass in the same dictionary to avoid repeated reading of the catkin marker file
    :param source_path_to_packages: the dictionary is populated with mappings from source paths to packages, pass in the same dictionary to avoid repeated crawling
    :raises ValueError: if search_dirs contains an invalid folder name
    :returns: List of paths
    '''
```

I think this has some unexpected behavior : 

``` python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
>>> acc = 0
>>> def return_acc_list():
...     global acc
...     acc = acc + 1
...     return [acc]
...     
>>> def testfunc( accdef = return_acc_list()):
...     print accdef
...     
>>> testfunc()
[1]
>>> testfunc()
[1]
```

As you can see here return_acc_list is run only one time.

The same happens for `get_workspaces()`.
If one part of the code tries to `find_in_workspace()` with a list of workspace, then there is no way to change that list list later on, since the list of workspace we look for packages in will always be the same.

=> It makes it impossible to dynamically set workspaces ( by setting CMAKE_PREFIX_PATH for example) in python.
=> it s a hidden and possibly non-obvious behavior.

I m not sure if this is a problem or not in daily use, and if this should be fixed or not, but I wanted to let you know as it might bite some people in some corner cases...

**Comment by asmodehn** [comment]
Effectively, it means that workspaces cannot be changed after doing `import rospy`

**Comment by dirk-thomas** [comment]
Having a non-primitive default value is clearly a bug. Also the naming of the keyword argument with a leading underscore (`_workspaces`) seems to be wrong to me. It was introduced in https://github.com/ros/catkin/pull/191/files#diff-4850e70090ee82fa1ed1ba173252c996L17

A simple workaround is to always explicitly pass the keyword argument when invoking the function (`find_in_workspaces(..., _workspaces=get_workspaces()`).

**Comment by dirk-thomas** [comment]
Thank you for the report. PR #768 should address the problem. It would be great if you could try it and report back if it fixes the problem for you.

**Comment by asmodehn** [comment]
PR looks good, but I don't plan to actually try it anytime soon.
I encountered that while probably hacking too deep and was able to get things to work for me already by doing things before importing rospy.
Investigating this is quite time consuming so I don't want to try a different way just yet, but this fix will come in useful in the next iteration :)
Thanks for the fix !
