### ISSUE TITLE
Make catkin functions and macros strict about arguments

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#77]
As we sort out the docs and settle on preferred usage of catkin, we need to clean up our own usage.  E.g., in catkin/CMakeLists.txt, there's this line:

```
install_cmake_config_version(ROS 12.04)
```

As far as I can tell, that second argument is never used within `install_cmake_config_version()`.  I suggest that all catkin functions and macros do something like:

```
if(ARGN)
  message(FATAL_ERROR "unused arguments: ${ARGN}")
endif()
```

It'll be a bit different for functions/macros that do keyword argument parsing, but it should still be possible to hard-fail on unused arguments.

**Comment by mkjaergaard** [comment]
Added arguments check to macros called by the users
2c5b79a
