### ISSUE TITLE
New workspace and $ROS_PACKAGE_PATH

### ISSUE THREAD

**Issue by jeff-delaune** [ros/catkin#773]
If I create the workspace 'catkin_ws1' after a fresh install and source it, $ROS_PACKAGE_PATH is:

/home/myhome/catkin_ws1/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks

If I create a second workspace 'catkin_ws2' after that and source it, $ROS_PACKAGE_PATH becomes:

/home/myhome/catkin_ws2/src:/home/myhome/catkin_ws1/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks

If I delete 'catkin_ws1' for some reason, and recreates it from scratch and source it, $ROS_PACKAGE_PATH remains:

/home/myhome/catkin_ws2/src:/home/myhome/catkin_ws1/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks

and is corrupted as ROS looks for packages inside catkin_ws2 before catkin_ws1.

I used two workspaces to test different versions of a same package. With this issue I wasn't able to launch one of the versions. As a beginner on ROS, I think more attention should be given to the user about workspace chaining. A similar issue seems to have been raised in issue #649

**Comment by dirk-thomas** [comment]
While it could certainly be more visible to the user (as mentioned in #649) and is not trivial to use this is not a bug but intended and documented behavior. If you can imagine an easier way please propose alternative approaches.

A workspace uses all workspaces which are listed in the current environment when it is build the first time as its parent workspaces. Changing them after the fact does not change the previously decided chaining. If you need to change the chain you must clear the downstream workspace and rebuild them from scratch.

Please feel free to provide a PR for #649 but I think this ticket should be closed as a duplicate.

**Comment by jbohren** [comment]
@fejj the catkin_tools beta can override workspace chaining explicitly. Take a look at: http://catkin-tools.readthedocs.org/en/latest/verbs/catkin_config.html#explicitly-specifying-workspace-chaining

**Comment by wjwwood** [comment]
But it doesn't notify you when the workspace needs to be rebuilt because the underlaid workspace was deleted. 

It's certainly a nice feature but I don't think it addresses this problem.

**Comment by jeff-delaune** [comment]
Thanks for the quick responses guys. I'm closing the issue since @dirk-thomas confirmed it was a duplicate of #649.
