### ISSUE TITLE
Provide option to use alternative python

### ISSUE THREAD

**Issue by kyrofa** [ros/catkin#779]
_setup_util.py (among other things) is generated using a template that uses `@PYTHON_EXECUTABLE@` that is replaced with a hard-coded python found at build time. This prevents these files from being relocatable, for example when being packaged for Ubuntu Core.

Catkin should provide an option to use an alternative python for these templates, where for example "/usr/bin/env python" could be provided and used instead of the hard-coded paths.

Contextual discussion from IRC:

```
<kyrofa> dirk-thomas, do you know off the top of your head why _setup_util.py uses an absolute shebang instead of using env?
<dirk-thomas> kyrofa: it embeds the found python executable during the build of catkin, see https://github.com/ros/catkin/blob/indigo-devel/cmake/templates/_setup_util.py.in#L1
<dirk-thomas> that ensures that the same python interpreter is being used as specified during build time
<kyrofa> dirk-thomas, there's a kernel character limit on shebangs that I'm hitting if I use a custom python
<dirk-thomas> e.g. if you select python3 or use a virtual env with a custom python binary
<dirk-thomas> what is the sheband in your case? the debians have "#!/usr/bin/python" which shouldn't hit the limit?
<kyrofa> dirk-thomas, this is packaging for Ubuntu Core, in which case the python is included in the snap and during build is nested far below the home directory
<kyrofa> dirk-thomas, also note, hardcoding the shebang like that also breaks being able to relocate the install after build
<dirk-thomas> indeed, but what would be the alternative? using "/usr/bin/env python" simply doesn't work in other cases.
<dirk-thomas> maybe an option to specify a custom path to override the default would be a good idea?
<kyrofa> Of course, it's not the only thing. The environment hooks do similar things
<kyrofa> Hmm
<kyrofa> Would that be a catkin argument?
<kyrofa> And would one be able to specify "/usr/bin/env python" as an option?
<dirk-thomas> most environment hooks should be relocatable, there are specific feature in the system to allow writing them in a relocatable way, see e.g. https://github.com/ros/ros/blob/dd88e9b13c9e6861af02275ff13ed6dbe34df7e2/core/roslib/env-hooks/10.ros.sh.em#L43
<dirk-thomas> yeah, it would be a catkin CMake option
<dirk-thomas> what ever is passed in can be used instead of `PYTHON_EXECUTABLE`
<kyrofa> dirk-thomas, yeah, that would be a good solution
<kyrofa> dirk-thomas, it's the PYTHON_EXECUTABLE in that exact hook that is the other case I'm fighting here, so the same solution would work, I think?
<dirk-thomas> i would assume so
```

**Comment by dirk-thomas** [comment]
Looking at the code it should already be possible to set a custom executable when invoking CMake by passing `-DPYTHON_EXECUTABLE=/wherever/python`. Can you please try that and comment back if that works for your use case.

**Comment by dirk-thomas** [comment]
Nvm I think I found the part in the CMake provided `FindPythonInterp` which prevent that approach from working...

**Comment by dirk-thomas** [comment]
Actually there are two cases:
- if you build with `catkin_make` or plain CMake you just pass the following as CMake args: `-DPYTHON_EXECUTABLE=/wherever/pythonX`
- if you build with `catkin_make_isolated` you additionally must invoke the script itself with the specific Python interpreter since the tool generates some of the file using its interpreter in the shebang line: `/wherever/pythonX /path/to/catkin_make_isolated ...`

Can you please try that and comment back if that works for your use case.

**Comment by dirk-thomas** [comment]
Since I assume this already works I will close this. Please comment on this to either confirm or if it doesn't work for you.

**Comment by kyrofa** [comment]
Sorry @dirk-thomas, we had a baby this week so I'm a little behind.

My specific use-case is `catkin_make_isolated`. You're right, calling it like so does indeed work, at least for `_setup_util.py`:

```
/custom/python /opt/ros/indigo/bin/catkin_make_isolated --pkg my_package --install --cmake-args -DPYTHON_EXECUTABLE=/custom/python
```

However, I've as yet been unable to get that working with `/usr/bin/env python`, which means it's still not relocatable. Do you have any suggestions for that?

**Comment by dirk-thomas** [comment]
Congratulations :confetti_ball: 

I am not aware of a way to tell Python / setup.py to install Python code but place `/usr/bin/env python` into the shebang line. It always puts an absolute path to a Python interpreter in.

If you find a way to achieve that I am more then happy to use it.

**Comment by kyrofa** [comment]
Heh, thanks!

Alright I'll think on this. Thanks for your time :smiley: .

**Comment by dirk-thomas** [comment]
Np. If you find a way to do it with pure Python I am happy to integrate it into catkin.
