### ISSUE TITLE
using __file__ in __init__.py return the pyc filename in devel/

### ISSUE THREAD

**Issue by asmodehn** [ros/catkin#785]
In `my_pkg/__init__.py`

```
print __file__
```

and then this is printed:

```
roslaunch my_pkg my_pkg.launch --screen
[...]
/<workspace_path>/devel/lib/python2.7/dist-packages/my_pkg/__init__.pyc
```

This is troublesome, because it's not the expected behavior from the python package: 

```
python -tt -m my_pkg
[...]
my_pkg/__init__.py
```

It can also break behavior of dependencies you are using from your `__init__.py` (like a method looking for non python files in a directory inside the package folder for example).

A simple workaround is to move the sensitive code to an external module, and import it from `__init__.py`, yet this shouldn't be needed.

Is there any rationale behind this behavior, or is it something that could/should be fixed ? 
PS: I didn't check other `__*` variables...

**Comment by dirk-thomas** [comment]
I am not sure what the question is here.

Python file (`.py`) are being compiled into `.pyc` files and I think it is commonn that `__file__` will return the file ending in `.pyc`. E.g. `python -c "import em; print(em.__file__)"`

So what are you expecting instead of the behavior you described?

**Comment by asmodehn** [comment]
I think there are a few points that actually bothered me at first, compared with what I get when just using my package from my local source folder : 
1. returns another file in another location.
2. returns the pyc.
3. return an absolute path.

I did a bit of research and :
1) Is the root cause of my problem. Having file return a **init**.pyc file in another place will make python do unexpected things with the code in my original **init**.py...
For example, getting the package directory with 

``` python
import os  
os.path.abspath(os.path.dirname(__file__))
```

won't work (I don't have any other package content in that devel workspace).

2) I tested more in details ( python2 on msys2 - but I'd think it would behave the same on ubuntu ) : 
- Installed package : 

```
$ python2
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import nose
>>> print(nose.__file__)
/usr/lib/python2.7/site-packages/nose/__init__.pyc
```
- Source the first time : 

```
$ git clone https://github.com/nose-devs/nose.git
$ cd nose/
$ python2
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import nose
>>> print(nose.__file__)
nose/__init__.py
```
- Source not the first time

```
$ python2
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import nose
>>> print(nose.__file__)
nose/__init__.pyc
```

So this is not an issue if we keep in mind that the first time we wont get the .pyc file since it doesn't exist (there is no compilation phase before running the code, in python development workflow). 

3) I found that https://mail.python.org/pipermail/python-dev/2010-February/097461.html and I understood why it happens. Actually in python 3.4, `__file__` will always return an absolute path https://bugs.python.org/issue18416. So I think this is overall not an issue.

So the main issue for me is really that we have to go through another `__init__.pyc` 
(in a different folder) . It seems to me that this redirection from the devel workspace to the source package, is not fully transparent. I ll check if something can be done about it when I get some time...

**Comment by dirk-thomas** [comment]
The location of the init file in the devel space is different from all the other files due to the way the devel space works. It avoid to copy the Python code and redirects all imports in order to enable mixing in generated code of e.g. messages.

I am not aware of a way to achieve this fully transparent to the user. Also overriding `__file__` in this file would only work for very few cases.

Maybe you can describe what you use these path information for. Some of it sounds like you are relying on the layout of your source space. Likely after installing a package that layout is different anyway. Maybe there is a better/different way?

You might also just skip the devel space altogether and only use the installed artifacts. Then it will behave as normal Python code.

**Comment by asmodehn** [comment]
I just want to be clear that I currently have a work around in place which is not too bad (using `__file__` from another module and then import it in `__init__.py`), so there is no need to act on this.

But for the sake of sharing knowledge, from what I know, setuptools does it like this : 
https://pythonhosted.org/setuptools/setuptools.html#development-mode

and that is what pip is using :
https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs

**Comment by dirk-thomas** [comment]
Is there anything we can do on this ticket or can it be closed?

**Comment by asmodehn** [comment]
Lets close it.
I m currently experimenting in catkin_pure_python how to improve the way
catkin deals with python packages.
Maybe I ll PR things back to catkin if I get some solid improvements...

**Comment by dirk-thomas** [comment]
In ROS 2 we have made significant changes how to handle "real" Python packages. Maybe that design doc is of interest to you: http://design.ros2.org/articles/ament.html#build-type-amentpython
