### ISSUE TITLE
Address correct CFLAGS for various architectures from the toplevel cmake

### ISSUE THREAD

**Issue by spaghetti-** [ros/catkin#792]
Often when compiling ros packages one forgets the importance of various cflags especially if dealing with less often used architectures such as arm.

I think that it'll be a good idea to add `add_compile_options(-march=native)` in the top level cmake file, and/or emit a warning when we detect a non standard configuration. A warning can also be emitted when a non standard configuration is detected to avoid developers accidentally missing out on performance; for example - missing out on neonv4, cortexa15 optimizations and so on.

**Comment by dirk-thomas** [comment]
I don't think `catkin` should set any of these compiler options for you. It highly depends on the use case what the "correct" flags are. Instead you should pass them in via the command line.

**Comment by spaghetti-** [comment]
Yes that is true. This isn't really a issue so I will close it. Thanks Dirk.

**Comment by NikolausDemmel** [comment]
I just want to add that `catkin_tools` has the `catkin config` command that can be used to persist such flags even if you clean your whole workspace.
