### ISSUE TITLE
Error during run of ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by gunshi** [ros/catkin#795]
I have been following the below link for instructions for installing ROS on OSX
[http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source](url)

When on running the command,

> rosdep install --from-paths src --ignore-src --rosdistro indigo -y

I got the error that many people have reported:
"could not find successful installation of gazebo" (even though I relinked it just to be sure)
 I did a brew install of gazebo(gazebo1), and added in  --skip-geys gazebo at the end and it ran successfully.

Upon further running:

>  ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release

The process stops with the error:

> [ 44%] Built target gazebo_os_joint_state_publisher
> [ 44%] Built target gazebo_os_block_laser
> make: **\* [all] Error 2
> <== Failed to process package 'gazebo_plugins': 
>   Command '['/Users/gunshigupta/ros_catkin_ws/install_isolated/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2
> 
> Reproduce this error by running:
> ==> cd /Users/gunshigupta/ros_catkin_ws/build_isolated/gazebo_plugins && /Users/gunshigupta/ros_catkin_ws/install_isolated/env.sh make -j4 -l4
> 
> Command failed, exiting.

So when i run the command:

> cd /Users/gunshigupta/ros_catkin_ws/build_isolated/gazebo_plugins && /Users/gunshigupta/ros_catkin_ws/install_isolated/env.sh make -j4 -l4

to reproduce the error, I get the errors:

> In file included from /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:19:
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/include/gazebo_plugins/MultiCameraPlugin.h:46:25: error: no
>       type named 'MultiCameraSensorPtr' in namespace 'gazebo::sensors'; did you mean 'MultiCameraSensor'?
>     protected: sensors::MultiCameraSensorPtr parentSensor;
>                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
>                         MultiCameraSensor
> /usr/local/Cellar/gazebo1/1.9.7/include/gazebo-1.9/gazebo/sensors/MultiCameraSensor.hh:40:11: note: 'MultiCameraSensor' declared
>       here
>     class MultiCameraSensor : public Sensor
>           ^
> [ 47%] Linking CXX executable /Users/gunshigupta/ros_catkin_ws/devel_isolated/gazebo_plugins/lib/gazebo_plugins/pub_joint_trajectory_test
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:33:22: error: no member named
>       'reset' in 'gazebo::sensors::MultiCameraSensor'
>   this->parentSensor.reset();
> 
> ``` ^
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:45:22: error: no viable overloaded
>       '='
>   this->parentSensor =
>   ~~~~~~~~~~~~~~~~~~ ^
> /usr/local/Cellar/gazebo1/1.9.7/include/gazebo-1.9/gazebo/sensors/MultiCameraSensor.hh:40:11: note: candidate function
>       (the implicit copy assignment operator) not viable: no known conversion from
>       'shared_ptr<gazebo::sensors::MultiCameraSensor>' to 'gazebo::sensors::MultiCameraSensor &' for 1st argument
>     class MultiCameraSensor : public Sensor
>           ^
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:48:7: error: invalid argument type
>       'sensors::MultiCameraSensor' to unary expression
>   if (!this->parentSensor)
>       ^~~~~~~~~~~~~~~~~~~
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:57:7: error: invalid argument type
>       'sensors::MultiCameraSensor' to unary expression
>   if (!this->parentSensor)
>       ^~~~~~~~~~~~~~~~~~~
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:63:50: error: member reference type
>       'sensors::MultiCameraSensor' is not a pointer; maybe you meant to use '.'?
>   for (unsigned int i = 0; i < this->parentSensor->GetCameraCount(); ++i)
>                                ~~~~~~~~~~~~~~~~~~^~
>                                                  .
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:65:46: error: member reference type
>       'sensors::MultiCameraSensor' is not a pointer; maybe you meant to use '.'?
>     this->camera.push_back(this->parentSensor->GetCamera(i));
>                            ~~~~~~~~~~~~~~~~~~^~
>                                              .
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:73:48: error: member reference type
>       'sensors::MultiCameraSensor' is not a pointer; maybe you meant to use '.'?
>     std::string cameraName = this->parentSensor->GetCamera(i)->GetName();
>                              ~~~~~~~~~~~~~~~~~~^~
>                                                .
> /Users/gunshigupta/ros_catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/src/MultiCameraPlugin.cpp:91:21: error: member reference type
>       'sensors::MultiCameraSensor' is not a pointer; maybe you meant to use '.'?
>   this->parentSensor->SetActive(true);
>   ~~~~~~~~~~~~~~~~~~^~
>                     .
> 9 warnings and 9 errors generated.
> 
> ```

Can anyone help me with what needs to be modified, (and if this is not the right page for this question, then where i should ask for help).
Thanks!

**Comment by dirk-thomas** [comment]
If building a workspace with `catkin` fails it is commonly no the fault of `catkin` but the package failing to build. In this case: `gazebo_plugins` / `gazebo_ros_pkgs`.

You can either open a ticket in that repo or better ask your question on answers.ros.org. Please see http://wiki.ros.org/Support for general guidelines for support.
