### ISSUE TITLE
Fails to build an executable "test" from test.cpp

### ISSUE THREAD

**Issue by AndyZe** [ros/catkin#804]
I recently had this identical issue:
http://answers.ros.org/question/201217/catkin-doesnt-create-test-executable/

There should at least be an error message if there's a naming conflict.

**Comment by dirk-thomas** [comment]
The CMake code mentioned in the question invokes:

```
add_executable(test ...)
```

`catkin` is not involved in this at all so it can't do anything about it. This is a plain CMake problem and has been addressed in CMake 3.0 (https://cmake.org/cmake/help/v3.0/policy/CMP0037.html).
