### ISSUE TITLE
CFG_EXTRAS doesnt support directories

### ISSUE THREAD

**Issue by asmodehn** [ros/catkin#805]
using:

```
catkin_package(
  CFG_EXTRAS
  directory/file.cmake
)
```

and using:

```
catkin_package(
  CFG_EXTRAS
  file.cmake
)
```

will both finally install the file.cmake in the same location.

The directory should not be removed from the path...

I had the issue with this version : https://github.com/asmodehn/catkin_pip/commit/78eaaae58778b5cacdac97f8819eb5a6fbe051e9

**Comment by asmodehn** [comment]
This leads to package requiring these extra to not find them. In my case :

```
CMake Error at /opt/ros/indigo/share/catkin_pip/cmake/catkin_pipConfig.cmake:190 (include):

  include could not find load file:

    /opt/ros/indigo/share/catkin_pip/cmake/test/pytest.cmake
```

**Comment by dirk-thomas** [comment]
While keeping a relative path would be possible the passed filename can also be absolute and then it would be more difficult to still ensure that multiple files don't collide. Therefore `catkin` simplifies the process and uses just the basename of the file.

While I understand your use case I am not convinced that this feature is necessary. The benefit is minimal and the effort to implement this robustly for cases like absolute paths is significant. Maybe it is enough to clarify the documentation (https://github.com/ros/catkin/blob/1b2e47643d782e147c17ecb8134a534a3f3630ef/cmake/catkin_package.cmake#L36-L51)?

**Comment by asmodehn** [comment]
I agree it might not be a really needed feature, I did my implementation this way because it worked in devel space.

So I think what got me there, is the difference between the devel space and the install space...
From what I can recall, in the devel space the relative path is kept. But on install space (when building package) it is removed.

The most important would be to get devel and install space behaving consistently, to avoid surprises.

This issue might need more detailed confirmed behavior, I cant recall exactly all details with all changes I did recently...

**Comment by dirk-thomas** [comment]
devel and install space intentionally behave different. In the case where your extra file is not a template the file is _not_ being copied to the devel space but used from the source space directly. In the install space case the file must be copied though.

I have updated the API documentation to mention that all basenames need to be unique:
- Kinetic b1e138a59b417e9c8e31f6c7272b3d99397d5e17
- Indigo / Jade 0bd2209612b5ee0d37fa46650761433daba70566
