### ISSUE TITLE
how to add or use tfx python module for catkin??

### ISSUE THREAD

**Issue by mudasserzahid** [ros/catkin#814]
Hi 'em trying to run  python script but error is 
rospkg.common,resoursenotfound: tfx
can someone guide me how to get rid off.

**Comment by dirk-thomas** [comment]
Please ask questions on https://answers.ros.org. Please also include enough information for others to understand / reproduce your problem (e.g. what exactly are you doing, any local files you are using, the exact and full output of the error).
