### ISSUE TITLE
how to add or use tfx python module for catkin?

### ISSUE THREAD

**Issue by mudasserzahid** [ros/catkin#815]
i download a repository [](https://github.com/simon0793/pr2_simulation) i am using catkin_workplace when ever i run python code

`python simulation_one_motion_queue.py`

every time error comes tfx not found as;

```
raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: tfx
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/mudasser/p/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks
```

**Comment by dirk-thomas** [comment]
Please do not open duplicate tickets for this (#814). As already mentioned there please ask questions on https://answers.ros.org. Please also include enough information for others to understand / reproduce your problem (e.g. show or link to the Python code which actually raise the exception).

**Comment by mudasserzahid** [comment]
they are not answering this problem you can see i have given enough info

**Comment by dirk-thomas** [comment]
Please post the link to your question on answers.ros.org for people to find it from this link.

From the information provided here I can't see what your code is actually doing hence can't recommend anything to help. So more information / context might help to "attract" answers to your question.

But even if your question hasn't been answered yet cross posting is not appropriate.

**Comment by dirk-thomas** [comment]
Please post the link to your question on answers.ros.org for people to find it from this link.

From the information provided here I can't see what your code is actually doing hence can't recommend anything to help. So more information / context might help to "attract" answers to your question.

But even if your question hasn't been answered yet cross posting is not appropriate.

Please also see the support guidelines in the wiki: http://wiki.ros.org/Support
