### ISSUE TITLE
setup.sh does not prepend LD_LIBRARY_PATH correctly

### ISSUE THREAD

**Issue by dornhege** [ros/catkin#818]
This is about the setup.sh found in, e.g., /opt/ros/indigo. I believe catkin generates that, but if that is another package, I can open this issue there.

The problem is that when sourcing /opt/ros/indigo/setup.bash, the LD_LIBRARY_PATH for indigo is not fully active, i.e., at the first possible place. So, if another workspace overlay was sourced before and one sources /opt/ros/indigo/setup.bash, there is a mixture of workspaces.

Example (where `test` might be left-overs from another workspace that overlays indigo):

```
export LD_LIBRARY_PATH=test:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib
echo $LD_LIBRARY_PATH 
    test:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib
source setup.sh 
echo $LD_LIBRARY_PATH 
    /opt/ros/indigo/lib/x86_64-linux-gnu:test:/opt/ros/indigo/lib
```

So, lib/x86_64_linux-gnu gets prepended, but /opt/ros/indigo/lib does not, possibly because that already was in the path?
I'd expect all folders sourced by setup.sh to be at the front of the path as sourcing setup.sh should activate that workspace ahead of others.

**Comment by miguelprada** [comment]
Hi @dornhege, this is probably related to #809.

I tracked the problem back to appearing whenever `ros-indigo-ompl` package was installed, but never got to open an issue in OMPL to try to figure out where the problem really comes from.

Do you have that package installed on your system? If you do and want to follow through with an issue in [OMPL](https://bitbucket.org/ompl/ompl/), I thing you should link to #809 as well to have a more complete history.

**Comment by dornhege** [comment]
Interesting... after uninstalling ompl I got this:

```
export LD_LIBRARY_PATH=test:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib
echo $LD_LIBRARY_PATH 
    test:/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/ros/indigo/lib
source /opt/ros/indigo/setup.bash 
echo $LD_LIBRARY_PATH 
    test:/opt/ros/indigo/lib
```

This still seems wrong to me. After sourcing /opt/ros/indigo/setup.bash /opt/ros/indigo/lib should be in front. Is this the expected behavior?

**Comment by dornhege** [comment]
I have found one specific thing about ompl. That seems to be the only package that puts libraries in /opt/ros/indigo/lib/x86_64-linux-gnu.

**Comment by dirk-thomas** [comment]
I will reopen #809 and comment there with new information. Therefore I am closing this as a duplicate.
