### ISSUE TITLE
adding meta packages to dependency

### ISSUE THREAD

**Issue by furushchev** [ros/catkin#824]
from catkin version 0.4, build of packages which have dependencies to meta packages fails as follows:

``` bash
Abandoned <<< jsk_pepper_startup                       [ Depends on unknown jobs: naoqi_bridge ]                   
```

(here, package `jsk_pepper_startup` has `run_depend` to `naoqi_bridge`, which is meta package.)

former than 0.4, depending on meta package was equivalent to depending on all packages of stack (whose name is the same as one of meta package).
Did this rule change recently?

**Comment by tfoote** [comment]
This has been true since we defined a metapackages. From the REP: http://www.ros.org/reps/rep-0127.html#metapackage

> Catkin packages must depend directly on the packages they use, not on any metapackages.

**Comment by furushchev** [comment]
@tfoote Thank you very much for clarifying!
