### ISSUE TITLE
Error while building octomap

### ISSUE THREAD

**Issue by jbrookshire** [ros/catkin#826]
Related to: http://answers.ros.org/question/244214/unable-to-install-because-of-missing-ninja/

Solution: 

```
--- catkin/python/catkin/builder.py.orig    2016-09-24 23:22:12.768371606 -0400
+++ catkin/python/catkin/builder.py 2016-09-24 23:22:20.812554961 -0400
@@ -527,11 +527,11 @@
         run_command_colorized(
             make_check_cmake_cmd, build_dir, quiet
         )

     # Run make
-    if not use_ninja:
+    if use_ninja:
         make_executable = 'ninja'
     elif use_nmake:
         make_executable = 'nmake'
     else:
         make_executable = 'make'
```

**Comment by gavanderhoorn** [comment]
This was introduced in #816. I commented [there](https://github.com/ros/catkin/pull/816/files#r80378295) as well.

**Comment by gavanderhoorn** [comment]
@jbrookshire: a PR would resolve this sooner I think.

**Comment by gavanderhoorn** [comment]
What is a bit of a mystery is why the user reporting this in the ROS Answers question only runs into this with OpenCV3.

**Comment by jbrookshire** [comment]
Yes, I had the error with all plain cmake packages (for me: octomap, opencv, and orocos)

**Comment by dirk-thomas** [comment]
This is clearly a bug in the patch adding Ninja support. Thank you for reporting this. I created #827 to fix the logic and will do a patch release.
