### ISSUE TITLE
catkin on windows?

### ISSUE THREAD

**Issue by antithing** [ros/catkin#836]
I am trying to build some code on windows, that was created with ROS on Ubuntu. I have followed these instruction:

https://github.com/ros2/ros2/wiki/Windows-Development-Setup

and have ros installed, but I am still missing catkin, so cannot run the cmake file to build the .sln that I need.

Does catkin support windows?

**Comment by dirk-thomas** [comment]
You seem to mix ROS 1 (which uses catkin) with ROS 2 (which doesn't). Please ask questions on answers.ros.org.
