### ISSUE TITLE
"catkin --force-color build" doesn't work anymore in some terminals

### ISSUE THREAD

**Issue by neumann89** [ros/catkin#837]
Since switching from Ubuntu Trusty/ROS Indigo to Ubuntu Xenial/ROS Kinetic the --force-color option doesn't work anymore in combination with the build command for embedded terminals as used in Eclipse for example.
If I only run "catkin --force-color --test-colors" then I get a colored output.

**Comment by dirk-thomas** [comment]
The `catkin` command is provided by https://github.com/catkin/catkin_tools. Please create the ticket in that repo.

That tool is also ROS version agnostic. So it might help if you can mention the version you were using on Trusty as well as Xenial to narrow down when the behavior changed / regressed.

**Comment by neumann89** [comment]
Oh sorry, created a ticket at the catkin_tools repository now.

**Comment by dirk-thomas** [comment]
No problem, it is kind of confusing and difficult to find the right repo in these cases.
