### ISSUE TITLE
Documentation on CFG_EXTRAS is misleading

### ISSUE THREAD

**Issue by mathias-luedtke** [ros/catkin#845]
The CMake API documentation on `CFG_EXTRAS` ([web version](http://docs.ros.org/kinetic/api/catkin/html/dev_guide/generated_cmake_api.html#catkin-package)) is misleading as it implies that the template extension should be added to the listed filename.
However only the basename with cmake extension must be listed, as the template extension is detected automatically.
Even worse: If the template extension is given in `CFG_EXTRAS` the file will be used [directly without template expansion](https://github.com/ros/catkin/blob/kinetic-devel/cmake/catkin_package.cmake#L363)!

The documentation should cover this auto-detect feature.
In addition files with extensions should be handled properly or trigger an error.

**Comment by dirk-thomas** [comment]
Thank you for bringing this up. Can you please propose an update / addition which clarifies this so that it becomes clear to you how the argument works.

**Comment by dirk-thomas** [comment]
I will close this for now since it is unclear what change would satisfy the request to "clarify" the existing documentation.
