### ISSUE TITLE
Documentation: add how to use catkin_EXPORTED_TARGETS to catkin_add_nosetests

### ISSUE THREAD

**Issue by kopp** [ros/catkin#846]
I would like to see something like

> If you used a message of the current package in the nosetest, make sure to specify the nosetest like this
> <pre>catkin_add_nosetests(test/your_test.py DEPENDENCIES ${${PROJECT_NAME}_EXPORTED_TARGETS})</pre>
> If you used messages from other packages, use
> <pre>catkin_add_nosetests(test/your_test.py DEPENDENCIES ${catkin_EXPORTED_TARGETS})</pre>

in the documentation here:
http://docs.ros.org/indigo/api/catkin/html/howto/format2/python_nose_configuration.html

**Comment by dirk-thomas** [comment]
That sounds like a good improvement of the docs. Please create a pull request with the suggested additions to the file https://github.com/ros/catkin/blob/kinetic-devel/doc/howto/format2/python_nose_configuration.rst It would be good to apply the same change to the `format1` sibling folder (https://github.com/ros/catkin/blob/kinetic-devel/doc/howto/format1/python_nose_configuration.rst).

**Comment by dirk-thomas** [comment]
Closed by #847

**Comment by kopp** [comment]
When will that appear on the web?

**Comment by dirk-thomas** [comment]
The doc jobs are being run every three days. If it doesn't show up by then please comment.

**Comment by kopp** [comment]
It still did not make its way to http://docs.ros.org/indigo/api/catkin/html/howto/format2/python_nose_configuration.html

**Comment by dirk-thomas** [comment]
The patch has been merged to the 'kinetic-devel' branch. Therefore only the kinetic documentation http://docs.ros.org/kinetic/api/catkin/html/howto/format2/python_nose_configuration.html will show this change.

I will backport the patch to the indigo branch before the next indigo release.

**Comment by kopp** [comment]
You're right, sorry; my fault.
Thank you for backporting.
