### ISSUE TITLE
run_tests_TARGET dependency on tests

### ISSUE THREAD

**Issue by EaterOA** [ros/catkin#850]
Invoking `catkin_make run_tests` eventually evaluates to a dependency on the `tests` target ([see this line](https://github.com/ros/catkin/blob/f9cad28fb34bb6a270703753bcd47e9150e57035/cmake/test/tests.cmake#L149)), but invoking `catkin_make run_tests_<project>` doesn't ([see this line](https://github.com/ros/catkin/blob/f9cad28fb34bb6a270703753bcd47e9150e57035/cmake/test/tests.cmake#L137)).

Is there a reason for this? The result is that, for instance, rostest builds the gtest executable when invoking `run_tests` but not for `run_tests_<project>`, because it [adds the dependency to the `tests` target](https://github.com/ros/ros_comm/blob/ed27b59329c38b1325ba0fb1c455a032ccc9efb9/tools/rostest/cmake/rostest-extras.cmake.em#L84). I don't see some other way to work around it from rostest's perspective, so I'm filing an issue here.

**Comment by wjwwood** [comment]
My naive answer (without looking at the code) is that the target `tests` applies to all projects, and therefore the `run_tests` target, which is also for all projects, can depend on it. However, it does not make sense for a project's specific `run_tests` target to depend on `tests` since there is no project specific version of tests.

Instead, each of your test targets (which are aggregated by `run_tests` and ultimately by `tests`) should have a target dependency on anything it uses for its tests (executables, libraries, downloaded or generated test data, etc).

**Comment by wjwwood** [comment]
I'm not sure where the solution belongs (in catkin's run_test code or in rostest). @dirk-thomas will probably have a clearer understanding of the situation than me.

**Comment by EaterOA** [comment]
Apologies, I didn't look at rostest kinetic-devel close enough and didn't realize that add_rostest_gtest already does [add a dependency on `${target}`](https://github.com/ros/ros_comm/blob/ed27b59329c38b1325ba0fb1c455a032ccc9efb9/tools/rostest/cmake/rostest-extras.cmake.em#L86), fixed half a year ago. `run_tests_<project>` will thus also build the gtest. Maybe I'm using an older version or something. In that case, the lines that add a dependency from `tests` can probably be removed.

I guess with this, in theory you don't really need a project-specific `tests` from the user's point of view. If the user is adding a test through `add_rostest`, they can add DEPENDENCIES arguments; if `add_rostest_gtest` or `catkin_add_gtest`, they can use `add_dependencies` on the target.

Feel free to close the issue if there's nothing else to be said.

**Comment by dirk-thomas** [comment]
Since this was addressed in ros/ros_comm#830 I will close the issue for now. Any `rostest` version including and after 1.12.3 (which is available in ROS Kinetic) will have that fix.
