### ISSUE TITLE
Cross-compilation fails because of non-existing absolute paths hardcoded in catkin-generated Config.cmake files

### ISSUE THREAD

**Issue by rojkov** [ros/catkin#851]
Many (most?) packages in ROS (e.g. cpp_common) explicitly set paths to the headers files of their dependencies to their <package_name>Config.cmake files. This breaks cross-compilation when depending packages (e.g. a package depending on cpp_common like gencpp) is built in a separate sysroot. This is the case for the recent Yocto where all packages are built in separate sysroots in order to provide clean build environment for every package.

Consider the following example:

  1. cpp_common depends on Boost and other packages built against cpp_common need to know where to find Boost's headers;
  2. cpp_common does find_package(Boost) and puts the path to its headers to cpp_common.Config.cmake ([1]).
  3. gencpp depends on cpp_common and when being built it has cpp_common installed to its build environment.
  4. But the path to Boost headers was hardcoded to cpp_commonConfig.cmake and it points to the sysroot where cpp_common had been built which may not exist at the moment of gencpp's build.

This is how it looks like in the real generated cpp_commonConfig.cmake file:

```
...

if(NOT "include;/home/rojkov/work/kit/build/tmp-glibc/work/corei7-64-refkit-linux/cpp-common/0.5.7-r0/recipe-sysroot/usr/include;/usr/include " STREQUAL " ")
  set(cpp_common_INCLUDE_DIRS "")
  set(_include_dirs "include;/home/rojkov/work/kit/build/tmp-glibc/work/corei7-64-refkit-linux/cpp-common/0.5.7-r0/recipe-sysroot/usr/include;/usr/include")
  foreach(idir ${_include_dirs})
    if(IS_ABSOLUTE ${idir} AND IS_DIRECTORY ${idir})
      set(include ${idir})
    _list_append_unique(cpp_common_INCLUDE_DIRS ${include})
    elseif("${idir} " STREQUAL "include ")
      get_filename_component(include "${cpp_common_DIR}/../../../include" ABSOLUTE)
      if(NOT IS_DIRECTORY ${include})
        message(FATAL_ERROR "Project 'cpp_common' specifies '${idir}' as an include dir, which is not found.  It does not exist in '${include}'.  Ask the maintainer 'Dirk Thomas <dthomas@osrfoundation.org>' to fix it.")
      endif()
    _list_append_unique(cpp_common_INCLUDE_DIRS ${include})
    else()
      message(WARNING "Project 'cpp_common' specifies '${idir}' as an include dir, which is not found.  It does neither exist as an absolute directory nor in '/opt/ros/indigo/${idir}'.  Ask the maintainer 'Dirk Thomas <dthomas@osrfoundation.org>' to fix it.")
    endif()
  endforeach()
endif()

...

```

The path `/home/rojkov/work/kit/build/tmp-glibc/work/corei7-64-refkit-linux/cpp-common/0.5.7-r0/recipe-sysroot/usr/include` is reported by the standard FindBoost.cmake module at cpp_common's configure-time. This file may not exist and gencpp build fails at the configure phase with the message 

```
Project 'cpp_common' specifies '/home/rojkov/work/kit/build/tmp-glibc/work/corei7-64-refkit-linux/cpp-common/0.5.7-r0/recipe-sysroot/usr/include' as an include dir, which is not found.  It does neither exist as an absolute directory nor in '/opt/ros/indigo/${idir}'.  Ask the maintainer 'Dirk Thomas <dthomas@osrfoundation.org>' to fix it.
```

I guess the proper solution would be not to enumerate include dirs (and library binaries) of dependencies in *Config.cmake files, but to declare a dependency on 3d-party packages, so that the client package could figure out itself the paths to the headers and libs inside its own build environment.

[1] https://github.com/ros/catkin/blob/kinetic-devel/cmake/catkin_package.cmake#L430

**Comment by dirk-thomas** [comment]
For dependencies which are catkin packages this is already done the way you describe it. Only the package name is exported and the CMake config file then calls `find_package()` for it and uses its variables.

For other dependencies this is sadly not possible since there is no strict mapping from the name you `find_package()` to the CMake variables being set. E.g. often the case varies so it can't be done automatically. One workaround is to not rely on exporting dependencies using `DEPENDS` in the `catkin_package()` call but instead write a custom extra file where you call `find_package()` manually and append the content of the CMake variables to the packages CMake variables.

**Comment by rojkov** [comment]
> For other dependencies this is sadly not possible since there is no strict mapping from the name you find_package() to the CMake variables being set. E.g. often the case varies so it can't be done automatically. One workaround is to not rely on exporting dependencies using DEPENDS in the catkin_package() call but instead write a custom extra file where you call find_package() manually and append the content of the CMake variables to the packages CMake variables.

Still catkin itself relies on the mapping for non-catkin based dependencies and simply ignores the cases where the strict mapping don't exist (https://github.com/ros/catkin/blob/kinetic-devel/cmake/catkin_package.cmake#L168). Would the system be less reliable if running this logic was postponed to a leaf package?

**Comment by dirk-thomas** [comment]
As mentioned above you can not use the `catkin_package` argument `DEPENDS`. You can achieve this by writing your own CMake snippet which you then register as an "extra" file (see https://github.com/ros/catkin/blob/6dd0e70efcf6ffec6997794cd3dc15c99cb4f37b/cmake/catkin_package.cmake#L38-L55).

**Comment by dirk-thomas** [comment]
The previous comments already describe how the goal of not embedding absolute path can be achieved.

This there is nothing to be done in the repo for this I will go ahead and close this.
