### ISSUE TITLE
catkin_make_isolated --force_cmake --pkg <pkg_name> runs cmake on all packages, not just specified one

### ISSUE THREAD

**Issue by anuppari** [ros/catkin#852]
As given in the title `catkin_make_isolated --force_cmake --pkg <pkg_name>` runs `cmake` on all packages in the workspace, not just specified one. It should only run cmake on the package(s) specified by the `--pkg` argument.

**Comment by anuppari** [comment]
This seems to also be the case with `catkin_make --force_cmake --pkg <pkg_name>`. It looks like whenever the `--force_cmake` argument is used, all packages are traversed.

**Comment by dirk-thomas** [comment]
The help text of the command line option says:

> Invoke 'make' on specific packages only

It doesn't intend to skip the CMake invocation of other packages.

Also for `catkin_make` that is not even possible since CMake is only invoked a single time covering all packages at once.

**Comment by anuppari** [comment]
So is there a way to run both the CMake and make on only certain packages that are within a shared workspace?

**Comment by dirk-thomas** [comment]
I just tried invoking `catkin_make_isolated --pkg <PKGNAME>` and it only does any operations on the specified package. I assume the help text was copied from `catkin_make` and is inaccurate. Please see #853 for the improved help text.

**Comment by anuppari** [comment]
OK I tried replicating the error with a fresh workspace and two packages, but it seemed to work fine. When I ran that command previously (including the `--force-cmake`), I was getting errors about cmake not being able to find files related to one of the packages which I specifically omitted from the command.

**Comment by dirk-thomas** [comment]
If you didn't build the dependencies before it could be that the error message was telling you that the package you are building couldn't find the information about one dependency. But that is only speculating without the full output.

Since it seems to work now I will close this. Please feel free to comment here if you run into the problem again.
