### ISSUE TITLE
Cannot install catkin in a clean environment

### ISSUE THREAD

**Issue by mirzashah** [ros/catkin#855]
Our automated builds have recently started breaking when attempting to install catkin. Here is the output when attempting to install catkin in a clean 16.04 container:

```
root@51476a8facdb:~# apt-get install catkin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 catkin : Depends: python-catkin-pkg but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by wjwwood** [comment]
Probably this: https://github.com/ros-infrastructure/catkin_pkg/pull/157#issuecomment-278720164

**Comment by tfoote** [comment]
This looks like it's not a clean container. If you're getting the newer stuff we released then you are then also mixing upstream packages with OSRF-provided packages: http://wiki.ros.org/UpstreamPackages

**Comment by mirzashah** [comment]
@tfoote Ah, was not aware of upstream packages. It works if I use the package ```ros-kinetic-catkin```.

Thanks guys!

**Comment by wjwwood** [comment]
Ah, actually then it is this: https://github.com/ros-infrastructure/catkin_pkg/pull/156 and it is intentional.

**Comment by elahia** [comment]
I have the same problem but, ` sudo apt-get install ros-indigo-catkin   `  didn't help!

I'm trying to install rosindigo on chroot.
The main os is ubuntu 16.04 and then I installed 14.04 by chroot.

**Comment by dirk-thomas** [comment]
@elahia You have been cross posting this in at least three locations:
* https://answers.ros.org/question/299739/problem-in-installing-ros-indigo-in-chroot/
* https://github.com/ros-infrastructure/catkin_pkg/issues/230#issuecomment-410678699

This is against the etiquette - please read the support support guidelines of ROS: http://wiki.ros.org/Support
