### ISSUE TITLE
catkin cmake config contradicts ROS support policy

### ISSUE THREAD

**Issue by trainman419** [ros/catkin#860]
The catkin cmake config at https://github.com/ros/catkin/blob/0f2baf16a0d403656b7a773737ebf5a229fc1e13/cmake/templates/pkgConfig.cmake.in#L103-L106 instructs the user to contact the package maintainer by email if something fails, but the [ROS supoprt guidelines](http://wiki.ros.org/Support) advise against directly contacting the maintainer.

Please fix one of these so that lost students and developers don't email me directly.

**Comment by dirk-thomas** [comment]
The support guidelines are certainly what we want users to follow. Please see #861 for a proposed change.

**Comment by trainman419** [comment]
Fixed by #861 .
