### ISSUE TITLE
gtest.cmake adds host-directories to include path in crosscompilation build

### ISSUE THREAD

**Issue by mxsrc** [ros/catkin#868]
In gtest.cmake there are two calls to find_path with NO_CMAKE_FIND_ROOT_PATH set. This causes e.g. the hosts /usr/include to be added to the INCLUDE_DIRECTORIES which will cause cross-compilation builds.

**Comment by dirk-thomas** [comment]
Please provide more information what exactly your are trying to do and how it fails. Please also consider providing a pull request how you think it should be changed.

**Comment by mxsrc** [comment]
I hope the comment and PR clarifies the issue.
