### ISSUE TITLE
catkin_make with devel space fails due to relocation of include paths

### ISSUE THREAD

**Issue by fabianoboril** [ros/catkin#871]
Hi everyone,

recently I encountered an issue that seems to be caused by the patch 0001-relocate-dependency-s-headers-to-current-sysroot.patch for catkin.

When building a project with multiple catkin packages with one recipe it happens that the generated cmakeConfig in the catkin devel space use non-existing include paths. This can break the build if headers are installed by an earlier package during the build process. 

For example, we have package A and package B, that should be build with one single catkin run. In addition, B uses headers from A. During the build process, catkin creates a devel space, in which a cmakeConfig for A is placed. When package B performs a find_package(catkin COMPONENT A) it finds the aforementioned cmakeConfig. However, the include path in this cmakeConfig is not correct, as it is the joined "${root_path}${includepath}", although ${includepath} is already pointing to the correct directory. As a result, cmake throws a warning and the build fails lateron, due to missing headers.

To fix this issue, I am currently not using the relocation patch. However, since the patch fixes other issues, I believe it would be good to include another fix for builds that rely on the catkin devel space. I am using the latest meta-ros with all patches until yesterday.

Best regards,
Fabian

cmake Warning:
CMake Warning at build/DEVEL/share/MyDatatypes/cmake/packageAConfig.cmake:111 (message):
  Project 'MyDatatypes' specifies
  '/data/foboril/yocto/project/build/tmp/sysroots/qemux86-64/data/foboril/yocto/project/build/tmp/work/core2-64-poky-linux/new-project/0.1.20-r0/build/DEVEL/include'
  as an include dir, which is not found.  It does neither exist as an
  absolute directory nor in
  '/data/foboril/yocto/project/build/tmp/work/core2-64-poky-linux/new-project/0.1.20-r0/generated/packageA//data/foboril/yocto/project/build/tmp/sysroots/qemux86-64/data/foboril/yocto/project/build/tmp/work/core2-64-poky-linux/new-project/0.1.20-r0/build/DEVEL/include'.
  Ask the maintainer 'todo <todo@todo.todo>' to fix it.
Call Stack (most recent call first):
  /data/foboril/yocto/project/build/tmp/sysroots/x86_64-linux/opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  generated/packageB/CMakeLists.txt:16 (find_package)

**Comment by dirk-thomas** [comment]
Can you please link to the mentioned patch. Also please provide exact steps to reproduce your case. Otherwise it is almost impossible to give any specific feedback.

**Comment by fabianoboril** [comment]
Sorry. I send this issue by mistake to the wrong place.
