### ISSUE TITLE
catkin_make_isolated crashes if first package does not create setup.*

### ISSUE THREAD

**Issue by awesomebytes** [ros/catkin#874]
Find my output in [this pastebin](https://pastebin.com/iFnU4Ddu). From [this rosinstall](https://pastebin.com/LGvS1JLr).

If I check (as kindly catkin_make_isolated suggests):
```bash
cd /home/nao/ros/ros_navigation_ws/build_isolated/depthimage_to_laserscan && /home/nao/ros/ros_navigation/env.sh cmake /home/nao/ros/ros_navigation_ws/src/depthimage_to_laserscan -DCATKIN_DEVEL_PREFIX=/home/nao/ros/ros_navigation_ws/devel_isolated/depthimage_to_laserscan -DCMAKE_INSTALL_PREFIX=/home/nao/ros/ros_navigation -DCMAKE_BUILD_TYPE=Release -DSETUPTOOLS_ARG_EXTRA= -DSETUPTOOLS_DEB_LAYOUT=OFF -DCMAKE_INCLUDE_PATH=/home/nao/system_deps/include -DCMAKE_LIBRARY_PATH=/home/nao/system_deps/lib -G 'Unix Makefiles'
/home/nao/ros/ros_navigation/env.sh: line 14: /home/nao/ros/ros_navigation/setup.sh: No such file or directory
```

If I just  copy the `setup.bash`,  `setup.sh`,  `setup.zsh`, of any of my other workspaces, then I modify `setup.sh` line:
```
: ${_CATKIN_SETUP_DIR:=/home/nao/ros/ros_navigation}
```
To point at the actual path of the install dir.

And then I can keep compiling. But it's ugly.

**Comment by dirk-thomas** [comment]
I can't reproduce your problem. Can you please provide more information about the exact commands you run, the platform you are on, and the version of involved packages you have installed (e.g. catkin).

**Comment by awesomebytes** [comment]
I'll try to build a docker image with a test. I need a bit of time.

**Comment by dirk-thomas** [comment]
I will close this ticket for now due to no response. Please feel free to comment and the ticket can be reopened if necessary.
