### ISSUE TITLE
setuptools is putting build artifacts in source tree

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#88]
Not sure where, but some part of the build or install is creating `build` subdirectories in the source tree.

**Comment by gerkey** [comment]
An example of this:

```
copying tools/rosmake/src/rosmake/engine.py -> build/lib.linux-x86_64-2.6/rosmake
```

**Comment by dirk-thomas** [comment]
The generated "build" folder of setuptools was moved out into the cmake build folder using "--build-base".
But for the other temporary folders (dist and egg...) setuptools does not allow to customize their location.

**Comment by dirk-thomas** [comment]
The other folders (besides "build" which is now created in buildspace) can not be created elsewhere with setuptools. Use distutils instead.
