### ISSUE TITLE
gtest.cmake assumes system library is a shared lib

### ISSUE THREAD

**Issue by rctoris** [ros/catkin#883]
We had a developer computer that had a pre-built version of gtest installed which catkin correctly found. However, it looks like it's assuming the library is a shared library: https://github.com/ros/catkin/blob/kinetic-devel/cmake/test/gtest.cmake#L166-L168

In our case it wasn't and leads to all kinds of wonky linking error messages. We fixed it by remaking gtest as a shared library but it would be nice if it could support either.

**Comment by dirk-thomas** [comment]
Can you please clarify on which platform you had that problem and how that system was being setup.

Upstream highly recommends not to use a pre-build library but to build `gtest` together with your code. Therefore I don't think the maintainers will spend time supporting a static library. If you could provide a pull request for supporting this use case I would be happy to review it.

**Comment by rctoris** [comment]
This was on Ubuntu 14.04 running indigo. Since catkin currently supports some conditions for this as apposed to no support, I'll look into getting it to check more dynamically.
