### ISSUE TITLE
find_package catkin components twice breaks

### ISSUE THREAD

**Issue by asmodehn** [ros/catkin#886]
Calling `find_package(catkin REQUIRED COMPONENTS pkg1)` and later `find_package(catkin REQUIRED COMPONENTS pkg2)` loses catkin variables content...

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.5)

find_package(catkin REQUIRED COMPONENTS rostest)
message(STATUS "INCLUDES : ${catkin_INCLUDE_DIRS}")
message(STATUS "LIBRARIES : ${catkin_LIBRARIES}")

find_package(catkin REQUIRED COMPONENTS roslint)
message(STATUS "INCLUDES : ${catkin_INCLUDE_DIRS}")
message(STATUS "LIBRARIES : ${catkin_LIBRARIES}")
```

Cmake configuration:
```
alexv@alexv-pc:~/tmp$ source /opt/ros/kinetic/setup.bash 
alexv@alexv-pc:~/tmp$ cmake .
-- Using CATKIN_DEVEL_PREFIX: /home/alexv/tmp/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/alexv/tmp/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.6
-- INCLUDES : /opt/ros/kinetic/include;/usr/include
-- LIBRARIES : /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- INCLUDES : 
-- LIBRARIES : 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alexv/tmp
```

It might come from : https://github.com/ros/catkin/blob/b05cd262f4aa992856d4470cfc2b1f5e52fabefc/cmake/catkinConfig.cmake.in#L48

While it is true that it doesn't make sense to call `find_package(catkin)` twice, it does make sense to find different "components" at different places in the `CMakeLists.txt`

One obvious workaround is to do the _proper cmake way_ : 
`find_package(pkg1)` and `find_package(pkg2)`

However since this "catkin component way" seems to be advised [in](http://wiki.ros.org/catkin/CMakeLists.txt#Why_Are_Catkin_Packages_Specified_as_Components.3F) [many](http://docs.ros.org/kinetic/api/catkin/html/user_guide/find_package.html) [places](https://answers.ros.org/question/48133/whats-the-effect-of-find_packagecatkin-components/), it is probably worth fixing...

**Comment by dirk-thomas** [comment]
This is not a supported use case. I am not aware of any documentation where invoking this more than once is recommended.

I would recommend to either save the content of the variables before invoking it a second time or use `find_package(<pkgname>)` directly.

**Comment by sloretz** [comment]
Hi @asmodehn, thanks for the issue! As mentioned by @dirk-thomas It seems like this won't be fixed. I'll close the issue for now, but feel free to reopen if you feel strongly that it should be worked on.
