### ISSUE TITLE
Error when running catkin_prepare_release

### ISSUE THREAD

**Issue by facontidavide** [ros/catkin#887]
Hi, I am tryint to run catkin_prepare_release after catkin_generate_changelog, but get the following error 

```
  File "/opt/ros/indigo/bin/catkin_prepare_release", line 390, in <module>
    main()
  File "/opt/ros/indigo/bin/catkin_prepare_release", line 269, in main
    if not args.non_interactive and not prompt_continue(fmt("Prepare release of version '@{bf}@{boldon}%s@{boldoff}@{reset}'%s" % (new_version, " (tagged as '@{bf}@{boldon}%s@{boldoff}@{reset}')" % tag_name if args.tag_prefix else '')), default=True):
  File "/opt/ros/indigo/bin/catkin_prepare_release", line 41, in prompt_continue
    response = raw_input(msg)
EOFError
```

Attached there is the changelog (I don't know if it helps).

[package.xml.txt](https://github.com/ros/catkin/files/1264341/package.xml.txt)

[CHANGELOG.rst.txt](https://github.com/ros/catkin/files/1264336/CHANGELOG.rst.txt)

**Comment by dirk-thomas** [comment]
The error happened when expecting the confirmation if the command should proceed. What did you enter on the prompt?

**Comment by facontidavide** [comment]
Misteriously the error disappeared once I reboot the computer. Doh

**Comment by dirk-thomas** [comment]
Based on the fact that `raw_input` might raise `EOFError` I created #888 to catch it just in case.
