### ISSUE TITLE
Implement namespaces in messages/services/actions

### ISSUE THREAD

**Issue by GuiRitter** [ros/catkin#891]
Hi everyone.

I want to be able to define custom messages with custom namespaces. For example. I want to define a message that I could reference in C++ by `project_name::Movement::Generic`. I've seen it's possible to create files inside folders inside the `msg` folder, but upon generation the message becomes `project_name::Generic`, using the same example. This means I can't have any other message with the same name, and I'm forced to add the namespace to the message name, such as `NameSpace1Generic`, `NameSpace2Generic` and so on.

I've tested in Indigo and in Lunar and trying to generate two messages with the same name in different folders result in an CMake error referencing [CMP0002](https://cmake.org/cmake/help/v3.0/policy/CMP0002.html).

I didn't test, but I suppose the same holds for services and actions. Please consider implementing namespaces in these structures.

Thanks in advance.

**Comment by sloretz** [comment]
Hi @GuiRitter, thanks for the ticket. It sounds like all of `project_name` is in a single catkin package. What do you think about moving the messages to their own package called `project_name_movement_msgs`? It moves the namespacing out of the message name.

I think this might fit better on the [genmsg repo](https://github.com/ros/genmsg), so I'll close it here for now. Feel free to reopen.

**Comment by dirk-thomas** [comment]
Implementing support for additional namespacing (beyond the package name) is not likely going to happen since the current `.msg` format doesn't allow adding such meta information and the enhancement is rather small compared to the additional complexity (and potential breakage) in the code generators for every language.

**Comment by GuiRitter** [comment]
Thanks for the suggestion about using separate packages, but I don't think it fits well with my intention.

I wasn't sure where to open this suggestion, and I thought that this was the place because I thought the problem was in the CMake context due to the `add_message_files` macro. Now that I know the problem is the way the messages are defined, I hope one day a new version of it is implemented with namespace support. Should I adapt this issue and open it at the [genmsg repo](https://github.com/ros/genmsg)?

Thanks for all the attention anyway!

**Comment by dirk-thomas** [comment]
> Should I adapt this issue and open it at the [genmsg repo](https://github.com/ros/genmsg)?

Please go ahead and do so. It will be unlikely that the maintainers will work on this enhancement in the future though.
