### ISSUE TITLE
catkin ignores cmake arguments

### ISSUE THREAD

**Issue by lizixroy** [ros/catkin#892]
Guys, when running **catkin_make_isolated**, I needed to pass in cmake argument to let cmake use em.pyc in the site-package folder created by Homebrew:

./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --cmake-args -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/opt/python/libexec/bin/python -DPYTHON_PACKAGES_DIR:FILEPATH=/usr/local/lib/python2.7/site-packages

However, this doesn't seem to work, as you can see below, cmake is still trying to find em.pyc in /Library/Python/2.7/site-packages/em.pyc

==> cmake /Users/roy/ros_catkin_ws/src/catkin -DCATKIN_DEVEL_PREFIX=/Users/roy/ros_catkin_ws/devel_isolated/catkin -DCMAKE_INSTALL_PREFIX=/Users/roy/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/opt/python/libexec/bin/python -DPYTHON_PACKAGES_DIR:FILEPATH=/usr/local/lib/python2.7/site-packages -G Unix Makefiles in '/Users/roy/ros_catkin_ws/build_isolated/catkin'
-- Using CATKIN_DEVEL_PREFIX: /Users/roy/ros_catkin_ws/devel_isolated/catkin
-- Using CMAKE_PREFIX_PATH: 
-- Using PYTHON_EXECUTABLE: /usr/local/opt/python/libexec/bin/python
-- Using default Python package layout
**-- Using empy: /Library/Python/2.7/site-packages/em.pyc**
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /Users/roy/ros_catkin_ws/build_isolated/catkin/test_results
-- Found gtest: gtests will be built
-- nosetests not found, Python tests can not be run (try installing package 'python-nose')
-- catkin 0.7.6
/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Library/Python/2.7/site-packages/em.pyc': [Errno 2] No such file or directory
CMake Error at cmake/safe_execute_process.cmake:11 (message):
  
  execute_process(/Users/roy/ros_catkin_ws/build_isolated/catkin/catkin_generated/env_cached.sh
  "/usr/local/opt/python/libexec/bin/python"
  "/Library/Python/2.7/site-packages/em.pyc" "--raw-errors" "-F"
  "/Users/roy/ros_catkin_ws/build_isolated/catkin/catkin_generated/pkg.develspace.context.pc.py"
  "-o"
  "/Users/roy/ros_catkin_ws/devel_isolated/catkin/lib/pkgconfig/catkin.pc"
  "/Users/roy/ros_catkin_ws/src/catkin/cmake/em/pkg.pc.em") returned error
  code 2
Call Stack (most recent call first):
  cmake/em_expand.cmake:25 (safe_execute_process)
  cmake/catkin_package.cmake:325 (em_expand)
  cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:11 (catkin_package)

-- Configuring incomplete, errors occurred!

Any idea how to fix this issue?

**Comment by dirk-thomas** [comment]
I don't think `catkin` is ignoring the passed CMake arguments. You can check the CMake cache file to confirm that the value was passed correctly. It is more likely that you need different parameters to achieve what you want to.

You might want to try importing `em` in an interactive Python shell to check from where it was loaded. And then e.g. try to set a different `PYTHONPATH`. Once you have it working in a pure Python shell it should be straight forward to apply the same arguments / set up the same environment using catkin.

**Comment by lizixroy** [comment]
Thanks Dirk for the reply. 

I seems that I can correctly import em in the Python shell:

Roys-iMac:~ roy$ python
Python 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
import em
em.__file__
'/usr/local/lib/python2.7/site-packages/em.pyc'

As you can see here, em is imported from /usr/local/lib/python2.7/site-packages/em.pyc.

I am not sure why cmake is trying to get em from **/Library/Python/2.7/site-packages/em.pyc**

Any idea how to configure catkin so that it uses em from a custom path instead of the system path?

**Comment by lizixroy** [comment]
It seems that in every package under build_isolated, the CMakeCache.txt has the wrong **//Empy script**
It's always pointing to the system site-package folder, and whereas I need this:
**EMPY_SCRIPT:STRING=/usr/local/lib/python2.7/site-packages/em.pyc**

I'm not very familiar with cmake yet, any idea how these CMakeCache.txt files are generated in the first place and how I can change the path when generating them?

**Comment by lizixroy** [comment]
Problem solved now, the problem is that when I first set up my catkin workspace using the instructions in here (http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source), I was still using a system version of Python and for somehow all CMakeLists for packages I was building tried to use em.pyc in the site-package folder of the system Python instead of the custom Python installed with Homebrew.

I solved this problem by removing my workspace and regenerating it with custom Python configured properly.

Closing.

**Comment by Shushman** [comment]
Could you specify how you regenerated the workspace with custom Python? I have `python2` installed via Homebrew and `pip2` linked to it (with which I installed `empy`), and I also used `pip2` to install `catkin_tools`.

But when I do `catkin build` on a new workspace, it is still trying to find `em` in `/Library/Python/2.7/site-packages/em.pyc` RATHER than `/usr/local/lib/python2.7/site-packages`

Did you have to set any variables for this new workspace that you regenerated? If so, where and how?

**Comment by lizixroy** [comment]
Sorry for the delayed response. Are you using home brew Python as the default on your system? Just because Python is installed via Homebrew it doesn’t mean that it’s used as default. 

What’s the output you get from running ‘which python’?

**Comment by Shushman** [comment]
No worries, thanks for following up.

Hmm I do get `usr/bin/python`, that could be it! What should I do?

**Comment by lizixroy** [comment]
Take a look at this: https://stackoverflow.com/questions/5157678/python-homebrew-by-default

Let me know if this works for you.
