### ISSUE TITLE
Support for OPTIONAL_COMPONENTS in find_package(catkin ..)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros/catkin#894]
There is support for optional components being specified in the call to `find_package(.. COMPONENTS .. OPTIONAL_COMPONENTS ..)` for some time now in CMake.

Trying to use that with `find_package(catkin ..)` does not seem to work (ros-planning/moveit#612), and from bug reports for other find scripts I have the impression that each find/config script will have to add support manually (ie: it's not something that CMake takes care of internally).

Are there any architectural or design related rationales for why such support should not be added to [catkinConfig.cmake.in](https://github.com/ros/catkin/blob/c6c9dc63322a44c0711719c8999ba0a887d24445/cmake/catkinConfig.cmake.in)?

**Comment by gavanderhoorn** [comment]
One thing I came up with myself is that the packaging infrastructure right now does not support the concept of optional dependencies (related ROS Answers questions: [#q217719](https://answers.ros.org/question/217719) and [#q202251](https://answers.ros.org/question/202251)).

Allowing optional dependencies in the build script itself then could be seen as divergent, as it could lead to differences between released binaries and those built from sources.

**Comment by dirk-thomas** [comment]
There are two parts here:

* The CMake config for `catkin`: this could be extended to support `OPTIONAL_COMPONENTS`. I don't see a reason why not to.

  * Just as a side note in `ament` the CMake config file doesn't even allow to pass `COMPONENTS`. Instead in a ROS 2 package you `find_package` every other package separately. There are convenience methods to use include dirs, libraries, etc. of multiple packages (to replace the usage of `catkin_INCLUDE_DIRS` etc.).

* The CMake config files generated for catkin packages: those currently don't even support `COMPONENTS`. If a package wants to support that it has to generate its own CMake config file atm.

I think it still makes sense to have the feature. For the release process a package needs to decide if it wants to declare the optional dependency as a mandatory one in the manifest or not.

**Comment by gavanderhoorn** [comment]
Makes sense.

Thanks for the clarifications.

**Comment by dirk-thomas** [comment]
Since there seems to be no immediate interest to implement this feature I will go ahead and close the ticket for now. Please feel free to provide a pull request for the feature.
