### ISSUE TITLE
Unbound variable CATKIN_SETUP_UTIL_ARGS in setup.sh

### ISSUE THREAD

**Issue by at-wat** [ros/catkin#904]
https://github.com/ros/catkin/blob/3519c73394d2121b85ddbee488e4c44d4d942118/cmake/templates/setup.sh.in#L60

Sourcing setup.sh fails with `set -eu` since `CATKIN_SETUP_UTIL_ARGS` is not set by default.
This causes a problem in CI environment in my use case.

It should be better to set a default value to the variable.

**Comment by dirk-thomas** [comment]
Please consider providing a pull request to support this non-standard use case.
