### ISSUE TITLE
catkin installs some not binary files to #{prefix}/bin

### ISSUE THREAD

**Issue by wjwwood** [ros/catkin#91]
While setting up a formula for catkin, Homebrew complained:

```
Warning: Non-executables were installed to "bin".
Installing non-executables to "bin" is bad practice.
The offending files are:
    /usr/local/Cellar/catkin/0.3.19/bin/catkin_util.sh
    /usr/local/Cellar/catkin/0.3.19/bin/CMakeLists.txt
```

I happen to agree with it.  That script is either in the wrong place or it might need to lose the extension and get a #!.  The CMakeLists.txt shouldn't be in there at all.

**Comment by gerkey** [comment]
Switched to installing scripts by name 4799cc5.  Killed #76 while I was at it.  Still need to look at the contents of `bin/em`, #92.
