### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by sergeant-wizard** [ros/catkin#921]
Currently, the setup script is only provided for either `sh`, `bash`, or `zsh`.
Is it likely that if I create a corresponding script of `setup.{sh,bash,zsh}` for [the fish shell](https://fishshell.com/) under `cmake/templates` in this repo, the PR would be merged?

That would be a great feature to have because currently, the only option for fish shell users using ROS is to switch to another shell just for `source`ing the setups.

Just for comparison, the `virtualenv` for python has a corresponding script to be sourced for the fish shell along with bash and zsh:
https://github.com/pypa/virtualenv/blob/263283be88061b965ead9ebff47c37021d7d3f62/virtualenv_embedded/activate.fish

**Comment by dirk-thomas** [comment]
Yes, a pull request to add support for fish would be accepted.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket. Please feel free to provide a pull request as mentioned before.

**Comment by sunapi386** [comment]
You can use utilities written in bash with (bass)[https://github.com/edc/bass]. So you can install bass, and then:

```fish
bass source /opt/ros/kinetic/setup.bash
```
Then you can seee
```fish
 ~ printenv | grep ROS
     
ROSLISP_PACKAGE_DIRECTORIES=
ROS_DISTRO=kinetic
ROS_ETC_DIR=/opt/ros/kinetic/etc/ros
ROS_MASTER_URI=http://localhost:11311
ROS_PACKAGE_PATH=/opt/ros/kinetic/share
ROS_ROOT=/opt/ros/kinetic/share/ros
ROS_VERSION=1
```
