### ISSUE TITLE
Installation instruction not sufficient

### ISSUE THREAD

**Issue by vincentb1** [ros/catkin#922]
Hello,
I had to install catkin outside of ROS in order to install https://github.com/wjwwood/serial, which I had to do from source because it does not come with a MAC OS X installer.

I did the catkin installation from source and I found that information how to install was not so clear.

I did the following steps:
```
git clone -b kinetic-devel https://github.com/ros/catkin.git
cd catkin
mkdir build
cd build
cmake ..
make 
make test
sudo make install
```
After this when I tried to compile wjwwood/serial, I had the following error: 
```
Traceback (most recent call last):
  File "/Users/vincentbelaiche/Projects/wjwwood-serial/serial/build/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named catkin.environment_cache
CMake Error at /usr/local/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/Users/vincentbelaiche/Projects/wjwwood-serial/serial/build/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /usr/local/share/catkin/cmake/all.cmake:186 (safe_execute_process)
  /usr/local/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:5 (find_package)
```

So, indeed I had to add the following steps to the catkin installation procedure described earlier:
```
cd ..
sudo pip install -e .
```

and then it solved the wjwwood/serial compilation problem.

It is a pity that this is not done automatically by the cmake install script. OK, this creates a dependency on pip, so there are two possible approaches:
* test for the presence of pip and make an error message if pip is not there &mdash; maybe cmake can get it… or
* try to install better without pip

I am sorry, but I have little expertise in python, so I cannot help more.

**Comment by dirk-thomas** [comment]
The Python code of the package of already being installed by the CMake logic (see https://github.com/ros/catkin/blob/cc161de9d737aafbcee61bf69a96dd2d4e9c99ae/CMakeLists.txt#L23). So the question is why is that not sufficient in your is case.

Can you please provide more information what exact files are being installed during the `sudo make install` step and to which location. Also what Python version are you using when the Python module is not being found?

**Comment by wjwwood** [comment]
I believe you're missing the `source <install location>/setup.bash` step most likely. In your case, it's probably `/usr/local/setup.bash`.

You could also put that package into a workspace with catkin and avoid installing catkin itself to your system, see: https://wiki.ros.org/catkin/Tutorials/using_a_workspace

**Comment by dirk-thomas** [comment]
I will close this issue since there was no more response assuming the instructions resolved the problem for you. Please feel free to comment and the issue can be reopened if necessary.
