### ISSUE TITLE
"fatal error: X.h: No such file or directory" occurs with catkin_make (but not with catkin_tools)

### ISSUE THREAD

**Issue by 130s** [ros/catkin#925]
My team just noticed our c++ package fails to build with `catkin_make` but passes with `catkin_tools`. Solution @geoffreychiou found was to add `add_dependencies` in CMakeLists.txt as the catkin_make's doc instructs as follows. We found, 

- From catkin tools documentatio [here](http://catkin-tools.readthedocs.io/en/latest/migration.html):

> Packages do not need to define target dependencies on ROS messages built in other packages.

- For catkin_make documentation [here](http://docs.ros.org/jade/api/catkin/html/howto/format2/cpp_msg_dependencies.html):

> Since you presumably have build targets using the message or service headers, add this to ensure all their headers get built before any targets that need them:
>
> ```
> add_dependencies(your_program ${catkin_EXPORTED_TARGETS})
> add_dependencies(your_library ${catkin_EXPORTED_TARGETS})
> ```

It'd be great from lazy users perspective for `catkin_make` to find the dependency.

We use catkin_tools on CI as it runs faster so that we can reduce job time (and our developers tend to use it too for the same reason), but use catkin_make for our production system as it's the ROS official tool. Because of that, we never noticed this issue until we start deployment.

Unfortunately I won't have time soon to provide a reproducible sample.

**Comment by 130s** [comment]
I think this has been already discussed extensibly, like https://github.com/ros/catkin/issues/801, and I understand that functionality to resolve the dependency won't be realized.
Only update might be the comparison with `catkin_tools` where the dependency gets resolved.  I'm find with this to be closed, but I'd appreciate if there's any comments.

**Comment by dirk-thomas** [comment]
> It'd be great from lazy users perspective for `catkin_make` to find the dependency.

`catkin_make` configures all packages in a single CMake context. Therefore it needs explicit target dependencies. I don't see any technical way to "find" these automatically for the user. Therefore I will close this as "wontfix". Please feel free to propose specific changes if you think this is possible.

> Only update might be the comparison with catkin_tools where the dependency gets resolved.

Btw. neither in `catkin_tools` nor in `catkin_make_isolated` " the dependency gets resolved". Since both tools build each package separately all targets of a dependency package have by definition been completed.

**Comment by NikolausDemmel** [comment]
@130s just my 2 cents: You could add `catkin_make` builds to your CI, maybe just for the main branches and maybe just running nightly or something like that. That would at least catch issues earlier. Otoh, maybe catkin_lint can detect this situation or can be extended to detect it...
