### ISSUE TITLE
catkin_add_gtest_build_flags is missing

### ISSUE THREAD

**Issue by trainman419** [ros/catkin#931]
http://wiki.ros.org/gtest describes a cmake macro called `catkin_add_gtest_build_flags()` but it doesn't appear to be present in catkin.

I have a couple of libraries that include shared test functions that use gtest (see https://github.com/ros/ros_comm/issues/1357), and these are currently under-linked on OSX. I'm able to fix them by linking directly against `${GTEST_LIBRARIES}` but it seems like it would be better to use the `catkin_add_gtest_build_flags()` macro for this.

**Comment by dirk-thomas** [comment]
Such a function does to my knowledge not exist in catkin and has never existed. Looking at the history of the wiki page it seems this was blindly renamed along time ago: http://wiki.ros.org/action/diff/gtest?action=diff&rev1=53&rev2=54

Currently there are only function to create binaries with gtest, e.g. `catkin_add_executable_with_gtest`. Similar function for libraries could be introduced if that is a common pattern.

**Comment by dirk-thomas** [comment]
I removed the invalid reference from the wiki page: http://wiki.ros.org/action/diff/gtest?action=diff&rev1=63&rev2=64
