### ISSUE TITLE
Handling package-local CMake modules

### ISSUE THREAD

**Issue by zultron** [ros/catkin#950]
When a ROS package uses the "Foo" project with no upstream-provided CMake module, the author may wish to write e.g. `cmake/FindFoo.cmake` and then `find_package(Foo)`.

However, the ["CMake coding standards"][1] document says simply, "Do not set `CMAKE_MODULE_PATH`" without suggesting the correct way to do this.

Others who have asked this question haven't found satisfactory answers, such as [this question][2] on ROS Answers (the OP ended up answering his own question by setting `CMAKE_MODULE_PATH`, contradictory to coding standards).

Anyway, other experienced ROS developers seem unaware of and violate this standard, such as [here][3].  (I understand `cmake_modules` makes this an obsolete example, and the line could simply be removed, but....)

The [Indigo Migration guide][4] suggests that CMake modules might be contributed to the ROS `cmake_modules` package.  However, that package's maintainers wouldn't be interested in modules for an unpublished package, and `.rosinstall`ing a locally-forked version with `FindFoo.cmake` is a lot of overhead.

So what is the correct way to find a CMake module that's local to a package?  Is this something missing from catkin, something missing from the docs, or something best accomplished some other way?

[1]: https://github.com/ros/catkin/blob/kinetic-devel/doc/user_guide/standards.rst
[2]: https://answers.ros.org/question/189223/how-can-i-reference-an-external-project-with-catkin/
[3]: https://github.com/PickNikRobotics/ros_control_boilerplate/blob/melodic-devel/CMakeLists.txt#L24
[4]: http://wiki.ros.org/indigo/Migration#cmake_modules

**Comment by sloretz** [comment]
Hi @zultron, is that link to the right question? I don't see `CMAKE_CXX_FLAGS` on that page.

**Comment by zultron** [comment]
Argh, really dumb copy'n'paste error.  I'll fix the original description to `CMAKE_MODULE_PATH`!

**Comment by sloretz** [comment]
Ah, I should have figured that out from the context.

I wasn't able to find the rationale for avoiding `CMAKE_MODULE_PATH` either. It was added in ros/catkin#216. @tkruse do you remember?

An alternative to using `CMAKE_MODULE_PATH` is to create your own package that installs the find module ([install rule in `cmake_modules`](https://github.com/ros/cmake_modules/blob/b6c1fb91b0316dad78ef58aab90da19aeb76ed15/CMakeLists.txt#L8-L10)). For example, create a package `foobar_cmake_module` which installs `Findfoobar.cmake`. Then add `<build_depend>foobar_cmake_module</build_depend>` to the `package.xml` of the package which needs to find it.

**Comment by dirk-thomas** [comment]
Without further information why this "rule" was added to the docs I suggest to remove it since I don't see a reason this usage shouldn't be "allowed". See #951.

**Comment by zultron** [comment]
I submitted a new issue in fkie/catkin_lint#55 in case someone over there wants to weigh in over here.  If #951 is merged, `catkin lint` will need the equivalent update.

I agree with @dirk-thomas.  If there's no known reason to disallow modifying `CMAKE_MODULE_PATH`, relaxing this standard reduces confusion and effort for ROS package authors.

If there does turn out to be a good reason for it, @sloretz's suggestion to create a special package is as elegant a workaround as I can imagine in cases where contributing new rules to the ROS `cmake_modules` package is impractical.  Thanks!

**Comment by zultron** [comment]
Since #951 is merged, I went ahead and submitted PR fkie/catkin_lint#56, reflecting the change in `catkin lint`.

Thanks, @dirk-thomas.
