### ISSUE TITLE
can't install catkin on Ubuntu 16.04

### ISSUE THREAD

**Issue by EricFiore** [ros/catkin#960]
I'm completely new to ROS and Catkin and fairly new to Ubuntu.  I have already installed ROS Kinetic and Gazebo8 on my system and they seem to be working.  I am now trying to install Catkin and having 
trouble.  I started by using the command:

sudo apt-get install cmake python-catkin-pkg python-empy python-nose python-setuptools libgtest-dev build-essential

then:

sudo apt-get install ros-kinetic-catkin
which worked flawlessly.  Next step was:
mkdir  -p ~/catkin_ws/src
cd ~/catkin_ws/src

 no problem so far.  The directory was created and I was able to cd into it. 

catkin_init_workspace

and this is where I fail.  The error message I get is:
_The program 'catkin_init_worksapce is currently not install.  You can install it by typing:
sudo apt install catkin_

when I type the above instruction I get an error about umet dependencies.
_catkin : Depends: python-catkin-pkg but it is not going to be installed_

I believe the problem is mixing the streams.  I try to uninstall catkin to start fresh and I get a message that catkin is not installed.  So I try to install catkin and I get a message that catkin is already installed.
Any help is much appreciated.

**Comment by sloretz** [comment]
Hi @EricFiore, Welcome. In the [ROS support guidelines](http://wiki.ros.org/Support) we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

There are a few benefits:
* Many more people read those questions so you are more likely to get a timely answer.
* Future users with similar problems will search there and find your question.
* The issue tracker in this repo has just bugs and feature requests.

I will close this ticket here for now. If it does turn out to be a bug then I would be happy to reopen it.

If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket. You might be interested in these past questions

https://answers.ros.org/question/258444/sudo-apt-install-catkin-not-working/
https://answers.ros.org/question/212492/catkin_make-command-not-found/
