### ISSUE TITLE
GMock broken in kinetic, results in "double free or corruption"

### ISSUE THREAD

**Issue by alex-gee** [ros/catkin#963]
When creating a Mock class inside a test case the test runs but at end it crashes with
"double free or corruption". Only happens on kinetic, melodic is fine.

Minimal example
```
class FooMock : public Foo
{
public:
  MOCK_METHOD0(sayHello, bool());
};

TEST(TestSuite, testCase)
{
  FooMock mock;
}

// Run all the tests that were declared with TEST()
int main(int argc, char **argv){
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

Steps to reproduce:
Use [https://github.com/alex-gee/gmock_bug_demo](https://github.com/alex-gee/gmock_bug_demo)
and run `catkin_make_run_tests_gmock_bug_demo` on a kinetic machine.

Also happens on **Travis** with industrial_ci (Note that both builds are green nevertheless):
Broken (kinetic) see Line 710 [https://travis-ci.org/alex-gee/gmock_bug_demo/jobs/438233466](https://travis-ci.org/alex-gee/gmock_bug_demo/jobs/438233466)
Fine (melodic) [https://travis-ci.org/alex-gee/gmock_bug_demo/jobs/438233467](https://travis-ci.org/alex-gee/gmock_bug_demo/jobs/438233467)

**Comment by dirk-thomas** [comment]
`catkin` only provides CMake logic to find GTest/GMock, build it if necessary and link tests against the library. Any runtime problem is likely something `catkin` can't do anything about. Have you compared the `Goggletest` version between Kinetic and Melodic? Likely the difference in behavior is due to the difference in version.

**Comment by alex-gee** [comment]
I am on it. 

Seems that it was my mistake since I overlooked that I have to use `catkin_add_gmock` and not `catkin_add_gtest` so https://github.com/alex-gee/gmock_bug_demo/commit/0a91e20e0dc84fca517e1763ed66f27ecb577691 fixes the issue. See https://travis-ci.org/alex-gee/gmock_bug_demo/builds/438315782

Maybe related to https://github.com/google/googletest/issues/930#issuecomment-348718113 ?

I would consider this closed but would be in favor of add documentation for `catkin_add_gmock`, added to my todo list. Hopefully I find the time soon.

**Comment by dirk-thomas** [comment]
> I would consider this closed but would be in favor of add documentation for `catkin_add_gmock` ...

Since you created the issue you should be able to close it. Please feel free to do so or keep this open until you had a chance to improve the documentation. Thanks.

**Comment by dirk-thomas** [comment]
> I would consider this closed but would be in favor of add documentation for catkin_add_gmock, added to my todo list. Hopefully I find the time soon.

@alex-gee Did you have a chance to contribute to the documentation in the mean time?

**Comment by dirk-thomas** [comment]
Closing due to no response.
