### ISSUE TITLE
Add support for auto-generating setup.py

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#98]
In the case where `generate_messages()` is called, but there isn't any `setup.py` file, we should autogenerate `setup.py` (into build space) to make and install an egg of the generated Python message code.

Probably condition this on whether `catkin_python_setup()` has been called.  If so, then be sure to document the ordering dependency.

**Comment by dirk-thomas** [comment]
This is not a required feature and due to the simplicity to write the file manually not planned

**Comment by vrabaud** [comment]
Well, it is very simple, but you still need to know how to do it and the docs should give an example :

#!/usr/bin/env python
from distutils.core import setup
from catkin_pkg.package import parse_package_for_distutils

d = parse_package_for_distutils()
d['packages'] = ['module1', 'module2']
d['package_dir'] = {'': 'python'}
d['install_requires'] = ['dependency1', 'dependency2']

setup(**d)

**Comment by tkruse** [comment]
Hi Vincent,

I work on creating a catkin_create_pkg script which generates
CmakeLists.txt and package.xml. I can well imagine adding to this
extensions to create more default structure, like --cpp generating
include/packagename, src, and --python generating such a setup.py. It would
just be a skelleton, but it can contain comments to guide the user.

Would that satisfy your request?

**Comment by vrabaud** [comment]
Sure, a script would definitely help even though I am a power user :) I was just referring to the lack of docs here: how was I supposed to know about that functionality ? Catkin (maybe in the macro catkin_python_setup docs) could point to the docs in catkin_pkg.
