### ISSUE TITLE
Debian: Why does `python3-catkin-pkg` conflict with `catkin, python-catkin-pkg`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ros/catkin#991]
We're in the process of porting some code from Python 2 to Python 3 (downstream of [drake](https://drake.mit.edu/)); I wanted to install `python3-rospkg` and `python3-catkin-pkg`, but found that it conflicts with `python-catkin-pkg` (and thus wants to completely uninstall ROS1 Melodic).

Is there a *really* strong reason for this?
Or is purely because the manifests conflict b/c both want to put binaries in the same place? (e.g. `/usr/bin/catkin_create_pkg`, vs. just using `/usr/bin/catkin3_create_pkg`, which would follow suite with other Python tools, like `pip`, `ipython`, etc.)

If there isn't a strong reason, is there a way that this can be fixed, at least while Python 2 is still the default Python version for Ubuntu (Bionic, 18.04)?

NOTE: As a workaround, I just installed the relevant stuff into a `virtualenv`.

**Comment by dirk-thomas** [comment]
The repository containing the Python package `catkin_pkg` is: https://github.com/ros-infrastructure/catkin_pkg

> Is there a _really_ strong reason for this?

Yes, both packages install the same global executables which is not possible.

> is there a way that this can be fixed

You don't need both version of the global executables - either of them is fine. What you do need are the actual Python modules of `catkin_pkg` for both Python versions. Those can be side-by-side installed: `python-catkin-pkg-modules` and `python3-catkin-pkg-modules`.

**Comment by EricCousineau-TRI** [comment]
Ah, sorry! Will post follow-up as an issue there.

EDIT: Filed in `rospkg`: https://github.com/ros-infrastructure/rospkg/issues/163
