### ISSUE TITLE
local_setup.sh

### ISSUE THREAD

**Issue by rhaschke** [ros/catkin#994]
Using `catkin-tools`, I get the following error since `local_setup.sh` was recently introduced in #993:
```
Cannot symlink from /homes/rhaschke/src/ros/devel/.private/rviz/local_setup.sh to existing file /homes/rhaschke/src/ros/devel/./local_setup.sh
Warning: Source hash: 1b5f4fec545a06a4cc4723db5116e3f2
Warning: Dest hash: 51a457f5bad6a3827efef461047f77e8
```
Is there a corresponding fix missing in `catkin-tools` or is this a bug in `catkin`?

**Comment by dirk-thomas** [comment]
I am not sure where the `.private` path comes from in the error message. It doesn't look like anything from `catkin`. It could be that `catkin_tools` needs to be updated somehow? @wjwwood FYI

**Comment by NikolausDemmel** [comment]
Just as a note (I can't further look into the error myself): The `.private` paths should come from catkin_tools "linked-devel" layout: https://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace.html

**Comment by dirk-thomas** [comment]
> The .private paths should come from catkin_tools "linked-devel" layout

That sounds indeed like `catkin_tools` needs some update then. Can you please open a ticket in the `catkin_tools` repo for it. Thanks.

**Comment by rhaschke** [comment]
Closing this in favour of https://github.com/catkin/catkin_tools/issues/538
