### ISSUE TITLE
Release version 0.7.15/0.7.16 for ROS Kinetic

### ISSUE THREAD

**Issue by javigallostra** [ros/catkin#999]
I'm new to the repo, coming from this [question](https://answers.ros.org/question/318596/upgrading-catkin-to-0716-on-ros-kinetic/). 0.7.15/16 has been released for Melodic but not for Kinetic, I have no idea whatsoever if it is possible but could we release those versions for Kinetic too?

**Comment by dirk-thomas** [comment]
Once the new version has been synced into the public repo of Melodic and sit there for a bit (and no regressions have been found) the same version will be released into Lunar and Kinetic.

**Comment by mathias-luedtke** [comment]
10 weeks have passed since v0.7.17..
Any status update?

**Comment by dirk-thomas** [comment]
A new release is in the pipeline: ros/rosdistro#21488.
